### ISSUE TITLE
AttributeError: type object 'Detections' has no attribute 'from_coco_annotations'

### ISSUE THREAD

**Issue by Sebi2106** [roboflow/supervision#1004]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I copied a tutorial where somebody used the from_coco_annotations function. Now I get this error: Exception has occurred: AttributeError
type object 'Detections' has no attribute 'from_coco_annoations'
  File "/home/labor/Dokumente/Studienarbeit_productiv/Code/transformer/own-detr/agar_loader.py", line 65, in <module>
    detections = sv.Detections.from_coco_annotations(coco_annotation=annotations)
AttributeError: type object 'Detections' has no attribute 'from_coco_annoations '

I saw that they removed the from_coco_annoations to from_coco but that also didn't work for me. 

Any suggestions how to fix this problem?

### Example

    image_processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50", revision="no_timm") 
    train_dataset = AgarDetection(image_directory_path=train_path, image_processor=image_processor, train=True)
    val_dataset = AgarDetection(image_directory_path=val_path, image_processor=image_processor, train=False)

    print("Number of training examples:", len(train_dataset))
    print("Number of validation examples:", len(val_dataset))
    
    image_ids = train_dataset.coco.getImgIds()
    image_id = random.choice(image_ids)
    print('Image #{}'.format(image_id))

    image = train_dataset.coco.loadImgs(image_id)[0]
    annotations = train_dataset.coco.imgToAnns[image_id]
    image_path = os.path.join(train_dataset.root, image['file_name'])
    image = cv2.imread(image_path)

    detections = sv.Detections.from_coco(coco_annotation=annotations)

    categories = train_dataset.coco.cats
    id2label = {k: v['name'] for k,v in categories.items()}

    labels = [
        f"{id2label[class_id]}" 
        for _, _, class_id, _ 
        in detections
    ]

    box_annotator = sv.BoxAnnotator()
    frame = box_annotator.annotate(scene=image, detections=detections, labels=labels)
 
    cv2.imshow("random image", image)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @Sebi2106 👋🏻 Thanks for your interest in `supervision`. What version of `supervision` are you using?

**Comment by Sebi2106** [comment]
Hi, I'm using supervision version 0.19.0.

**Comment by SkalskiP** [comment]
`from_coco_annotations` is deprecated. You'd need to downgrade `supervision` to `0.10.0` to use it.

**Comment by SkalskiP** [comment]
I'm closing this issue. Feel free to reopen it if you need any more help.

**Comment by Sebi2106** [comment]
> `from_coco_annotations` is deprecated. You'd need to downgrade `supervision` to `0.10.0` to use it.

Yes that worked, thank you.

**Comment by SkalskiP** [comment]
@Sebi2106 It's great to hear that the problem was solved. 🔥
