### ISSUE TITLE
[Color] - constants like `WHITE`, `BLACK`, `RED`, and so on have the wrong type.

### ISSUE THREAD

**Issue by marcospgp** [roboflow/supervision#1010]
### Bug

`sv.Color.WHITE` has type `classproperty`, for example.

**Comment by SkalskiP** [comment]
Hi @marcospgp 👋🏻 Thanks a lot for letting us know. @LinasKo or @onuralpszr, do any of you have time to take a look at this?

**Comment by marcospgp** [comment]
`PolygonZone.trigger` is also insufficiently typed:

`(method) def trigger(detections: Detections) -> ndarray[Unknown, Unknown]`

I would recommend enabling strict python type checking, which would uncover all of these issues.

At least for me typing is a very important factor.

Thank you guys!

**Comment by onuralpszr** [comment]
> Hi @marcospgp 👋🏻 Thanks a lot for letting us know. @LinasKo or @onuralpszr, do any of you have time to take a look at this?

Looking.

**Comment by onuralpszr** [comment]
> `PolygonZone.trigger` is also insufficiently typed:
> 
> `(method) def trigger(detections: Detections) -> ndarray[Unknown, Unknown]`
> 
> I would recommend enabling strict python type checking, which would uncover all of these issues.
> 
> At least for me typing is a very important factor.
> 
> Thank you guys!

Thank you and let me take look this one too

**Comment by marcospgp** [comment]
I think in general all of your usage of `np.ndarray` should be annotated with `numpy.typing.NDArray` according to numpy's typing docs (such as `NDArray[np.single]` or `NDArray[Any]` for things like function return value types).

The instances I mentioned are just examples, the underlying issue is likely spread throughout the codebase including from my experience working with the library.

Not to sound harsh, I super appreciate your work and this project is useful & great! Any effort you're willing to allocate towards improving typing is super appreciated by me and likely many others!

**Comment by onuralpszr** [comment]
> I think in general all of your usage of `np.ndarray` should be annotated with `numpy.typing.NDArray` according to numpy's typing docs (such as `NDArray[np.single]` or `NDArray[Any]` for things like function return value types).
> 
> The instances I mentioned are just examples, the underlying issue is likely spread throughout the codebase including from my experience working with the library.
> 
> Not to sound harsh, I super appreciate your work and this project is useful & great! Any effort you're willing to allocate towards improving typing is super appreciated by me and likely many others!

I will take look all
