### ISSUE TITLE
Enhance `sv.LabelAnnotator` by adding argument for round edges

### ISSUE THREAD

**Issue by xaristeidou** [roboflow/supervision#1027]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

In `sv.LabelAnnotator` an attribute that will apply round edges to the label box can be added for prettier labels.

I have modified the annotator by adding an attribute:
`round_edges`: bool = True

 
![Screenshot from 2024-03-20 23-40-11](https://github.com/roboflow/supervision/assets/65918758/9b1668f3-e3f1-4bfe-8b94-793d3fd06c5b)

### Use case

Better visualization results.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @xaristeidou 👋🏻 I think it's a cool idea, but I would replace `round_edges` with `corner_radious`.

**Comment by xaristeidou** [comment]
@SkalskiP So for `corner_radius` I assume that it will be integer and if the value is higher than the half of the lower dimension (height or width) of the box, it should be clipped?

**Comment by xaristeidou** [comment]
@SkalskiP  Accidentally closed it.

**Comment by SkalskiP** [comment]
@xaristeidou 

> So for `corner_radius` I assume that it will be integer and if the value is higher than the half of the lower dimension (height or width) of the box, it should be clipped?

Exactly!

> Accidentally closed it.

Don't worry, it happens to me all the time.

**Comment by xaristeidou** [comment]
I close the issue, implemented in PR #1037

**Comment by SkalskiP** [comment]
Thanks for your help @xaristeidou 🙏🏻
