### ISSUE TITLE
Opencv channel swap in ImageSinks

### ISSUE THREAD

**Issue by zhmiao** [roboflow/supervision#1038]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Hello I realize opencv used BGR instead of RGB, and therefore, the following code will cause channel swap: 

```python
with sv.ImageSink(target_dir_path=output_dir, overwrite=True) as sink:
    annotated_img = box_annotator.annotate(
        scene=np.array(Image.open(img_dir).convert("RGB")),
        detections=results,
        labels=labels,
    )
    sink.save_image(
        image=annotated_img, image_name="test.jpg"
    )
```
Unless I use `cv2.cvtColor(annotated_img, cv2.COLOR_RGB2BGR)` . This also happens with video sinks and other places using `Opencv` for image writing. 

I wonder if it is possible to add this conversion by default or at least mention this in the docs? Thanks a lot! 

### Use case

For savings with `ImageSink()`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @zhmiao 👋🏻 In fact, Supervision does not change the channel order. By default, Supervision uses OpenCV as its image/video processing engine, and BGR is the default color order for OpenCV. Support for Pillow began rolling out only in the [last release](https://github.com/roboflow/supervision/releases/tag/0.19.0), significantly simplifying the annotation of Pillow images.


While addressing the issue [#1041](https://github.com/roboflow/supervision/pull/1041), I added a note in the documentation for [`VideoSink`](https://supervision.roboflow.com/develop/utils/video/#supervision.utils.video.VideoSink.write_frame) and [`ImageSink`](https://supervision.roboflow.com/develop/utils/image/#supervision.utils.image.ImageSink.save_image) about the expected color order. Do you think it would be a good idea to directly allow the acceptance of Pillow Images?

**Comment by zhmiao** [comment]
Hello @SkalskiP, thank you so much for the information! I think as long as they are mentioned in the docs, it would be enough for me because Supervision is using opencv by default. I always forget opencv and PIL use different channel formats. I think whether to add direct compatibility to the sinks depends on whether Supervision thinks there will be a lot of people like me who directly uses PIL images in sinks lol. Thanks again for the clarification!

**Comment by zhmiao** [comment]
I am closing this issue as it is resolved! Thanks for your help!
