### ISSUE TITLE
[Detections] extend `from_transformers` with `class_names` support 

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#1043]
### Description

Currently, Supervision supports class name extraction exclusively for Inference and Ultralytics libraries. Let's enhance [`from_transformers`](https://github.com/roboflow/supervision/blob/781a064d8aa46e3875378ab6aba1dfdad8bc636c/supervision/detection/core.py#L391) by incorporating support for Transformers. Take a look at [`from_inference`](https://github.com/roboflow/supervision/blob/781a064d8aa46e3875378ab6aba1dfdad8bc636c/supervision/detection/core.py#L449) and [`from_ultralytics`](https://github.com/roboflow/supervision/blob/781a064d8aa46e3875378ab6aba1dfdad8bc636c/supervision/detection/core.py#L177) for more reference.

### API

The code below should annotate the resulting image with class names.

```python
def from_transformers(cls, transformers_results: dict, id2label: Dict[int, str]) -> Detections:
    pass
```

```python
import torch
import supervision as sv
from PIL import Image
from transformers import DetrImageProcessor, DetrForObjectDetection

processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")
model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")

image = Image.open(<PATH TO IMAGE>)
inputs = processor(images=image, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)

width, height = image.size
target_size = torch.tensor([[height, width]])
results = processor.post_process_object_detection(
    outputs=outputs, target_sizes=target_size)[0]
detections = sv.Detections.from_transformers(results, id2label=model.config.id2label)

bounding_box_annotator = sv.BoundingBoxAnnotator()
label_annotator = sv.LabelAnnotator()

annotated_image = bounding_box_annotator.annotate(
    scene=image, detections=detections)
annotated_image = label_annotator.annotate(
    scene=annotated_image, detections=detections)
```

![basic-annotation](https://media.roboflow.com/supervision_detect_and_annotate_example_1.png)

### Additional

- [Transformers DETR Docs](https://huggingface.co/docs/transformers/en/model_doc/detr)
- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by jeslinpjames** [comment]
I'd like to try doing this

**Comment by onuralpszr** [comment]
@jeslinpjames  I assigned to you and thanks for PR already
