### ISSUE TITLE
Better handling of wrong data types of mask for sv.PolygonZone()

### ISSUE THREAD

**Issue by GeorgePearse** [roboflow/supervision#106]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

<img width="898" alt="image" src="https://github.com/roboflow/supervision/assets/47161914/6eebe556-97f1-452b-8757-17062548ca12">

OpenCV errors out with an uninformative error when the dtype of the mask is wrong. 

Would be good to add catch if dtype != np.int32 and raise an Exception.

### Use case

I was trying to create a mask in CVAT, the exported segmentation had decimal places, np.array(coords) did not convert to np.int32, and I was confused by the bad error message.

This is likely to happen to other users too .

### Additional

Happy to submit PR

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by GeorgePearse** [comment]
Yep, better idea

**Comment by SkalskiP** [comment]
I'll try to make it happen with next release :)
