### ISSUE TITLE
The line anottator doesn't work well

### ISSUE THREAD

**Issue by carbonto** [roboflow/supervision#109]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

When I draw the line to count people passing it with the linezone and linezone annotator classes it sometimes counts people passing far from the line.

All this has been done using yolov8.

### Minimal Reproducible Example

import cv2

from ultralytics import YOLO
import supervision as sv
import numpy as np

#Line for example_01
# LINE_START = sv.Point(0, 227)
# LINE_END = sv.Point(401, 227)

#Line for prueba2
# LINE_START = sv.Point(0, 500)
# LINE_END = sv.Point(1275, 500)

#Line for beach_video 
#Linea puesta mas arriba de lo que seria logico porque si no la gente de fuera la linea detecta la bounding box y los cuenta como que han entrado
LINE_START = sv.Point(98,1737)
LINE_END = sv.Point(1182, 1477)

def main():
    line_counter = sv.LineZone(start=LINE_END, end=LINE_START) #LineZone is a line that can count objects
    line_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.5) #Format of LineZone
    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=1,
        text_scale=0.5
    )

    segmentation_model = "yolov8n-seg.pt"
    detection_model = "yolov8n.pt"
    onnx = "yolov8n.onnx"
    model = YOLO(detection_model) #yolov8n faster but less accurate than yolov8x
    path = "Examples/prueba2.mp4"
    path2 = "102 - Armada1 - 2023-05-09 12-30-31-345.mp4"

    for result in model.track(source=path2, show=False, stream=True, agnostic_nms=False,imgsz=[640,640],device='0',classes=[0]):
        
        frame = result.orig_img
        detections = sv.Detections.from_yolov8(result)
        
        if result.boxes.id is not None: #prevent crashing when no object is detected
            detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
        
        detections = detections[detections.class_id == 0] #Only detect people

        
        labels = [
            f"{model.model.names[class_id]} {confidence:0.2f}"
             for _, _, confidence, class_id, _
             in detections
        ]

        frame = box_annotator.annotate(  #Draws boxes around objects
            scene=frame, 
            detections=detections,
            labels=labels
        )
        #Draws line and counts objects
        line_counter.trigger(detections=detections)
        line_annotator.annotate(frame=frame, line_counter=line_counter)
        cv2.namedWindow('yolov8', cv2.WINDOW_NORMAL)
        cv2.imshow("yolov8", frame)
        if (cv2.waitKey(30) == 27):
            break
        #Prints the number of objects that have crossed the line
        print("in_counter: ",line_counter.in_count)
        print("out_counter: ",line_counter.out_count)
if __name__ == "__main__":
    main()

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @carbonto 👋🏻! Thanks for your interest in our project. This is a known issue, and we are working on a solution. You can learn more about our internal investigation here (https://github.com/roboflow/supervision/issues/87). Our community is also working on some workaround here (https://github.com/roboflow/supervision/discussions/107).

I'm marking this issue as duplicate and closing it. But feel free to be active at https://github.com/roboflow/supervision/issues/87 and https://github.com/roboflow/supervision/discussions/107.
