### ISSUE TITLE
An elegant way to apply thresholds and area filters etc. at the class level

### ISSUE THREAD

**Issue by GeorgePearse** [roboflow/supervision#111]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Thanks once more, this package has saved me a lot of time, and already improved how my code looks and feels. 

Possible I'm just requesting something to be added to the docs.

I can't work out a semi-elegant way to apply thresholds at the class level, or apply area filters at the class level. If I just have to iterated and then merge_detections or something like that that's fine, just thought you may already have an approach. 

### Use case

You have some small object, filter any detections of that small object above a certain size. 

Every other object has a very large range of sizes.

### Additional

nope

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @GeorgePearse 👋🏻! Thanks a lot for your interest in `supervision`. 

I'm not sure if I understand your intention correctly. But if I do, **you would like to apply different filtering logical conditions to detections belonging to different classes**.

I think currently there are two ways to do it. Let's dive in! 🤿 

1. Using complex logical conditions. 
 
`supervision` allows filtering detections using logical conditions. You can read more about it [here](https://roboflow.github.io/supervision/quickstart/detections/). Importantly those logical conditions can be arbitrarily complicated. You can combine two logical conditions using "and" `&` or "or" `|`. 

Let's assume that you would like to keep only the objects of class `0` that has a confidence level over `0.5` and the objects of class `1` with an area over `400` squared pixels. 

- `detections = detections[detections.class_id == 0]` - allows you to use the class as your filtering condition
- `detections = detections[detections.confidence > 0.5]` - allows you to use the confidence as your filtering condition
- `detections = detections[detections.area > 400]` - allows you to use the area as your filtering condition

Now let's think about how we can use `&` and `|` to build more complex masks.

`(detections.class_id == 0) & (detections.confidence > 0.5)` - allows you to select only objects of class `0` that has a confidence level over `0.5`
`(detections.class_id == 1) & (detections.area > 400)` - allows you to select only objects of class `1` with an area over `400` squared pixels

`((detections.class_id == 0) & (detections.confidence > 0.5)) | ((detections.class_id == 1) & (detections.area > 400))` - allows you to select only objects of class `0` that has a confidence level over `0.5` and the objects of class `1` with an area over `400` squared pixels

I would probably do something like this in code to make it more intuitive to read:

```python
import supervision as sv

detections = sv.Detections(...)
class_0_logical_mask = (detections.class_id == 0) & (detections.confidence > 0.5)
class_1_logical_mask = (detections.class_id == 1) & (detections.area > 400)
logical_mask = (class_0_logical_mask) | (class_1_logical_mask)

detections = detections[logical_mask]
```

2. Simple logical conditions + [`sv.Detections.merge`](https://roboflow.github.io/supervision/detection/core/#supervision.detection.core.Detections.merge)

```python
import supervision as sv

detections = sv.Detections(...)
detections_0 = detections[detections.class_id == 0]
detections_1 = detections[detections.class_id == 1]

detections = sv.Detections.merge([
    detections_0[detections_0.confidence > 0.5],
    detections_1[detections_1.area > 400],
])
```

**Comment by SkalskiP** [comment]
@GeorgePearse I'm closing this issue for now. Fell free to reopen it if you'll face similar problems.

**Comment by Jordan-Pierce** [comment]
@SkalskiP I have a question regarding filtering detection. In the [docs](https://supervision.roboflow.com/latest/how_to/filter_detections/) there are some nice natively ways to filter detections, including by region. I'm using autodistill to create segmentation masks for objects, which sometimes creates masks for a larger region containing smaller, actually objects. Any recommendations on filtering out the larger masks that contain multiple smaller objects?
