### ISSUE TITLE
Adding a function to convert Supervision.Detections to Ultralytics.Results?

### ISSUE THREAD

**Issue by Jordan-Pierce** [roboflow/supervision#1134]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Due to the overlap between the two libraries, I think it'd be nice to have the ability to convert back and forth between Supervision.Detections and Ultralytics.Results, instead of it just being a one-way relationship.

### Use case

It helps if data are already in Supervision format, but needs to be converted back to Ultralytics.Results for random reasons.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hey @Jordan-Pierce! I'm afraid we can't do that. The bidirectional conversion would require us to use `ultralytics` as a dependency. We want to avoid this due to the license used by that package. Our priority is to keep `supervision` under the MIT license.

**Comment by Jordan-Pierce** [comment]
@SkalskiP understood, thanks for the prompt reply.
