### ISSUE TITLE
Take the frame by sec

### ISSUE THREAD

**Issue by sceddd** [roboflow/supervision#116]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Is there any way to collect the frame by sec, like if i have a clip length 400sec, then i'll have a list 400 frame? I have search through process_video() and figure out it took the frame base on the index of the frame.

**Comment by sceddd** [comment]
Hello,
After working a while with your videosink, i'm end up with using the fps to check the frame at every secs, i'll put the code here if anyone need it. Hope it'll help:
```
from typing import Callable
def process_video(
    source_path: str,
    target_path: str,
    callback: Callable[[np.ndarray, int], np.ndarray],
) -> None:
    """
    Process a video file by applying a callback function on each frame and saving the result to a target video file.

    Args:
        source_path (str): The path to the source video file.
        target_path (str): The path to the target video file.
        callback (Callable[[np.ndarray, int], np.ndarray]): A function that takes in a numpy ndarray representation of a video frame and an int index of the frame and returns a processed numpy ndarray representation of the frame.

    Examples:
        ```python
        >>> from supervision import process_video

        >>> def process_frame(scene: np.ndarray) -> np.ndarray:
        ...     ...

        >>> process_video(
        ...     source_path='source_video.mp4',
        ...     target_path='target_video.mp4',
        ...     callback=process_frame
        ... )
        ```
    """
    source_video_info = VideoInfo.from_video_path(video_path=source_path)
    with VideoSink(target_path=target_path, video_info=source_video_info) as sink:
        for index, frame in enumerate(
            get_video_frames_generator(source_path=source_path)
        ):
            result_frame = callback(frame, index)
            if index % sink.video_info.fps==0:
              plot_image(frame) # put the function you wanna work with the frame at here
            sink.write_frame(frame=result_frame)

**Comment by SkalskiP** [comment]
Hi @sceddd 👋🏻! Thanks a lot for your interest in our project. Sorry for the late response. Here is how I would do that.

```python
import supervision as sv

VIDEO_PATH = 'video.mp4'
video_info = sv.VideoInfo.from_video_path(video_path=VIDEO_PATH)

for index, frame in enumerate(sv.get_video_frames_generator(source_path=VIDEO_PATH)):
    if index % video_info.fps == 0:
        sv.plot_image(frame)
```

**Comment by sceddd** [comment]
Hi @SkalskiP, Thanks for your reply. I already override your process_video() and do the same thing in the last comment. After all, I appreciate it.

**Comment by SkalskiP** [comment]
No worries :) In that case, I'm closing the issue. However, I'm thinking about adding it as a feature in `supervision`.

**Comment by SkalskiP** [comment]
Hi, @sceddd 👋🏻! I just started to work on `supervision` update that will allow you to pick every N-th frame from the video.
