### ISSUE TITLE
[KeyPoints] - add `from_mediapipe` connector allowing Supervision to be used with Google MediaPipe models 

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#1174]
### Description

- Add `Skeleton.GHUM` to the [`Skeleton`](https://github.com/roboflow/supervision/blob/447ef41fc45353130ec4dccdc7eeaf68b622fb7e/supervision/keypoint/skeletons.py#L7) enum. This is the skeleton format used by Mediapipe.
- Extend the [`KeyPoints`](https://github.com/roboflow/supervision/blob/447ef41fc45353130ec4dccdc7eeaf68b622fb7e/supervision/keypoint/core.py#L16) object and add the `from_keypoints` connector.

<img width="723" alt="pose_landmarks_index" src="https://github.com/roboflow/supervision/assets/26109316/9a3181d3-8b5a-4dec-b6d2-368ee2a8f14f">

### Links

- Google Mediapipe repository: https://github.com/google/mediapipe
- Google Mediapipe example notebook: https://colab.research.google.com/github/kevinash/awesome-ai/blob/main/notebooks/6_PosesAndAction/Pose_MediaPipe.ipynb
- Google Medipipe documentation: https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by LinasKo** [comment]
Let's not get bogged down by details. I propose we implement `visibility` as confidence for now and adjust later if required. Other than that, this should be a straightforward one - get frames+keypoints from mediapipe, and implement something super similar to `from_ultralytics` :slightly_smiling_face:

**Comment by LinasKo** [comment]
Hey @David-rn,

I saw your comment on the RLE ticket. If you wish, this one is up for grabs. Should be pretty straightforward too.

Is this something you'd be interest in helping out with?

**Comment by David-rn** [comment]
Hi @LinasKo! I haven't worked with MediaPipe but I'll give it a try! 👍
