### ISSUE TITLE
tflite with supervison

### ISSUE THREAD

**Issue by abichoi** [roboflow/supervision#1218]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi, does supervsion support tflite detection results? If not, is there a way to convert tflite outputs to the Detections class format?

**Comment by SkalskiP** [comment]
Hi @abichoi 👋🏻 Thanks for your interest in `supervision`. As far as I know, it does not support `tflite`. What's the structure of your `tflite` inference result?

**Comment by SkalskiP** [comment]
That's awesome! 🔥 Good luck

**Comment by acode-x** [comment]
Hi @abichoi 
I encountered a similar use case and would appreciate it if you could share your source code.

Thank!
