### ISSUE TITLE
Loading OBB detection from ultralytics fails

### ISSUE THREAD

**Issue by dbestPacksol** [roboflow/supervision#1219]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

When passing in the results from ultralytics yolov8 OBB model to from_ultralytics it will fail and give the following: 

AttributeError: 'NoneType' object has no attribute 'cls'

due to:

class_id = ultralytics_results.boxes.cls.cpu().numpy().astype(int)

 

### Environment

- Supervision 0.20.0
- Ultralytics 8.2.18

### Minimal Reproducible Example

```python
from typing import List

import cv2
from ultralytics import YOLO
from supervision import Detections
from ultralytics.engine.results import Results
from supervision.tracker.byte_tracker.core import ByteTrack

yolo = YOLO("yolov8n-obb.pt", task="obb")

tracker = ByteTrack(track_activation_threshold=0.8,
                    minimum_matching_threshold=0.8,
                    lost_track_buffer=30,
                    frame_rate=30)

video_feed = cv2.VideoCapture("test_rgb.mp4")

status, frame = video_feed.read()

while status:
    results: List[Results] = yolo(frame,
                                  show=False,
                                  verbose=False,
                                  imgsz=[736, 1280])
    result: Results = results[0]

    inference_detections: Detections = Detections.from_ultralytics(result)
    detections = tracker.update_with_detections(inference_detections)

    for (xyxy, mask, conf, class_id, tracker_id, data) in detections:
        print("xyxy:", xyxy)

    status, frame = video_feed.read()
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @dbestPacksol 👋🏻 Thanks for your interest in `supervision`. Could you install `ultralytics==8.1` and check if the code works or fails?

**Comment by dbestPacksol** [comment]
@SkalskiP Even when running on ultralytics==8.1 it still has the same failure

**Comment by kavanagh-cw** [comment]
Same problem here and I have tried both version.

**Comment by SkalskiP** [comment]
Hi, @onuralpszr. 👋🏻 Is there any chance you could take a look? If you are busy, no problem we can try to debug ourselves.

**Comment by onuralpszr** [comment]
@SkalskiP I took it, let me debug quickly and open PR based on that (If needed)

**Comment by SkalskiP** [comment]
@onuralpszr thanks a lot for the help 🙏🏻

**Comment by onuralpszr** [comment]
I send PR and for test please use this collab for quick test based on code, I had to some values because using different video in my case

https://colab.research.google.com/drive/1S57W1lRKKZ4Jnh1HUp1Abu5T3dIPzHZU?usp=sharing

**Comment by SkalskiP** [comment]
@onuralpszr, thanks a lot for the fast response! 🔥 

@dbestPacksol and @kavanagh-cw, could you check if the fix solves your problems? All you need to do is install `supervision` like this:

```python
pip install git+https://github.com/roboflow/supervision.git@fix/yolo-obb
```

**Comment by LinasKo** [comment]
Hey @onuralpszr,

I left some comments on the PR. I think it reintroduces a past issue if left as is.

**Comment by onuralpszr** [comment]
> Hey @onuralpszr,
> 
> I left some comments on the PR. I think it reintroduces a past issue if left as is.

Where ?

**Comment by LinasKo** [comment]
https://github.com/roboflow/supervision/pull/1222/files/c529511dcc7a33a62a56c77d2ed2b379e9f9f787#diff-d620bf6569b39b0318ed01ac9fbd645b801ee1e237c188e3c50a7e3480f2ee25R243

**Comment by onuralpszr** [comment]
> https://github.com/roboflow/supervision/pull/1222/files/c529511dcc7a33a62a56c77d2ed2b379e9f9f787#diff-d620bf6569b39b0318ed01ac9fbd645b801ee1e237c188e3c50a7e3480f2ee25R243

I think you forgot the press "comment" because I don't see it.

**Comment by LinasKo** [comment]
Ah yes. I thought pressing "Comment" was enough, but it needs a review submission. Apologies!

**Comment by dbestPacksol** [comment]
@SkalskiP Sorry for the late response, I have installed the new version and it works for me now.

**Comment by onuralpszr** [comment]
@dbestPacksol  thank you for response. I am glad it fixed for you.

**Comment by LinasKo** [comment]
Hi @kavanagh-cw 👋 

If you're having issues, I recommend you try `pip install supervision==0.21.0.rc5`.

Let me know if that doesn't help!
