### ISSUE TITLE
Speed Estimator for Vehicle Tracking

### ISSUE THREAD

**Issue by bthoma48** [roboflow/supervision#1247]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Where and how do I specifically add the configurations for both "vehicles.mp4" and "vehicles-result.mp4" in the ultralytics script, "ultralytics_example.py"?

Does it simply replace the code-line: "--source_video_path" and "--target_video-path"?

Can you specifically send the 146-line ultralytics script to incorporate "vehicles.mp4" and "vehicles-result.mp4"?

**Comment by LinasKo** [comment]
Hi @bthoma48 :wave: 

I see you've already opened a discussion. Let's chat there :wink: 

https://github.com/roboflow/supervision/discussions/1248
