### ISSUE TITLE
line counter is not working anymore?

### ISSUE THREAD

**Issue by uzumakinaruto19** [roboflow/supervision#126]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

this is my code I wanted to add multiple lines and count the objects, but the line counter is not working anymore with the latest supervision.

```python
import os
import torch
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="0"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
import numpy as np
import json
from ultralytics import YOLO
import supervision as sv
# from supervision.tools.line_counter import LineCounter
# from supervision.geometry.dataclasses import Point


# LINE_START = Point(50, 1500)
# LINE_END = Point(3790, 1500)

# line_counter = LineCounter(start=LINE_START, end=LINE_END)

model = YOLO('yolov8n.pt')

def main_func(input_data,frame):

    global model

    if 'ignore' in input_data:
        return "ignore"
    else:

        input_data = json.loads(input_data)

        results= model.track(frame, imgsz=640, classes=0,tracker="bytetrack.yaml")[0]
        detections = sv.Detections.from_yolov8(results)

        if results.boxes.id is not None:
            detections.tracker_id = results.boxes.id.cpu().numpy().astype(int)
            detections.conf = results.boxes.conf.cpu().numpy().astype(float)
            detections.xyxy = results.boxes.xyxy.cpu().numpy().astype(int)
            
            # print(detections.tracker_id)
            # print(detections.conf)
            # print(detections.xyxy)
        else:
            detections.tracker_id = np.array([])
            detections.conf = np.array([])
            detections.xyxy = np.array([])
 
        new_box=detections.xyxy
        new_box = new_box.astype("int").tolist()
        new_ids = detections.tracker_id.astype("int").tolist()
        new_confs = detections.conf.astype("float").tolist()    



        print("count",count)

        output = {
                  'frame_index':input_data['frame_index'],
                  'time_stamp':input_data['time_stamp'],
                  'detections':new_box,
                  'demo_run':input_data['demo_run'],
                  'ids':new_ids,
                  'confs':new_confs
                  }
        
        print(output)
        return output
```

except for the polygon , how to have multiple lines and update the counts?

**Comment by SkalskiP** [comment]
Hi, @uzumakinaruto19 👋🏻! Could you be a bit more specific? What do you mean by "but the line counter is not working anymore with the latest supervision"?

**Comment by sceddd** [comment]
@uzumakinaruto19 did you use trigger() yet? I don't see it in your code.

**Comment by uzumakinaruto19** [comment]
> Hi, @uzumakinaruto19 👋🏻! Could you be a bit more specific? What do you mean by "but the line counter is not working anymore with the latest supervision"?

hey sorry I'll provide the updated code

`import os
import torch
import numpy as np
import json
from ultralytics import YOLO
import supervision as sv
from supervision.detection.line_counter import LineZone, LineZoneAnnotator
from collections import defaultdict
import cv2

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = YOLO('yolov8n.pt')
LINE_1_START = sv.Point(85, 297)  
LINE_1_END = sv.Point(640, 462)  
LINE_2_START = sv.Point(689, 279)  
LINE_2_END = sv.Point(663, 229)  
LINE_3_START = sv.Point(219, 197)  
LINE_3_END = sv.Point(330, 190)

def main_func(video_path):
    global model

    line_counter_1 = sv.LineZone(start=LINE_1_START, end=LINE_1_END)
    line_counter_2 = sv.LineZone(start=LINE_2_START, end=LINE_2_END)
    line_counter_3 = sv.LineZone(start=LINE_3_START, end=LINE_3_END)
    line_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.5)
    box_annotator = sv.BoxAnnotator(thickness=2, text_thickness=1, text_scale=0.5)

    video = cv2.VideoCapture(video_path)
    frame_index = 0

    while video.isOpened():
        ret, frame = video.read()
        if not ret:
            break

        input_data = {
            'frame_index': frame_index,
            'time_stamp': 0,  # You can replace 0 with an appropriate timestamp
            'demo_run': False
        }

        output = process_frame(input_data, frame, line_counter_1, line_counter_2, line_counter_3, line_annotator, box_annotator)
        display_frame(output, frame)

        print("Line 1 Out Count: ", line_counter_1.out_count)
        print("Line 2 Out Count: ", line_counter_2.out_count)
        print("Line 3 Out Count: ", line_counter_3.out_count)
        print("-------------------------------------")

        if cv2.waitKey(1) & 0xFF == ord('q'):  # Press 'q' to exit
            break

        frame_index += 1

    video.release()
    cv2.destroyAllWindows()





def process_frame(input_data, frame, line_counter_1, line_counter_2, line_counter_3, line_annotator, box_annotator):

    
    results = model.track(frame, imgsz=640, classes=0, tracker="bytetrack.yaml")[0]
    detections = sv.Detections.from_yolov8(results)

    if results.boxes.id is not None:
        detections.tracker_id = results.boxes.id.cpu().numpy().astype(int)
        detections.conf = results.boxes.conf.cpu().numpy().astype(float)
        detections.xyxy = results.boxes.xyxy.cpu().numpy().astype(int)
    else:
        detections.tracker_id = np.array([])
        detections.conf = np.array([])
        detections.xyxy = np.array([])

    frame = box_annotator.annotate(scene=frame, detections=detections, labels=[str(id) for id in detections.tracker_id])
    line_counter_1.trigger(detections=detections)
    line_counter_2.trigger(detections=detections)
    line_counter_3.trigger(detections=detections)

    line_annotator.annotate(frame=frame, line_counter=line_counter_1)
    line_annotator.annotate(frame=frame, line_counter=line_counter_2)
    line_annotator.annotate(frame=frame, line_counter=line_counter_3)

    new_ids = detections.tracker_id.astype("int").tolist()
    new_box = detections.xyxy.astype("int").tolist()
    new_confs = detections.conf.astype("float").tolist()

    output = {
        'frame_index': input_data['frame_index'],
        'time_stamp': input_data['time_stamp'],
        'detections': new_box,
        'demo_run': input_data['demo_run'],
        'ids': new_ids,
        'confs': new_confs,
        'line_1_out_count': line_counter_1.out_count,
        'line_2_out_count': line_counter_2.out_count,
        'line_3_out_count': line_counter_3.out_count
    }

    print(output)
    return output




def display_frame(output, frame):
    cv2.imshow("Output", frame)
    cv2.waitKey(1)


# Provide the path to your video file
video_path = './test.mp4'
main_func(video_path)
`


ever after using the trigger and the object crosses the line its not getting counted?

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19 did you use trigger() yet? I don't see it in your code.

i have used , I provided the wrong code, my bad

**Comment by uzumakinaruto19** [comment]
well the detection is working fine aswell as the tracking

below shown is the output

`
WARNING ⚠️ imgsz=[740] must be multiple of max stride 32, updating to [768]
{'frame_index': 10, 'time_stamp': 0, 'detections': [[275, 147, 317, 271], [330, 162, 347, 221]], 'demo_run': False, 'ids': [1, 2], 'confs': [0.8728579878807068, 0.731636643409729], 'line_1_out_count': 0}
Line 1 Out Count:  0
`

I'm having issues while counting alone ids what I'm guessing

I have drawn the line but even after the object crossing it is not getting counted
![Screenshot from 2023-06-09 21-21-08](https://github.com/roboflow/supervision/assets/99479748/aa3e8f44-418a-4f05-80ae-041735e7bd0d)


![()

**Comment by SkalskiP** [comment]
With the current implementation, for the object to be counted, all four corners of the bounding box must cross the line.

**Comment by uzumakinaruto19** [comment]
So u are suggesting extending the line more (I guess I tried that aswell, it is not getting counted at all, anyway I'll try once more), should a go with a polygon(idk whether that will make any sense with that)

**Comment by uzumakinaruto19** [comment]
> With the current implementation, for the object to be counted, all four corners of the bounding box must cross the line.

Instead of that can't u use the centroid of the Box, more accurate maybe?

**Comment by SkalskiP** [comment]
Using single point with models like YOLOv8 is not reliable solution unfortunately.

**Comment by sceddd** [comment]
Maybe you put the line in the wrong position. The logic is that if all the bounding boxes cross the line, the count will increase. In your case, you should either turn the camera to a higher position or detect the shoes and count if those shoes cross the line or you could take a look at #107 with the @maddust issue by choose the point at bottom center of the bounding box for counting.

**Comment by uzumakinaruto19** [comment]
> 

This actually worked in my case with @maddust suggestion, thanks a ton !!

when using the polygon zone I'm getting this error, it's running for some seconds and throwing this error

 ```
result[:, [0, 2]] = result[:, [0, 2]].clip(0, width)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```
And is it possible to how much time some object spends in that zone alone ?

Thanks in advance

**Comment by SkalskiP** [comment]
> This actually worked in my case

Awesome! :tada: 

> when using the polygon zone I'm getting this error, it's running for some seconds and throwing this error

Could you create a separate bug report where we could address that issue? Please make sure to provide the following:
1. Version of `supervision` you use.
2. Minimal reproducible example.
3. Full stack trace. 
4. If you can video/image you use for tests.

> And is it possible to get how much time an object spends in that zone alone?

It is but you would need a tracker for that. We also do not have ready-to-use tools you could use, but we can guide you and help you build your code.

**Comment by uzumakinaruto19** [comment]
>Could you create a separate bug report where we could address that issue? 

I have raised issue #131 for that 

> It is but you would need a tracker for that. We also do not have ready-to-use tools you could use, but we can guide you and help you build your code.

I'm already having a tracker(ByteTrack) with yolov8 

Really appreciate this repo and the help you guys giving!!

**Comment by SkalskiP** [comment]
@uzumakinaruto19 As for your in-zone time counter. Here is a sketch of the python logic that you will need.

```python
# dictionary that stores information when given detection starts to be in the zone
in_zone_state: Dict[int, int] = {}

# loop over frames
for frame_index, frame in ...:

    # trigger your zone with detections
    in_zone = polygon_zone.trigger(detections)
    # filter detections to get only those in the zone
    detections_in_zone = detections[in_zone]
    
    # tracker ids that were in the zone in the current frame
    curr_in_zone = set(detections_in_zone.tracker_id)
    # tracker ids that were in the zone in the previous frame
    prev_in_zone = set(in_zone_state.keys())
    # tracker ids that just entered the zone
    new = curr_in_zone.difference(prev_in_zone)
    # tracker ids that just left the zone
    old = prev_in_zone.difference(curr_in_zone)

    # adding new tracker ids to in_zone_state with current frame_index
    for tracker_id in new:
        in_zone_state[tracker_id] = frame_index

    # removing old tracker ids from in_zone_state and calculating how long it was in zone
    for tracker_id in old:
        in_zone_frame_count = frame_index - in_zone_state[tracker_id]
        in_zone_time = in_zone_frame_count * 1 / VIDEO_FPS
        del in_zone_state[tracker_id]
```

**Comment by uzumakinaruto19** [comment]
Hey thanks a lot for the help, but while running it the in_zone_time is always coming empty, I couldn't find what I was doing wrong

````import cv2
from ultralytics import YOLO
import supervision as sv
import numpy as np
from typing import Dict

polygon = np.array([
    [364, 833],
    [1382, 809],
    [993, 280],
    [698, 281],
])
video_info = sv.VideoInfo.from_video_path('./test.mp4')
zone = sv.PolygonZone(polygon=polygon, frame_resolution_wh=video_info.resolution_wh)
VIDEO_FPS = 30
def main():
    global model

    zone_annotator = sv.PolygonZoneAnnotator(zone=zone, color=sv.Color.white(), thickness=1, text_thickness=1, text_scale=0.5)

    box_annotator = sv.BoxAnnotator(
        thickness=2,
        text_thickness=1,
        text_scale=0.5
    )
    frame_index = 0
    input_data = {
        'frame_index': frame_index,
        'time_stamp': 0,  # You can replace 0 with an appropriate timestamp
        'demo_run': False
    }

    model = YOLO("yolov8n.pt")

    for result in model.track(source='./test.mp4', classes=0, imgsz=480, show=True, stream=True,
                              agnostic_nms=True):

        frame = result.orig_img
        detections = sv.Detections.from_yolov8(result)

        if result.boxes.id is not None:
            detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
        else:
            detections.tracker_id = np.array([])

        # detections = detections[(detections.class_id != 60) & (detections.class_id != 0)]

        labels = [str(id) for id in detections.tracker_id]

        frame = box_annotator.annotate(
            scene=frame,
            detections=detections,
            labels=labels
        )
        in_zone_state: Dict[int, int] = {}

        in_zone_time = {}

        try:
            in_zone = zone.trigger(detections=detections)

            detections_in_zone = detections[in_zone]

            curr_in_zone = set(detections_in_zone.tracker_id)
            prev_in_zone = set(in_zone_state.keys())

            new = curr_in_zone.difference(prev_in_zone)

            old = prev_in_zone.difference(curr_in_zone)


            in_zone_time_list = []

            for tracker_id in new:
                in_zone_state[tracker_id] = frame_index
                print(in_zone_state)

            for tracker_id in old:
                in_zone_frame_count = frame_index - in_zone_state[tracker_id]
                print(in_zone_frame_count)
                in_zone_time[tracker_id] = in_zone_frame_count * 1 / VIDEO_FPS
                print(in_zone_time)
                del in_zone_state[tracker_id]
        
        except:
            catch = True
            print(detections.xyxy, "error in xyxy")
            print(detections.xyxy.shape, "error in shape")

        frame = zone_annotator.annotate(scene=frame)

        new_ids = detections.tracker_id.astype("int").tolist()
        new_box = detections.xyxy.astype("int").tolist()

        output = {
            'frame_index': frame_index,
            'time_stamp': input_data['time_stamp'],
            'detections': new_box,
            'demo_run': input_data['demo_run'],
            'ids': new_ids,
            'in_zone_time': in_zone_time
        }
        # print(output)

        cv2.imshow("yolov8", frame)
        frame_index += 1

        if (cv2.waitKey(30) == 27):
            break

if __name__ == '__main__':
    main()
```

**Comment by sceddd** [comment]
@uzumakinaruto19 In this case, I recommend overriding the linezone class. You'll need to add in, and out dicts to store the value you want to take. Take a look at #87 for my issue, for taking the frame index, use VideoInfo to take fps info for taking the sec. more info in #116.

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19 In this case, I recommend overriding the linezone class. You'll need to add in, and out dicts to store the value you want to take. Take a look at #87 for my issue, for taking the frame index, use VideoInfo to take fps info for taking the sec. more info in #116.

Done!! Thanks

**Comment by uzumakinaruto19** [comment]
Hey, hope everyone is doing good, is there a way I can reset the counters say after 20 mins?  i tried  the below code but not really working

```
def reset_counters():
    global line_counter_values, in_zone_time, frame_index, model, start_time
    print("Resetting counters...")
    model = YOLO("yolov8n.pt")
    in_zone_time = {}
    frame_index = 0
    start_time = time.time()  # Reset the start time
    return {
        "line_counter_1": {"in": 0, "out": 0},
        "line_counter_2": {"in": 0, "out": 0},
        "line_counter_3": {"in": 0, "out": 0}
    }, {}, 0



def main(input_data, frame, line_counter_1, line_counter_2, line_counter_3, zone):
    global model, frame_index, in_zone_state, in_zone_time, start_time, reset_interval
    
    line_annotator = sv.LineZoneAnnotator(thickness=2, text_thickness=1, text_scale=0.5)
    zone_annotator = sv.PolygonZoneAnnotator(zone=zone, color=sv.Color.white(), thickness=1, text_thickness=1, text_scale=0.5)

    # Get the current time
    current_time = time.time()

    # Calculate the elapsed time in seconds
    elapsed_time = current_time - start_time
    print(elapsed_time)

    # Check if the reset interval has passed
    if elapsed_time >= reset_interval:
        #print("Resetting counters...")
        reset_counters()
        print("Resetting counters...")
        # Reset the tracking IDs by setting persist=False
        persist = False
        result = model.track(frame, classes=0, imgsz=480, agnostic_nms=True, tracker="bytetrack.yaml", persist=persist)
        #print("Resetting counters...")


        # Reset the start time for the next interval
        start_time = current_time
    else:
        # Keep the tracking IDs by setting persist=True (default)       
        
        persist = True
        print("Keeping counters...")
        

        result = model.track(frame, classes=0, imgsz=480, agnostic_nms=True ,tracker="bytetrack.yaml", persist=persist)
    result = result[0]
    
 
    detections = sv.Detections.from_yolov8(result)

```
Thanks in advance!!!

**Comment by SkalskiP** [comment]
Hi @uzumakinaruto19 👋🏻 ! If you want to reset line counter counts, all you need to do is:

```python
# line counter
line_zone = sv.LineZone(...)

# line counter reset
counter.tracker_state = {}
counter.in_count = 0
counter.out_count = 0
```
