### ISSUE TITLE
Trigger when detection lost

### ISSUE THREAD

**Issue by wong-kene** [roboflow/supervision#1269]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

I use supervision for visitor counting inside specific area.
The whole system was running well except for one area only (let's call it area X).
The problem is the distance between camera and area X is too far, So that the person is so smaill. Engine still can detect the people but sometimes detection is lost for several second although the person is not move. and suddenly it be detected again

My question is.
Is any trigger when the people/object is : 
1. lost from detection
2. move out from area

if both trigger are exist, i will make a different treatment like this :
1. if object lost from detection, i will not decrease the total of people
2. if the person move out from are, i will descrease the total of people

Or any solution to cover my problem?

thanks...

**Comment by SkalskiP** [comment]
Hi @wong-kene 👋🏻 At present, there is no distinction between the situation when an object crosses the zone boundaries and simply disappears. We plan to add `cross_in` and `cross_our` counts for the polygon zone.

**Comment by wong-kene** [comment]
thanks for your response @SkalskiP 
i have tried to use Dataset for 'small people' over internet. but nothing matched with requirement. 
are you or anyone have recommendation dataset for 'small people'?

**Comment by SkalskiP** [comment]
@wong-kene, I guess the dataset is not the issue; the people are simply too small for the model to detect. As mentioned, you could detect them by increasing the model input resolution, but then your model would become slower.

**Comment by LinasKo** [comment]
Hi @wong-kene 👋 

The primary solution here is to increase the quality of small object detection.
For that reason, I'll close this tracker feature request.

---

However, I'd still like to help.

Here's some more info about small object detection with `InferenceSlicer`: https://supervision.roboflow.com/0.21.0/how_to/detect_small_objects/

If that runs too slow, there's a hybrid solution you can try:
1. Crop an image in the frame with [crop_image](https://supervision.roboflow.com/0.21.0/utils/image/)
2. Run a separate model just on that area.

While the tracker IDs won't be compatible, you'll still know whether someone entered / left the problematic zone.

Let me know if that solves your issue!
