### ISSUE TITLE
Is DetectionDataset intended behavior to store all images?

### ISSUE THREAD

**Issue by David-rn** [roboflow/supervision#1270]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi! :wave: 

I found that supervision was using >40GB of RAM in my system when using `DectectionDataset` to save a relatively large dataset as_yolo. I realized that the `DectectionDataset` uses a [dictionary to map](https://github.com/roboflow/supervision/blob/7f78f93407a13a9f73ef547af85dbda29f857b08/supervision/dataset/core.py#L62) the image name to the image, which is stored in memory. 

I wanted to ask if this is the expected behavior since it could lead to take all the available RAM when dealing with some datasets. 
If it is not, maybe it could store a reference path to the original image that is only opened when exporting the dataset.

As an example of this behavior I used this skeleton script:
```python
for image_name in list_images:
    image = cv2.imread(join(images_path, image_name))
    detection = get_detection_from_file(gt_file_path)

    images[image_name] = image
    annotations[image_name] = detection

dataset = sv.DetectionDataset(
        classes=classes,
        images=images,
        annotations=annotations,
    )
dataset.as_yolo(annotations_directory_path=output_gt_path, images_directory_path=output_images_path)
```

**Comment by SkalskiP** [comment]
@LinasKo and @David-rn, I'm closing this issue and marking it as duplicate.

**Comment by David-rn** [comment]
Perfect! I didn't find that issue, thanks @LinasKo for the clarification. If you need anything, glad to help!

**Comment by SkalskiP** [comment]
For now, we will work with @LinasKo, as we know, to design the proper API. Once we will create the first dataset loader (probably for YOLO format), you can pick the next one (COCO or PASCAL).
