### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR: roboflow.github.io/supervision

### ISSUE THREAD

**Issue by kenomo** [roboflow/supervision#128]
### Search before asking

- [x] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

ERR_SSL_PROTOCOL_ERROR during opening roboflow.github.io/supervision

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
I'm looking now, and I don't see any errors. Could you provide any more details? 

![Screenshot 2023-06-09 at 13 28 18](https://github.com/roboflow/supervision/assets/26109316/09e3ad7e-aba0-4072-98c9-0fd16bc81ddd)

**Comment by kenomo** [comment]
Now sophos web protection alerts with "Access was denied due to the detection of the Mal/HTMLGen-A threat on the website." https://www.sophos.com/de-de/threat-center/threat-analyses/viruses-and-spyware/Mal~HTMLGen-A

![image](https://github.com/roboflow/supervision/assets/30553042/fe271f13-ea54-430c-a949-259f6f3155e5)

But Chrome also alerts SSL issues

![image](https://github.com/roboflow/supervision/assets/30553042/4d8525bf-1f59-4cb2-b965-094876b7f33b)

**Comment by SkalskiP** [comment]
What are your OS and browser?

**Comment by kenomo** [comment]
Sry, just a sophos web protection issue.

**Comment by SkalskiP** [comment]
@kenomo no worries ;)
