### ISSUE TITLE
DotAnnotator support radius proportional to object size

### ISSUE THREAD

**Issue by zhaoruibing** [roboflow/supervision#1283]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Currently DotAnnotator takes a fixed radius. It would be great if the radii can be relative to the object sizes.

### Use case

For rebar counting, the size of the rebar in the photo depends on the proximity of the camera, meaning the dots' radii should vary for each image.

For airplanes or insects, objects closer to the camera will appear larger, while those further away will look smaller within the same image. Therefore, the radii should adjust for each object.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @zhaoruibing 👋 

If someone wishes to see the size, they can use `sv.CircleAnnotator`, with custom thickness.
![image](https://github.com/roboflow/supervision/assets/6500785/cac9c81a-4039-48eb-aad7-a096ab9a0043)

I'm closing this for now but adding it to a list of less urgent ideas to be investigated in the future.
