### ISSUE TITLE
Modified Triangle Annotator

### ISSUE THREAD

**Issue by dsaha21** [roboflow/supervision#1285]
### Search before asking

- [x] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Upgradation of the triangle above head annotators more prominently

![Modified__traiangle_2](https://github.com/roboflow/supervision/assets/73748916/cb7e9cb7-a540-4f43-bb67-1e38d89a5175)
![Modified_Triangle_1](https://github.com/roboflow/supervision/assets/73748916/c6bcf82f-1edc-4c0b-94a8-bc560095b438)

### Use case

The original Triangle Annotator is attached below :-
![Original](https://github.com/roboflow/supervision/assets/73748916/e4c1f08d-7bba-49c0-93a4-4d69596d5200)

The modified one might help us to view for a more clear detection.

### Additional

My request is to please analyse the modified annotator. If its pleasing and if possible please accept for a PR. Thank You

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @dsaha21 👋 

I like how this looks! Feel free to open a PR for it. Please also include a Colab we can test it in.

Let's make sure the old behaviour is the default, (e.g. if `outline_thickness=0` then old triangles are shown).

Are the any [other annotators](https://supervision.roboflow.com/annotators/) we should add this to?

**Comment by LinasKo** [comment]
This looks great. Let's make a PR :)

One change I'd like to request is to check if this can also be added to sv.DotAnnotator, as it can be just as hard to see: [Colab](https://colab.research.google.com/drive/1NvVs28MnSb-_W-zkFa6-FXiY-0G4nx7k#scrollTo=VjdCk7cMuhh2).

**Comment by onuralpszr** [comment]
Complete via https://github.com/roboflow/supervision/pull/1294
