### ISSUE TITLE
How to get detections from index ver 0.3.0 

### ISSUE THREAD

**Issue by litaldavar** [roboflow/supervision#129]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

I'm using supervision version 0.3.0 it works great.
I want to iterate on all detections of each frame and get the xyxy and tracker id.
I wanted to use __iter__() and __getitem__() but I couldn't get it to work
Please write an example for that 
Thank you

**Comment by SkalskiP** [comment]
Hi @litaldavar 👋🏻 ! Small question: Do you need to use version `0.3.0`?

**Comment by litaldavar** [comment]
I think so because when I tried the current version it crushed and supervision issues said to use 0.3.0
I managed to make a loop on all detections it is working, and I need to count how many I got. It works but not pretty 
thanks

**Comment by SkalskiP** [comment]
You need to know how many detections you have? If so, you can do `len(detections)`.
