### ISSUE TITLE
Help in gathering commonly used supervision functions.

### ISSUE THREAD

**Issue by LinasKo** [roboflow/supervision#1293]
We will be releasing a supervision cheatsheet soon - something of a similar style as https://github.com/a-anjos/python-opencv/blob/master/cv2cheatsheet.pdf

First, we need to gather a list of code snippets in a Colab. We'll then go over it and copy out a subset of the functions into the PDF.

Partial submissions are fine - every little bit helps!
---

The sections in the Colab I anticipate are as follows:

1. `# Supervision Basics` - pip install supervision and inference, load an imagerun the model (`"yolov8s-640"`) and `from_inference`, visualize result. This section also has `Detections.empty`, `is_empty` and `Detections.merge`.

More importantly this should have frequently searched behaviour such as selecting detections with one class. I'll add this myself later.

Let's include `with_nmm` and `with_nms` too. 

> https://supervision.roboflow.com/develop/#hello
> https://supervision.roboflow.com/develop/how_to/detect_and_annotate/
> https://supervision.roboflow.com/develop/detection/core/

2. `# supervision assets` - an example of loading from https://supervision.roboflow.com/assets/

3. `# Loading model results` - examples of installing dependencies and running every model mentioned [here](https://supervision.roboflow.com/latest/detection/core/), showing every `from_X` method at work.

> https://supervision.roboflow.com/develop/detection/core/

3. `Annotators` - Create and run every annotator on a detections object, show the result.

> https://supervision.roboflow.com/develop/detection/annotators/

4. `# KeyPoints` - similar sections of the Basics, from_X, annotators

> https://supervision.roboflow.com/latest/keypoint/core/
> https://supervision.roboflow.com/latest/keypoint/annotators/

---

If you start creating a Colab, please post a link on this issue.

After you're done, please set it to "anyone can edit" - it will be useful in the next few days.

**Comment by LinasKo** [comment]
@Bhavay-2001, does this sound interesting? I believe it's a good opportunity to learn more about the library, and we need this urgently, expecting to release the cheatsheet by the end of this week.

**Comment by Bhavay-2001** [comment]
Hi @LinasKo, I have created a [colab](https://colab.research.google.com/drive/1YNPqO5aE5iAu9Q9KtmP2NyzYdgTb43m8?usp=sharing) notebook. I have started with some examples and will add more in the coming days. Please have a look and let me know about that changes.

**Comment by Bhavay-2001** [comment]
Hi @LinasKo, please review the colab notebook once again and share your feedback as I have updated with few more examples.
There are some examples like `with_nmm` and `with_nms` and some others which don't have a coding snippet available. Soo what should we do regarding those examples?

**Comment by LinasKo** [comment]
Hi @Bhavay-2001,

Again, this looks awesome and very helpful. If there's no examples you can either try to make it working based on the docs, look for [blog posts](https://blog.roboflow.com/) or [here](https://blog.roboflow.com/detect-small-objects/).

If a quick search yields no results, let me know - I can probably find a [Colab](https://colab.research.google.com/drive/1v0MPlG1tQctX5-koh0l6h1NcB6eWJ_YY).

Alternatively, if there's another section you'd prefer to work on, feel free to skip it.
Anything you don't include, I will fill in myself, when I make the sheet.

Lastly, one update: there a [new model](https://huggingface.co/microsoft/Florence-2-large) out, so instead of launching it tomorrow, we'll do it by next Friday. So it's less urgent than I originally said.

**Comment by Bhavay-2001** [comment]
Hi @LinasKo, I have updated the colab notebook again and raised a bug in the `CropAnnotator` class. Please review it and let me know what else can be added or this is it? 
Thanks

**Comment by Bhavay-2001** [comment]
Hi @LinasKo, just let me know if anything else needs to be done in the notebook and also pls view the bug too that i have raised. I can try to fix it as well.
Thanks

**Comment by LinasKo** [comment]
I'll have a look either today or tomorrow. Thanks again for your work!

**Comment by Bhavay-2001** [comment]
Hi @LinasKo, any updates on this? 
Thanks

**Comment by LinasKo** [comment]
Hi @Bhavay-2001,

Thank you for your work! At this point I consider it complete - I'll be using the functions you extracted to create the cheat sheet for us.

Would you like to be mentioned in the launch post on LinkedIn? If so, do you have a LinkedIn profile, or should I use your GitHub?

**Comment by Bhavay-2001** [comment]
Sure @LinasKo, I'll just drop my Linkedin right away. [here](https://www.linkedin.com/in/bhavay2001?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app)

**Comment by LinasKo** [comment]
Thanks! I'll make sure to refer to your contribution 😉
