### ISSUE TITLE
Require `opencv-python-headless` by default

### ISSUE THREAD

**Issue by fabito** [roboflow/supervision#130]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Installing supervision indirectly installs `opencv-python` package as a dependency.
It would be nice to make it optional or replace `opencv-python` by `opencv-python-headless`.

### Use case

For production inference environments we usually don't want/need to install/depend on GUI packages and libraries.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @fabito 👋🏻! That will be awesome for example if you want to limit the size of your Docker image. I definitely think it is a good move.

The next question is how do we implement this? We could add `headless` into `extras_require` but this way it will install `opencv-python` first and then `opencv-python-headless`. Do you have better ideas?

```python
install_requires=[
    'numpy>=1.20.0',
    'opencv-python',  # this will install by default
    'matplotlib',
    'pyyaml'
],
extras_require={
    'dev': [
        'flake8',
        'black==22.3.0',
        'isort',
        'twine',
        'pytest',
        'wheel',
        'notebook',
        'mkdocs-material',
        'mkdocstrings[python]'
    ],
    'headless': ['opencv-python-headless'],  # extra for environments without GUI
},
```

**Comment by fabito** [comment]
A new extra sounds like a good route.
I am not sure if we can exclude a package when a specific extra is specified though. I did a [quick research and apparently that is not possible ](https://github.com/pypa/pip/issues/8686) ? Needs further investigation.

**Comment by SkalskiP** [comment]
I guess the alternative is to build two separate pip packages, `supervision` and `supervision-headless`, using two different `setup.py` files.

**Comment by sanmai-NL** [comment]
Why use a `setup.py` at all in 2023? I'd expect you to use a [PEP 621 `pyproject.toml`](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#declaring-project-metadata). For this issue, using optional dependencies.

**Comment by SkalskiP** [comment]
Hi, @sanmai-NL 👋🏻! It looks like I'm already lagging behind the latest Python dev trends. We started working on a migration from `setup.py` to `project.toml`, but got distracted by other features. I'll make sure to revive this idea.

**Comment by SkalskiP** [comment]
@onuralpszr would be awesome if you could propose some solution that would work 🔥
