### ISSUE TITLE
overlay_image() function

### ISSUE THREAD

**Issue by Bhavay-2001** [roboflow/supervision#1301]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

The `overlay_image` function used in the `CropAnnotator` class [here](https://github.com/roboflow/supervision/blob/f00dcede1a2e0e3bca0f403ed4a0d23e16cde937/supervision/annotators/core.py#L2105) has different arguments as compared to the parameters in the `overlay_image` function defined over [here](https://github.com/roboflow/supervision/blob/f00dcede1a2e0e3bca0f403ed4a0d23e16cde937/supervision/utils/image.py#L293)

### Minimal Reproducible Example

```python
import supervision as sv
from inference import get_model
import cv2

model = get_model(model_id="yolov8n-seg-640")
image = cv2.imread('/content/highway.jpg')
results = model.infer(image)[0]
detections = sv.Detections.from_inference(results)

crop_annotator = sv.CropAnnotator()
annotated_frame = crop_annotator.annotate(
    scene=image.copy(),
    detections=detections
)
cv2.imshow(annotated_frame)
``` 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Confirming the bug: https://colab.research.google.com/drive/1liqwH6p_rPbNrV2D1jPPe8pOmoA0DCME?usp=sharing

@Bhavay-2001, if you're still keen, feel free to open a PR with the fix!
