### ISSUE TITLE
Estimate Speed with Computer Vision

### ISSUE THREAD

**Issue by dearMOMO** [roboflow/supervision#1330]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

speed = distance / time * 3.6
Excuse me, what does 3.6 do here

**Comment by LinasKo** [comment]
I don't know the context, but:

That's an hour (3600 seconds) divided by 1000m - it's used to convert between `km/h` and `m/s`.

**Comment by dearMOMO** [comment]
Wow, thank you so much
