### ISSUE TITLE
text cannot be painted in valid area in `RichLabelAnnotator`

### ISSUE THREAD

**Issue by Ying-Kang** [roboflow/supervision#1346]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

here is my code:
```python
...
LABEL_ANNOTATOR = sv.RichLabelAnnotator(font_path="utils/resource/xxxfont.ttf", color=sv.Color.ROBOFLOW)
...
img = BOUNDING_BOX_ANNOTATOR.annotate(img, detections)
img = LABEL_ANNOTATOR.annotate(img, detections, labels=labels)
```
most cases, it works well
however, when the bbox with xmin=0, ymin=0, which is the edge case
painted text area can not be put in a visible area just like below
![image](https://github.com/user-attachments/assets/f383c3c4-0ce0-4b5a-98c4-43a98ee38f0c)

### Environment

- python3.9
- supervision 0.21
- ubuntu

### Minimal Reproducible Example

same as illurstrated in bug

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @Ying-Kang 👋 

This is expected behavior. By default, label boxes are meant to be shown **above** the top-left corner of the bounding box.

If that doesn't work for you, I suggest playing around with the `text_position`.

**Comment by Ying-Kang** [comment]
undestand...
I mean it can be more intelligient if you could offer more edge judgement instead of align with fixed behavior like 'top left'

**Comment by LinasKo** [comment]
Yeah, I've been thinking similarly myself. I'll add it to our backlog
