### ISSUE TITLE
color_lookup="INDEX",  TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by yeldarby** [roboflow/supervision#1368]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Using `color_lookup = "INDEX"` throws: `TypeError: '<' not supported between instances of 'NoneType' and 'int'`.

### Environment

- Supervision: 0.22.0
- Colab

### Minimal Reproducible Example

Colab: https://colab.research.google.com/drive/1SpxXrpDJKadaJLMNxx5ukXygl2JA9dxH#scrollTo=1tnbpMYBQAVF

```
box_annotator = sv.BoxAnnotator(
    color_lookup = "INDEX"
)
label_annotator = sv.LabelAnnotator()

annotated_image = box_annotator.annotate(image.copy(), detections=detections)
annotated_image = label_annotator.annotate(annotated_image, detections=detections)

sv.plot_image(image=annotated_image, size=(8, 8))
```

### Additional

[The docs](https://supervision.roboflow.com/latest/detection/annotators/) say this should be a string (`Type: str`, `Options are INDEX, CLASS, TRACK.`) but it's actually an enum. This works:

```
box_annotator = sv.BoxAnnotator(
    color_lookup = sv.annotators.utils.ColorLookup.INDEX
)
label_annotator = sv.LabelAnnotator()

annotated_image = box_annotator.annotate(image.copy(), detections=detections)
annotated_image = label_annotator.annotate(annotated_image, detections=detections)

sv.plot_image(image=annotated_image, size=(8, 8))
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @yeldarby 👋🏻 good point. It is interesting to see how wrong documentation can result in wrong usage.

**Comment by SkalskiP** [comment]
I updated the docstrings. You can take a look here: https://supervision.roboflow.com/develop/detection/annotators. It will become official along with the next release.
