### ISSUE TITLE
from_matplotlib: 'LinearSegmentedColormap' object has no attribute 'colors'

### ISSUE THREAD

**Issue by yeldarby** [roboflow/supervision#1369]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Some matplotlib color palettes fail with `'LinearSegmentedColormap' object has no attribute 'colors'`.

### Environment

- Supervision: 0.22.0
- Colab

### Minimal Reproducible Example

Colab: https://colab.research.google.com/drive/1t8n2nnGGHqbm6idj8FmI7HYFe78ZhYxa#scrollTo=aGRu4uWp6wrB

```
box_annotator = sv.BoxAnnotator(
    color = sv.ColorPalette.from_matplotlib("hsv", 10)
)
label_annotator = sv.LabelAnnotator()

annotated_image = box_annotator.annotate(image.copy(), detections=detections)
annotated_image = label_annotator.annotate(annotated_image, detections=detections)

sv.plot_image(image=annotated_image, size=(8, 8))
```

### Additional

A list of a bunch of matplotlib palettes that fail:

```
twilight
twilight_shifted
hsv
jet
turbo
rainbow
gist_rainbow
nipy_spectral
gist_ncar
ocean
gist_earth
terrain
gist_stern
gnuplot
gnuplot2
spring
summer
autumn
winter
cool
hot
copper
bone
greys_r
purples_r
blues_r
greens_r
oranges_r
reds_r
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @yeldarby 👋🏻 Thanks a lot for reporting this. I've already identified the issue, and I'm working on a fix.

**Comment by SkalskiP** [comment]
Fix is available on `develop`. You can test it here: https://colab.research.google.com/drive/1cRxvuuJe8jrQYt8kepwUGRcAU80T9N-y?usp=sharing
