### ISSUE TITLE
mAP for small, medium and large objects

### ISSUE THREAD

**Issue by Bhavay-2001** [roboflow/supervision#1376]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

I saw an issue online where the user demanded calculation of MeanAveragePrecision for small, medium and large objects for HBB and OBB detection models. I thought that maybe this will be a good idea to expand this in supervision library. 

We can discuss about this issue and maybe potential approach on how to achieve this. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @Bhavay-2001 👋🏻, We plan to add this feature. But for now, we need to decide on the API internally. Let me close this issue for now. I'll open the new one once we make the final design decisions.

**Comment by Bhavay-2001** [comment]
Alright @SkalskiP, pls let me know. Thanks
