### ISSUE TITLE
setting up dev environment fails in two places

### ISSUE THREAD

**Issue by sharukiln** [roboflow/supervision#1378]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

![Screenshot from 2024-07-18 05-06-08](https://github.com/user-attachments/assets/a82b3e2f-d413-47d2-b43b-d2859d53ef68)
![Screenshot from 2024-07-18 05-13-04](https://github.com/user-attachments/assets/954cc3eb-a86e-4e6c-838a-e9c55c247812)

### Environment

ubuntu 24.04
python 3.12.3

### Minimal Reproducible Example

`poetry install`
`poetry run pytest`

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
@sharukiln hello, first error could cause because of old poetry so make sure it is latest version, second error basically happen because of First one, it just opencv not installed. So first try update your poetry and re run installation.

**Comment by onuralpszr** [comment]
@sharukiln I talked little bit early, so I made a PR for fix the issue, sorry for the trouble
