### ISSUE TITLE
Error when running PR checks 

### ISSUE THREAD

**Issue by danigarciaoca** [roboflow/supervision#138]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi everyone! I've one question realted to PR and Test Workflow.

I've seen that, when commiting my PR (#135) I get an error in all checks related to Test Workflow due to problems in fetching the respository. Here are [the errors](https://github.com/roboflow/supervision/actions/runs/5265179974).

![245773658-ef3286fa-35ac-45f5-9e26-cd94df97c1a4](https://github.com/roboflow/supervision/assets/27818263/efda20d9-a347-4c3b-918d-7e01963422f6)

Does anyone have an idea about what can be happening? I've seen that some other users that have created and merged a PR haven't experienced this issue. Some examples of successful PRs:
- [Update `__init__.py` to include linezone](https://github.com/roboflow/supervision/pull/31), by @dceejay 
- [Add custom text for the in & out tags](https://github.com/roboflow/supervision/pull/44), by @iPoe 
- [Adding yolov8 masks to detections](https://github.com/roboflow/supervision/pull/101), by @hardikdava 

Thanks in advance!

**Comment by SkalskiP** [comment]
Hi @dankresio 👋🏻 ! It is most likely a problem with our GitHub Action. This only happens if you try to marge from the fork of Supervision. I will look into it. 👀

**Comment by dankresio** [comment]
Oh, thanks! I thought it was a problem with private repositories or my Github PAT.

Regarding this comment:
> This only happens if you try to marge from the fork of Supervision

Some other PRs (#101, #44) have been merged from the fork and there have been no problems with their checks. That was the point that was blowing my mind. Its weird...

**Comment by hardikdava** [comment]
@SkalskiP I think this problem rises when we use different branch from a fork respository i.e. other than `main` branch.

**Comment by SkalskiP** [comment]
@hardikdava that idea looks plausible. Let's keep our eyes on future PRs and try to confirm that.

**Comment by hardikdava** [comment]
@SkalskiP I noticed the following thing:

fork_repo/any_branch -> supervision/other than main branch :+1: 
fork_repo/any_branch -> supervision/main branch :-1:

**Comment by onuralpszr** [comment]
@SkalskiP  has been fix via #218 so we can close this too 🎉 🎉 🎉 🎉

**Comment by SkalskiP** [comment]
@onuralpszr closing!
