### ISSUE TITLE
[LabelAnnotator, RichLabelAnnotator, VertexLabelAnnotator] - allow `text_color` to be `Union[Color, ColorPalette]`

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#1384]
### Description

[`LabelAnnotator`](https://supervision.roboflow.com/develop/detection/annotators/#supervision.annotators.core.LabelAnnotator), [`RichLabelAnnotator`](https://supervision.roboflow.com/develop/detection/annotators/#supervision.annotators.core.RichLabelAnnotator), and [`VertexLabelAnnotator`](https://supervision.roboflow.com/develop/keypoint/annotators/#supervision.keypoint.annotators.EdgeAnnotator.annotate) currently allow defining the background color as `Union[Color, ColorPalette]`. When the background color is a single `Color`, all boxes are drawn with the same color. If the background color is a `ColorPalette`, the detection index, class_id, or tracker_id is mapped to the corresponding color from the palette. Unfortunately, this functionality is not currently available for `text_color`.

Update `LabelAnnotator`, `RichLabelAnnotator`, and `VertexLabelAnnotator` to enable defining `text_color` as `Union[Color, ColorPalette]` and implement the same mechanism as for the background color.

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by Bhavay-2001** [comment]
Hi @SkalskiP, you can assign this to me. I'll take a look over thr weekend.

**Comment by SkalskiP** [comment]
@Bhavay-2001 Done ✅

**Comment by SkalskiP** [comment]
The expected change was added to `LabelAnnotator` and `RichLabelAnnotator` via https://github.com/roboflow/supervision/pull/1387. @Bhavay-2001 would you be interested in adding this change to `VertexLabelAnnotator` as well?

**Comment by Bhavay-2001** [comment]
Sure

**Comment by SkalskiP** [comment]
@Bhavay-2001 thank you ;)
