### ISSUE TITLE
[TriangleAnnotator, DotAnnotator] - allow customization of the contour color

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#1403]
### Description

`TriangleAnnotator` and `DotAnnotator` allow rendering an outline around a triangle and a dot, respectively. This feature is activated by setting `outline_thickness` to a value greater than 0. However, there is no way to customize the outline color.

Add a new argument `outline_color` to both of these annotators. Set the type of `outline_color` as `Union[Color, ColorPalette]`. `outline_color` should integrate with `color_lookup` like other colors in supervision annotators.

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by SkalskiP** [comment]
@Bhavay-2001, maybe it would be better if you finish https://github.com/roboflow/supervision/issues/1384 first?

**Comment by Bhavay-2001** [comment]
Yeah definitely, only after that.

**Comment by Bhavay-2001** [comment]
Hi @SkalskiP, I have one doubt in this. You said to add `outline_color` parameter to both the annotators and what I understood is that this parameter will basically add the color to the outline of my `Dot` or `Triangle` right? 

If we take the `DotAnnotator` for instance, we use this [function](https://github.com/roboflow/supervision/blob/bb0e4ec059aec195039c13f43ab419a55d7a2325/supervision/annotators/core.py#L998). It doesn't have any parameter to change the color of the outline, so how we can add the parameter here?

**Comment by onuralpszr** [comment]
> Hi, I'd like to work on this issue if it's still available :))

Technically it is available so, you can go for it. task is yours :)
