### ISSUE TITLE
import/export dataset in COCO format

### ISSUE THREAD

**Issue by kobic8** [roboflow/supervision#141]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

I have noticed you have a method to load datasets only in PASCAL-VOC, are you planning to also support COCO formats?

### Use case

omport and export in COCO format

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @kobic8 👋🏻! We currently support both loading and saving in YOLO and PASCAL VOC formats. However, we plan to add COCO support soon. Maybe with the `0.11.0` release.

**Comment by SkalskiP** [comment]
Hi @kobic8 👋🏻! We just merged #150 PR and added the 🥥 COCO dataset import-export. It is not yet released but you can already use it if you install it from the source.
