### ISSUE TITLE
Recieving -> IndexError: arrays used as indices must be of integer (or boolean) type. When trying to annotate detections.

### ISSUE THREAD

**Issue by fernanh98** [roboflow/supervision#1417]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I have extracted masks from an image using SAM 2 model and then I am trying to annotate those masks using sv.detections and MaskAnnotator like this:

image_path = "car.jpg"
image_bgr = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
image_array = np.array(image_rgb)
box = np.array([1, 1, image_array.shape[1], image_array.shape[0]])

# SAM 2 prediction
mask_predictor.set_image(image_rgb)
masks, scores, logits = mask_predictor.predict(
    box=box,
    multimask_output=True
)

box_annotator = sv.BoxAnnotator(color=sv.Color.RED)
mask_annotator = sv.MaskAnnotator(color=sv.Color.RED)
detections = sv.Detections(
    xyxy=sv.mask_to_xyxy(masks=masks),
    mask=masks
)
detections.class_id = np.zeros(len(detections), dtype=int)
source_image = box_annotator.annotate(scene=image_bgr.copy(), detections=detections)
segmented_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)

In this code everything executes correctly until it reaches last line (segmented_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)) in which I receive this error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-135-0ff839f33faa>](https://localhost:8080/#) in <cell line: 10>()
      8 #detections = detections[detections.area == np.max(detections.area)]
      9 source_image = box_annotator.annotate(scene=image_bgr.copy(), detections=detections)
---> 10 segmented_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)
     11 sv.plot_images_grid(
     12     images=[source_image, segmented_image],

1 frames
[/usr/local/lib/python3.10/dist-packages/supervision/annotators/core.py](https://localhost:8080/#) in annotate(self, scene, detections, custom_color_lookup)
    358             )
    359             mask = detections.mask[detection_idx]
--> 360             colored_mask[mask] = color.as_bgr()
    361 
    362         cv2.addWeighted(

IndexError: arrays used as indices must be of integer (or boolean) type

### Environment

- Supervision: 0.22.0
- Python: 3.10.12
- Working on Google Colab

### Minimal Reproducible Example

image_path = "car.jpg"
image_bgr = cv2.imread(image_path)
image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
image_array = np.array(image_rgb)
box = np.array([1, 1, image_array.shape[1], image_array.shape[0]])

# SAM 2 prediction
mask_predictor.set_image(image_rgb)
masks, scores, logits = mask_predictor.predict(
    box=box,
    multimask_output=True
)

box_annotator = sv.BoxAnnotator(color=sv.Color.RED)
mask_annotator = sv.MaskAnnotator(color=sv.Color.RED)
detections = sv.Detections(
    xyxy=sv.mask_to_xyxy(masks=masks),
    mask=masks
)
detections.class_id = np.zeros(len(detections), dtype=int)
source_image = box_annotator.annotate(scene=image_bgr.copy(), detections=detections)
segmented_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by rolson24** [comment]
Hmm I think you need to make the masks have the datatype of bool. I have attached the code below


### SAM 2 prediction
```
mask_predictor.set_image(image_rgb)
masks, scores, logits = mask_predictor.predict(
box=box,
multimask_output=True
)

box_annotator = sv.BoxAnnotator(color=sv.Color.RED)
mask_annotator = sv.MaskAnnotator(color=sv.Color.RED)
detections = sv.Detections(
xyxy=sv.mask_to_xyxy(masks=masks),
# change this line to make dtype of masks bool
mask=masks.astype(bool)
)
detections.class_id = np.zeros(len(detections), dtype=int)
source_image = box_annotator.annotate(scene=image_bgr.copy(), detections=detections)
segmented_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)
```

**Comment by fernanh98** [comment]
Yep, that worked. Thank you @rolson24 :)
