### ISSUE TITLE
Add method for REDETR model 

### ISSUE THREAD

**Issue by Bhavay-2001** [roboflow/supervision#1418]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Add a method to take predictions from REDETR model and convert them to detections just like for other models for instance - yolo5, ultralytics etc.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @Bhavay-2001,

Unfortunately we're rather preoccupied at the moment, and would prefer to not assign more than 1 issue per contributor. We know we wouldn't be able to review anyway!

I shall close this for now.

**Comment by Bhavay-2001** [comment]
Hi @LinasKo, actually I have worked on this on the inference repository and I think I can add this method. It won't be a problem much.

**Comment by LinasKo** [comment]
Feel free to open a PR! We'll have a look when we have time.
