### ISSUE TITLE
How to set tracker_buffer

### ISSUE THREAD

**Issue by litaldavar** [roboflow/supervision#142]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hello, I'm using native tracking with yolov8 and supervision 0.3.0 
I want to set the tracker_buffer to a higher number so my objects won't get a new tracker Id each time they disappear around a corner 
how can I do that with supervision?
Thank you

**Comment by SkalskiP** [comment]
Hi @litaldavar 👋🏻! I'm not on the Ultralytics team, but I did some research, and it looks like you can steer that by changing the value of `track_buffer` in [`bytetrack.yaml`](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/tracker/cfg/bytetrack.yaml). I'm closing the issue, as it is not directly related to supervision. :)
