### ISSUE TITLE
VOC XML Starts at (1,1) not (0,0)

### ISSUE THREAD

**Issue by Jacobsolawetz** [roboflow/supervision#144]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

<img width="756" alt="image" src="https://github.com/roboflow/supervision/assets/8428198/8f6e01ae-815c-4235-9a8b-ddc8eebf4a40">

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hardikdava** [comment]
@mayankagarwals Can you first try this? This is been there since long time.

**Comment by SkalskiP** [comment]
It also looks to be super easy :)

**Comment by mayankagarwals** [comment]
Yeah, I've fixed this and tested locally: https://github.com/roboflow/supervision/pull/235 

<img width="553" alt="image" src="https://github.com/roboflow/supervision/assets/39498938/65f3b5f7-4287-43e1-aca9-f3005c3673a7">
<img width="429" alt="image" src="https://github.com/roboflow/supervision/assets/39498938/24090b5f-1994-41a4-aa34-04f2c87986e2">

Everything looks fine.

**Comment by mayankagarwals** [comment]
We can probably do one round of testing on colab if we don't have sanity tests around loading dataset. Would be great if we already have a roboflow project with sample voc data :) @SkalskiP

**Comment by SkalskiP** [comment]
We need to cake care of that for both loading and saving. And I'm not sure, but probably for polygons as well.

**Comment by mayankagarwals** [comment]
Got it. 
Can you help me understand why we are preferring bounding box given by the polygon instead of the bounding box detected? Not sure if I'm missing something obvious

**Comment by SkalskiP** [comment]
> Doesn't look like polygons are loaded or saved for Pascal VOC

Polygons are saved but not loaded. We have a separate task for that. @kirilllzaitsev will probably do it.

> Can you help me understand why we are preferring bounding box given by the polygon instead of the bounding box detected?

I'm not sure what you mean. Could you elaborate?

**Comment by mayankagarwals** [comment]
> Polygons are saved but not loaded. We have a separate task for that. @kirilllzaitsev will probably do it.

Can you point me to where they are being saved? 
https://github.com/roboflow/supervision/blob/7067741310e4ce582436ebd76d415c2d357cec3f/supervision/dataset/formats/pascal_voc.py#L141
New to the ecosystem so apologies if this is obvious :) 

> I'm not sure what you mean. Could you elaborate?

In this line
https://github.com/roboflow/supervision/blob/8662671e6b4a1793602e4981ba8e164a2e5d50e3/supervision/dataset/formats/pascal_voc.py#L107C1-L107C1
When saving pascal voc, the pseudo-code looks like 
```python
if polygon present: 
  load xyxy from polygon of detection
else: 
  load xyxy from bounding box of detection
```

I want to know why that is the case.

**Comment by hardikdava** [comment]
@mayankagarwals once the dataset is loaded using any format then `sv.DetectionDatasets.as_()` method can save the loaded dataset into `pascal voc, yolo or coco`.

**Comment by mayankagarwals** [comment]
> @mayankagarwals once the dataset is loaded using any format then sv.DetectionDatasets.as_() method can save the loaded dataset into pascal voc, yolo or coco.

My point is sv isn't saving polygons when saving pascal_voc dataset. Please check https://github.com/roboflow/supervision/blob/7067741310e4ce582436ebd76d415c2d357cec3f/supervision/dataset/formats/pascal_voc.py#L141

**Comment by SkalskiP** [comment]
> Can you point me to where they are being saved?

@mayankagarwals we save in `object_to_pascal_voc` and load in `load_pascal_voc_annotations`
