### ISSUE TITLE
Research Paper 

### ISSUE THREAD

**Issue by olawalejuwonm** [roboflow/supervision#1468]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

This is a great library. I've used it for a research project, but I'm curious to know if there is any paper on it that i can cite?

**Comment by LinasKo** [comment]
Hi @olawalejuwonm 👋 ,

Glad to hear it's useful! If you go to the [Repository page](https://github.com/roboflow/supervision), on the right hand side you'll see a "Cite this repository" button. That should provide a copyable snippet for you.

<img width="365" alt="Screenshot 2024-08-20 at 4 31 19 PM" src="https://github.com/user-attachments/assets/346a4087-84fe-4958-a9e9-f513976da736">

Thanks again for the kind words!
