### ISSUE TITLE
plotting single bounding prompt with SAM2 inference 

### ISSUE THREAD

**Issue by nadeem414** [roboflow/supervision#1492]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

boxes = np.array([[5.94719971e+02, 1.98900009e+02, 6.28320007e+02, 2.64900024e+02]])

box_annotator = sv.BoxAnnotator(color_lookup=sv.ColorLookup.INDEX)
mask_annotator = sv.MaskAnnotator(color_lookup=sv.ColorLookup.INDEX)

detections = sv.Detections(
    xyxy=sv.mask_to_xyxy(masks=masks),
    mask=masks.astype(bool)
)

source_image = box_annotator.annotate(scene=image_bgr.copy(), detections=detections)
segmented_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)

sv.plot_images_grid(
    images=[source_image, segmented_image],
    grid_size=(1, 2),
    titles=['source image', 'segmented image']
)

### Environment

how-to-segment-images-with-sam-2.ipynb on google collab notebook

### Minimal Reproducible Example

pass single bbox to sv.mask_to_xyxy function in sam2 notebook. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by venkatram-dev** [comment]
Created PR for notebook code fix

https://github.com/roboflow/notebooks/pull/305

**Comment by LinasKo** [comment]
Hi @nadeem414,

Thank you for reporting the issue. The solution by @venkatram-dev is correct - you can solve this by changing

```python
masks = np.squeeze(masks)
```

into

```python
if boxes.shape[0] != 1:
    masks = np.squeeze(masks)
```

We'll update the notebook. Feel free to let me know if there are any more issues!

**Comment by LinasKo** [comment]
Closing as solved. Thanks @venkatram-dev!
