### ISSUE TITLE
Problem to use supervision with docker image's nvcr.io/nvidia/pytorch

### ISSUE THREAD

**Issue by MattBlue92** [roboflow/supervision#1522]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

In [1]: import supervision as sv
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 import supervision as sv

File /usr/local/lib/python3.10/dist-packages/supervision/__init__.py:9
      6 except importlib_metadata.PackageNotFoundError:
      7     __version__ = "development"
----> 9 from supervision.annotators.core import (
     10     BackgroundOverlayAnnotator,
     11     BlurAnnotator,
     12     BoundingBoxAnnotator,
     13     BoxAnnotator,
     14     BoxCornerAnnotator,
     15     CircleAnnotator,
     16     ColorAnnotator,
     17     CropAnnotator,
     18     DotAnnotator,
     19     EllipseAnnotator,
     20     HaloAnnotator,
     21     HeatMapAnnotator,
     22     IconAnnotator,
     23     LabelAnnotator,
     24     MaskAnnotator,
     25     OrientedBoxAnnotator,
     26     PercentageBarAnnotator,
     27     PixelateAnnotator,
     28     PolygonAnnotator,
     29     RichLabelAnnotator,
     30     RoundBoxAnnotator,
     31     TraceAnnotator,
     32     TriangleAnnotator,
     33 )
     34 from supervision.annotators.utils import ColorLookup
     35 from supervision.classification.core import Classifications

File /usr/local/lib/python3.10/dist-packages/supervision/annotators/core.py:5
      2 from math import sqrt
      3 from typing import List, Optional, Tuple, Union
----> 5 import cv2
      6 import numpy as np
      7 import numpy.typing as npt

File /usr/local/lib/python3.10/dist-packages/cv2/__init__.py:181
    176             if DEBUG: print("Extra Python code for", submodule, "is loaded")
    178     if DEBUG: print('OpenCV loader: DONE')
--> 181 bootstrap()

File /usr/local/lib/python3.10/dist-packages/cv2/__init__.py:175, in bootstrap()
    172 if DEBUG: print('OpenCV loader: binary extension... OK')
    174 for submodule in __collect_extra_submodules(DEBUG):
--> 175     if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
    176         if DEBUG: print("Extra Python code for", submodule, "is loaded")
    178 if DEBUG: print('OpenCV loader: DONE')

File /usr/local/lib/python3.10/dist-packages/cv2/__init__.py:28, in __load_extra_py_code_for_module(base, name, enable_debug_print)
     26 native_module = sys.modules.pop(module_name, None)
     27 try:
---> 28     py_module = importlib.import_module(module_name)
     29 except ImportError as err:
     30     if enable_debug_print:

File /usr/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File /usr/local/lib/python3.10/dist-packages/cv2/typing/__init__.py:171
    169 ExtractArgsCallback = _typing.Callable[[_typing.Sequence[GTypeInfo]], _typing.Sequence[GRunArg]]
    170 ExtractMetaCallback = _typing.Callable[[_typing.Sequence[GTypeInfo]], _typing.Sequence[GMetaArg]]
--> 171 LayerId = cv2.dnn.DictValue
    172 IndexParams = _typing.Dict[str, _typing.Union[bool, int, float, str]]
    173 SearchParams = _typing.Dict[str, _typing.Union[bool, int, float, str]]

AttributeError: module 'cv2.dnn' has no attribute 'DictValue'

### Environment

-Python 3.10.12
-supervision 0.23.0
-ubuntu 24.04.1 LTS
-opencv 4.7.0
-opencv-contrib-python 4.10.0.84
-opencv-python 4.10.0.84
-opencv-python-headless 4.10.0.84
- NVIDIA TITAN RTX
- Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz

### Minimal Reproducible Example

docker pull nvcr.io/nvidia/pytorch:24.08-py3

docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:24.08-py3

pip install supervision

ipython

import supervision as sv

### Additional

Hi there,

I'm going to be mad to solve this bug, there are problem to install flash-attention, so the docker images nvcr.io/nvidia/pytorch is only way to get flash-attention but supervision don't work.

I have some data that cannot be upload in colab, the only way is use local machine and for research goals I need to use florence-2 that working only with flash-attention.
Any suggestion?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by LinasKo** [comment]
Hi @MattBlue92 👋 

It's unlikely we can help fix it, but here's something you can try:
Can you run `pip install opencv-python` after installing supervision?

There's a very tiny chance this is a clash between `opencv-python-headless` and `opencv-python`, as one you install last overwrites a couple of folders, causing odd errors.

Also, @onuralpszr, I can't quite remember - were you the one who mentioned flash attention recently? Something relating to the new `from_` connector?

**Comment by onuralpszr** [comment]
Hello @LinasKo  and @MattBlue92  I decided to install and show you via this; https://asciinema.org/a/676564
I hope that will explain everything :) all works and you can see in terminal record, I just ran container and start import and show all

**Comment by MattBlue92** [comment]
Hi @LinasKo  

Open-cv in nvcr.io/nvidia/pytorch:24.08-py3 is allready installed when the container is created. I'll try to install opencv and then install supervision first and opencv after.

For now I solved installing conda inside  the container and manually I installed the packages that I need and it worked.

**Comment by onuralpszr** [comment]
> Hi @LinasKo
> 
> Open-cv in nvcr.io/nvidia/pytorch:24.08-py3 is allready installed when the container is created. I'll try to install opencv and then install supervision first and opencv after.
> 
> For now I solved installing conda inside the container and manually I installed the packages that I need and it worked.

You don't need to install conda could you please check the link I posted

**Comment by MattBlue92** [comment]
@onuralpszr wow you solved it. 
Thank you I much appreciated!
