### ISSUE TITLE
Dataset merge

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#155]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

- Ability to merge multiple datasets.
- API should be similar to `sv.Detections.merge`
- **NOTE:** Notice that different datasets can have different `classes`. If `classes` are different make sure to create new classes list and remap `class_id` of annotations to match new `classes`

### Use case

```python
>>> import supervision as sv

>>> ds_1 = sv.DetectionDataset.from_yolo(...)
>>> ds_1.classes
['dog', 'person']
>>> len(ds_1)
100

>>> ds_2 = sv.DetectionDataset.from_coco(...)
>>> ds_2.classes
['car']
>>> len(ds_2)
100

>>> ds_3 = sv.DetectionDataset.from_pascal_voc(...)
>>> ds_2.classes
['apple', 'orange']
>>> len(ds_3)
100

>>> ds = sv.DetectionDataset.merge(dataset_list=[ds_1, ds_2, ds_3])
>>> ds.classes
['apple', 'car', 'dog', 'orange', 'person']
>>> len(ds)
300
```

### Additional

It would be awesome if we could make it work for both `sv.DetectionDataset` and `sv.ClassificationDataset`.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@hardikdava would you like to implement that feature?

**Comment by hardikdava** [comment]
@SkalskiP I can try to implement it.

**Comment by SkalskiP** [comment]
@hardikdava 👋🏻 

> What should be done in case of same `image name` in `dataset-1` and `dataset-2`?

I'd think we throw an exception and provide some explanation.

> What should be done in case of conflict of class names as mentioned in the description? Should `dataset-1` will be given priority when remap the classes?

I think we should do something predictable. Sort classes alphabetically.

> Can we create a new naming system when we save the dataset? i.e. based on `timestamp` or other keys.

Not sure if I understand. But in any case, we should keep it simple.

**Comment by hardikdava** [comment]
HI @SkalskiP, you can use this code for unittest or manual testing. Please change dataset paths based on your dataset.

Feature branch: https://github.com/hardikdava/supervision/tree/dataset_merge

I have tested with 2 dataset but it should work fine regardless of number of dataset.

Check: dataset/core.py and dataset/utils.py
PS: Minor refactoring and docstrings might needed.
```
import supervision as sv
import cv2

ds1_dir = "data/doggg.v1i.coco/valid"
ds1 = sv.DetectionDataset.from_coco(
    images_directory_path=f"{ds1_dir}/",
    annotations_path=f"{ds1_dir}/_annotations.coco.json",
    force_masks=False
   )

ds2_dir = "data/doggg.v1i.coco/valid"
ds2 = sv.DetectionDataset.from_yolo(
    images_directory_path=f"{ds2_dir}/images",
    annotations_directory_path=f"{ds2_dir}/labels",
    data_yaml_path=f"{ds2_dir}/data.yaml",
    force_masks=False
   )

merged_dataset = sv.DetectionDataset.merge([ds1, ds2])
box_annotator = sv.BoxAnnotator()

# Initial Testing
for image_name, image, detections in merged_dataset:
    labels = [f"{merged_dataset.classes[class_id]}" for _, _, _, class_id, _ in detections]
    render_image = box_annotator.annotate(scene=image, detections=detections, labels=labels)
    cv2.imshow("Result", render_image)
    cv2.waitKey(1)


tmp_dir = "tmp/valid"
# Save merged dataset
merged_dataset.as_yolo(images_directory_path=f"{tmp_dir}/images",
                       annotations_directory_path=f"{tmp_dir}/labels",
                       data_yaml_path=f"{tmp_dir}/data.yaml")


# Load merged dataset
merged_dataset= sv.DetectionDataset.from_yolo(images_directory_path=f"{tmp_dir}/images",
                       annotations_directory_path=f"{tmp_dir}/labels",
                       data_yaml_path=f"{tmp_dir}/data.yaml")


box_annotator = sv.BoxAnnotator()
# Visualized merged dataset again
for image_name, image, detections in merged_dataset:

    labels = [f"{merged_dataset.classes[class_id]}" for _, _, _, class_id, _ in detections]
    render_image = box_annotator.annotate(scene=image, detections=detections, labels=labels)
    cv2.imshow("Result", render_image)
    cv2.waitKey(0)

```

**Comment by SkalskiP** [comment]
@hardikdava could you submit PR?

**Comment by SkalskiP** [comment]
@hardikdava I’m not sure I can do it myself.

**Comment by SkalskiP** [comment]
Changes merged. Closing the issue.

**Comment by cls-talha** [comment]
> HI @SkalskiP, you can use this code for unittest or manual testing. Please change dataset paths based on your dataset.
> 
> Feature branch: https://github.com/hardikdava/supervision/tree/dataset_merge
> 
> I have tested with 2 dataset but it should work fine regardless of number of dataset.
> 
> Check: dataset/core.py and dataset/utils.py PS: Minor refactoring and docstrings might needed.
> 
> ```
> import supervision as sv
> import cv2
> 
> ds1_dir = "data/doggg.v1i.coco/valid"
> ds1 = sv.DetectionDataset.from_coco(
>     images_directory_path=f"{ds1_dir}/",
>     annotations_path=f"{ds1_dir}/_annotations.coco.json",
>     force_masks=False
>    )
> 
> ds2_dir = "data/doggg.v1i.coco/valid"
> ds2 = sv.DetectionDataset.from_yolo(
>     images_directory_path=f"{ds2_dir}/images",
>     annotations_directory_path=f"{ds2_dir}/labels",
>     data_yaml_path=f"{ds2_dir}/data.yaml",
>     force_masks=False
>    )
> 
> merged_dataset = sv.DetectionDataset.merge([ds1, ds2])
> box_annotator = sv.BoxAnnotator()
> 
> # Initial Testing
> for image_name, image, detections in merged_dataset:
>     labels = [f"{merged_dataset.classes[class_id]}" for _, _, _, class_id, _ in detections]
>     render_image = box_annotator.annotate(scene=image, detections=detections, labels=labels)
>     cv2.imshow("Result", render_image)
>     cv2.waitKey(1)
> 
> 
> tmp_dir = "tmp/valid"
> # Save merged dataset
> merged_dataset.as_yolo(images_directory_path=f"{tmp_dir}/images",
>                        annotations_directory_path=f"{tmp_dir}/labels",
>                        data_yaml_path=f"{tmp_dir}/data.yaml")
> 
> 
> # Load merged dataset
> merged_dataset= sv.DetectionDataset.from_yolo(images_directory_path=f"{tmp_dir}/images",
>                        annotations_directory_path=f"{tmp_dir}/labels",
>                        data_yaml_path=f"{tmp_dir}/data.yaml")
> 
> 
> box_annotator = sv.BoxAnnotator()
> # Visualized merged dataset again
> for image_name, image, detections in merged_dataset:
> 
>     labels = [f"{merged_dataset.classes[class_id]}" for _, _, _, class_id, _ in detections]
>     render_image = box_annotator.annotate(scene=image, detections=detections, labels=labels)
>     cv2.imshow("Result", render_image)
>     cv2.waitKey(0)
> ```
Hi, I'm getting this error

Traceback (most recent call last):
  File "merge.py", line 21, in <module>
    merged_dataset = sv.DetectionDataset.merge([ds1, ds2])
  File "/home/talha/miniconda3/envs/yolov8-seg/lib/python3.7/site-packages/supervision/dataset/core.py", line 488, in merge
    source_classes=dataset.classes, target_classes=merged_classes
  File "/home/talha/miniconda3/envs/yolov8-seg/lib/python3.7/site-packages/supervision/dataset/utils.py", line 66, in build_class_index_mapping
    f"Class {class_name} not found in target classes. "
ValueError: Class Benign not found in target classes. source_classes must be a subset of target_classes.

**Comment by onuralpszr** [comment]
> > HI @SkalskiP, you can use this code for unittest or manual testing. Please change dataset paths based on your dataset.
> > Feature branch: https://github.com/hardikdava/supervision/tree/dataset_merge
> > I have tested with 2 dataset but it should work fine regardless of number of dataset.
> > Check: dataset/core.py and dataset/utils.py PS: Minor refactoring and docstrings might needed.
> > ```
> > import supervision as sv
> > import cv2
> > 
> > ds1_dir = "data/doggg.v1i.coco/valid"
> > ds1 = sv.DetectionDataset.from_coco(
> >     images_directory_path=f"{ds1_dir}/",
> >     annotations_path=f"{ds1_dir}/_annotations.coco.json",
> >     force_masks=False
> >    )
> > 
> > ds2_dir = "data/doggg.v1i.coco/valid"
> > ds2 = sv.DetectionDataset.from_yolo(
> >     images_directory_path=f"{ds2_dir}/images",
> >     annotations_directory_path=f"{ds2_dir}/labels",
> >     data_yaml_path=f"{ds2_dir}/data.yaml",
> >     force_masks=False
> >    )
> > 
> > merged_dataset = sv.DetectionDataset.merge([ds1, ds2])
> > box_annotator = sv.BoxAnnotator()
> > 
> > # Initial Testing
> > for image_name, image, detections in merged_dataset:
> >     labels = [f"{merged_dataset.classes[class_id]}" for _, _, _, class_id, _ in detections]
> >     render_image = box_annotator.annotate(scene=image, detections=detections, labels=labels)
> >     cv2.imshow("Result", render_image)
> >     cv2.waitKey(1)
> > 
> > 
> > tmp_dir = "tmp/valid"
> > # Save merged dataset
> > merged_dataset.as_yolo(images_directory_path=f"{tmp_dir}/images",
> >                        annotations_directory_path=f"{tmp_dir}/labels",
> >                        data_yaml_path=f"{tmp_dir}/data.yaml")
> > 
> > 
> > # Load merged dataset
> > merged_dataset= sv.DetectionDataset.from_yolo(images_directory_path=f"{tmp_dir}/images",
> >                        annotations_directory_path=f"{tmp_dir}/labels",
> >                        data_yaml_path=f"{tmp_dir}/data.yaml")
> > 
> > 
> > box_annotator = sv.BoxAnnotator()
> > # Visualized merged dataset again
> > for image_name, image, detections in merged_dataset:
> > 
> >     labels = [f"{merged_dataset.classes[class_id]}" for _, _, _, class_id, _ in detections]
> >     render_image = box_annotator.annotate(scene=image, detections=detections, labels=labels)
> >     cv2.imshow("Result", render_image)
> >     cv2.waitKey(0)
> > ```
> 
> Hi, I'm getting this error
> 
> Traceback (most recent call last): File "merge.py", line 21, in merged_dataset = sv.DetectionDataset.merge([ds1, ds2]) File "/home/talha/miniconda3/envs/yolov8-seg/lib/python3.7/site-packages/supervision/dataset/core.py", line 488, in merge source_classes=dataset.classes, target_classes=merged_classes File "/home/talha/miniconda3/envs/yolov8-seg/lib/python3.7/site-packages/supervision/dataset/utils.py", line 66, in build_class_index_mapping f"Class {class_name} not found in target classes. " ValueError: Class Benign not found in target classes. source_classes must be a subset of target_classes.

Could you please open issue instead of typing here please also please use proper markdown formatter for codes and colors to make us easier to read.
