### ISSUE TITLE
DetectionDataset class names loading error

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#156]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

`DetectionDataset.from_yolo` method is having an issue for loading class names from `yaml file`. It is showing an empty list even though the names are present in `data.yaml` file.

Solution:

- Use `pyyaml` (already as dependency) for fetching information from `data.yaml` instead of reading as `txt` file 

### Environment

- Supervision source code
- Ubuntu

### Minimal Reproducible Example

Please put dataset before running test code.

```
import supervision as sv
import cv2

ds = sv.DetectionDataset.from_yolo(
    images_directory_path="data/coco128/valid/images",
    annotations_directory_path="data/coco128/valid/labels",
    data_yaml_path="data/coco128/data.yaml",
    force_masks=False
   )

print(ds.classes)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@hardikdava Wow, that is weird. Until now, I didn't experience any problems loading names from `data.yaml`. However, feel free to use `pyyaml` to load names. At first, we tried not to add `pyyaml` as a dependency. But as we have it already feel free to refactor the code.

**Comment by hardikdava** [comment]
@SkalskiP There is an another bug I noticed. `data.yaml` file does not contain `train, valid, test` directory path. Is it intended? `yolo dataset` does contain directory information.
