### ISSUE TITLE
Connect Oriented Bounding Box to Metrics

### ISSUE THREAD

**Issue by LinasKo** [roboflow/supervision#1562]
# Connect Oriented Bounding Box to Metrics

> [!TIP]
> [Hacktoberfest](https://hacktoberfest.com/) is calling! Whether it's your first PR or your 50th, you’re helping shape the future of open source. Help us build the most reliable and user-friendly computer vision library out there! 🌱

---

Several new features were recently added to supervision:
* Mean Average Precision (mAP)
* F1 Score
* IoU calculation for Oriented Bounding Boxes

Intersection Over Union (IoU) is the starting point when computing these metrics. It determines which detections are considered true positives. However, [take a look](https://github.com/roboflow/supervision/blob/d6aa72c0f2b158b838145a81ed5995db6a1e9015/supervision/metrics/mean_average_precision.py#L176)! The Oriented Box IoU is not supported yet! Help us add support by using `oriented_box_iou_batch`.

Helpful links:
* [Contribution guide](https://supervision.roboflow.com/develop/contributing/#how-to-contribute-changes)
* Metrics:
  * mAP metric: [docs](https://supervision.roboflow.com/develop/metrics/mean_average_precision/), [code](https://github.com/roboflow/supervision/blob/d6aa72c0f2b158b838145a81ed5995db6a1e9015/supervision/metrics/mean_average_precision.py#L25)
  * F1 Score: [docs](https://supervision.roboflow.com/develop/metrics/f1_score/), [code](https://github.com/roboflow/supervision/blob/d6aa72c0f2b158b838145a81ed5995db6a1e9015/supervision/metrics/f1_score.py#L25)
* Oriented box IoU calculation function: [docs](https://supervision.roboflow.com/develop/detection/utils/#supervision.detection.utils.oriented_box_iou_batch), [code](https://github.com/roboflow/supervision/blob/d6aa72c0f2b158b838145a81ed5995db6a1e9015/supervision/detection/utils.py#L143)
* [Supervision Cheatsheet](https://roboflow.github.io/cheatsheet-supervision/)
* [Colab Starter Template](https://colab.research.google.com/drive/1rin7WrS-UvVIe-_Gfxmu-yVslGphOq89#scrollTo=pjmCrNre2g58)
* [Prior metrics test Colab](https://colab.research.google.com/drive/1qSMDDpImc9arTgQv-qvxlTA87KRRegYN)

**Comment by LinasKo** [comment]
Hi @patel-zeel 👋 

I'm moving the IoU integration into metrics here. I believe we spoke about it briefly. Have you done substantial work on it already? If not, I will open it to the community.

**Comment by LinasKo** [comment]
> [!NOTE]
> If you would like to make a contribution, please check that no one else is assigned already. Then leave a comment such as "Hi, I would like to work on this issue". We're happy to answer any questions about the task even if you choose not to contribute.
> 
> Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. You may use the [Starter Template](https://colab.research.google.com/drive/1rin7WrS-UvVIe-_Gfxmu-yVslGphOq89). The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! :pray:

**Comment by Prasadayus** [comment]
Hi ,I would like to work on this issue. Please @LinasKo  assign me this issue

**Comment by patel-zeel** [comment]
Hi @LinasKo, feel free to open it for the community. I'd be happy to help other contributors if they face any issues while implementing :)

**Comment by onuralpszr** [comment]
@patel-zeel  task is yours, good luck have fun :)

**Comment by onuralpszr** [comment]
> Hi ,I would like to work on this issue. Please @LinasKo assign me this issue

@Prasadayus  hello task is yours, good luck have fun :)

**Comment by abhinav7289A** [comment]
Hi @LinasKo I am new to open source contribution. Please assign me this issue as I want to excel in this field

**Comment by LinasKo** [comment]
Hi @abhinav7289A,

This issue is already taken. I'll add many new ones next week - keep an eye on our issue board! 😉

**Comment by PrakharJain1509** [comment]
If an issue is already taken and I propose a better solution, then will you consider it or not? @LinasKo

**Comment by LinasKo** [comment]
Hi @PrakharJain1509 👋 
No. However, after the initial solution is refined and merged, I'm happy to review PRs that meaningfully improve upon it, even if the issue is closed. This would be eligible for Hacktoberfest as well.

**Comment by LinasKo** [comment]
Hi @Prasadayus 👋 

How's it going? Did you find any time to look at oriented boxes and metrics? 😉

**Comment by Prasadayus** [comment]
@LinasKo Sorry for the late reply, I was very busy this week. I cloned the project, reviewed the oriented box  and will make the changes by the end of this week

**Comment by LinasKo** [comment]
Thank you very much!

**Comment by PrakharJain1509** [comment]
@LinasKo I have opened a PR for this issue. Please review it and let me know if any changes are required.

**Comment by LinasKo** [comment]
Thank you very much @PrakharJain1509 ! I'll have a look and review it tomorrow

**Comment by LinasKo** [comment]
This is now open to a second contributor. Remember, creating either a well-encompassed unit test suite or a Colab showing the changes, is required for the PR to be accepted.

**Comment by LinasKo** [comment]
I've just realized that @Prasadayus is the original assigned contributor. Your PR will have priority over that of @PrakharJain1509.

@Prasadayus, how goes it? Do you think you'll have time to complete this PR? 😉

**Comment by AyuK03** [comment]
Hi, I would like to work on this issue

**Comment by LinasKo** [comment]
Adding @PrakharJain1509 as an assignee.
Of the two, the first successfully merged contribution will be chosen.

**Comment by rahulsamant37** [comment]
Can you review my changes, sir?

**Comment by LinasKo** [comment]
@rahulsamant37, I reviewed your changes in the PR and decided to close it in favor of #1593, as it aligns better with our current direction. Thanks for your effort and looking forward to your future contributions!

**Comment by LinasKo** [comment]
Completed via #1593. Thank you for your contributions, everyone! I hope you found the experience useful and fun!
