### ISSUE TITLE
Bug in git-committers-plugin-2, v2.4.0

### ISSUE THREAD

**Issue by LinasKo** [roboflow/supervision#1567]
At the moment, an error is observed when running the `mkdocs build` action from develop.

```
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line 121, in get_contributors_to_file
    'avatar': commit['author']['avatar_url'] if user['avatar_url'] is not None else ''
UnboundLocalError: local variable 'user' referenced before assignment
```

This is due to: https://github.com/ojacques/mkdocs-git-committers-plugin-2/issues/72

**Comment by LinasKo** [comment]
fyi @onuralpszr. We could drop the version, but let's wait till tomorrow's evening. Might be fixed by then.

**Comment by onuralpszr** [comment]
> fyi @onuralpszr. We could drop the version, but let's wait till tomorrow's evening. Might be fixed by then.

I will do what needs to done I will keep pr  ready in case we need

**Comment by onuralpszr** [comment]
Fix attempt PR : https://github.com/ojacques/mkdocs-git-committers-plugin-2/pull/73

**Comment by onuralpszr** [comment]
Fix PR has been merged. Closing the issue as complete
