### ISSUE TITLE
Metrics: Mean Average Recall (mAR)

### ISSUE THREAD

**Issue by LinasKo** [roboflow/supervision#1583]
# Metrics: Mean Average Recall (mAR)

> [!TIP]
> [Hacktoberfest](https://hacktoberfest.com/) is calling! Whether it's your first PR or your 50th, you’re helping shape the future of open source. Help us build the most reliable and user-friendly computer vision library out there! 🌱

We'd like to expand our suite of metrics with a new one - Mean Average Recall (mAR). This would involve creating it, its accompanying results class, and briefly testing it.

Note it is different from `mAP` in that it don't use the precision-recall curve, but recall-IoU. This affects `MeanAverageRecallResult`:

* The will not be `mAR@50`, `mAR@75`, etc - only the global main `mAR` value.
* Other frameworks threshold by max detections. I suggest we add this later if required.
* mAP currently implements a single averaging method, and F1 has 3 different ones (micro, macro, weighted). The choice between those is left to PR author - we can always add more later.
* The metric can report mAR values per-class. Do tell if that is difficult.
* I think we should have `1.0` as the default if no value are provided. `-1` is a consideration too, which should bring the same change to `mAP`.

Feel free to change the above if it feels better.

---

Helpful links:
* [Contribution guide](https://supervision.roboflow.com/develop/contributing/#how-to-contribute-changes)
* Metrics:
  * mAP metric: [docs](https://supervision.roboflow.com/develop/metrics/mean_average_precision/), [code](https://github.com/roboflow/supervision/blob/d6aa72c0f2b158b838145a81ed5995db6a1e9015/supervision/metrics/mean_average_precision.py#L25)
  * F1 Score: [docs](https://supervision.roboflow.com/develop/metrics/f1_score/), [code](https://github.com/roboflow/supervision/blob/d6aa72c0f2b158b838145a81ed5995db6a1e9015/supervision/metrics/f1_score.py#L25)
* [Supervision Cheatsheet](https://roboflow.github.io/cheatsheet-supervision/)
* [Colab Starter Template](https://colab.research.google.com/drive/1rin7WrS-UvVIe-_Gfxmu-yVslGphOq89#scrollTo=pjmCrNre2g58)
* [Prior metrics test Colab](https://colab.research.google.com/drive/1qSMDDpImc9arTgQv-qvxlTA87KRRegYN)

**Comment by LinasKo** [comment]
### Contribution guidelines
If you would like to make a contribution, please check that no one else is assigned already. Then leave a comment such as "Hi, I would like to work on this issue". We're happy to answer any questions about the task even if you choose not to contribute.

### Testing
Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. You may use the [Starter Template](https://colab.research.google.com/drive/1rin7WrS-UvVIe-_Gfxmu-yVslGphOq89). The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! :pray:

**Comment by LinasKo** [comment]
@onuralpszr, I've heard you already put some work towards this one. Shall I assign it to you?

**Comment by LinasKo** [comment]
Hey @onuralpszr, how's it going? Did you manage to get the mAR working in the end?

**Comment by onuralpszr** [comment]
> Hey @onuralpszr, how's it going? Did you manage to get the mAR working in the end?

After my work let me check and open pr

**Comment by LinasKo** [comment]
Implemented via https://github.com/roboflow/supervision/pull/1661
