### ISSUE TITLE
Add default color: PolygonZoneAnnotator, drawing functions

### ISSUE THREAD

**Issue by LinasKo** [roboflow/supervision#1587]
# Add default color: PolygonZoneAnnotator, drawing functions

> [!TIP]
> [Hacktoberfest](https://hacktoberfest.com/) is calling! Whether it's your first PR or your 50th, you’re helping shape the future of open source. Help us build the most reliable and user-friendly computer vision library out there! 🌱

In a [recent stream](https://www.youtube.com/live/RvVLqXdhdVQ), we noticed that some drawing functions and annotators require you to specify a color. Please give these a default color!

Of course, we wish to have `sv.Color.ROBOFLOW`.

Check [polygon annotator](https://supervision.roboflow.com/latest/detection/tools/polygon_zone/#supervision.detection.tools.polygon_zone.PolygonZone.trigger) and [draw functions](https://supervision.roboflow.com/latest/utils/draw/)!

---

Helpful links:
* [Contribution guide](https://supervision.roboflow.com/develop/contributing/#how-to-contribute-changes)
* [Supervision Cheatsheet](https://roboflow.github.io/cheatsheet-supervision/)
* [Colab Starter Template](https://colab.research.google.com/drive/1rin7WrS-UvVIe-_Gfxmu-yVslGphOq89#scrollTo=pjmCrNre2g58)
* [Prior metrics test Colab](https://colab.research.google.com/drive/1qSMDDpImc9arTgQv-qvxlTA87KRRegYN)

**Comment by DivyaVijay1234** [comment]
Hello, I would like to work on this issue. Please assign it to me.

**Comment by LinasKo** [comment]
@souhhmm, let's see how yours goes first, before taking another 😉 

Assigning it to you, @DivyaVijay1234!

**Comment by LinasKo** [comment]
The draw functions I foresee needing this are:
* draw_line
* draw_rectangle
* draw_filled_rectangle
* draw_polygon
* draw_filled_polygon

**Comment by DivyaVijay1234** [comment]
Thank you for assigning it to me. I will work on this issue.

**Comment by mostafahanafi** [comment]
My fault @LinasKo I didn't see that someone else was already assigned, I just saw an issue with no PR so got to work immediately

**Comment by LinasKo** [comment]
It happens sometimes, @mostafahanafi , don't worry about it.

However, we consider, review and iterate on the solution by the assigned contributor first. Only if that fails would we consider other ones.
