### ISSUE TITLE
Draw ellipse from bounding box

### ISSUE THREAD

**Issue by litaldavar** [roboflow/supervision#16]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

How do I draw ellipse from the bounding box from BoxAnnotator class with YOLOv8?

**Comment by SkalskiP** [comment]
Hi, @litaldavar 👋🏻! Thanks a lot for your interest in Supervision. We don't have that feature yet, unfortunately. We talk about ellipses like this: https://youtu.be/QCG8QMhga9k

**Comment by hardikdava** [comment]
@SkalskiP @litaldavar  Do we have any confirmation on final design about this issue?

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻 I would go for a design like the one you can see in the [video](https://www.youtube.com/watch?v=QCG8QMhga9k). Here is the [notebook](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-football-players.ipynb) I used to process the video.

**Comment by hardikdava** [comment]
Hey @SkalskiP I will take a look and try to include in our feature.

**Comment by hardikdava** [comment]
Preview:
User can play with start and end angles to customize more.
![Screenshot from 2023-07-07 19-12-46](https://github.com/roboflow/supervision/assets/39372750/8adf7aa3-4f45-4d96-b27b-4ff740300204)
