### ISSUE TITLE
Advanced BoxAnnotator🤩

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#168]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Current `sv.BoxAnnotator` is drawing boxes based on opencv rectangle. It can be improved for this kind of boxes. This looks pretty cool! 

- [ ] Advanced corner based bounding boxes
- [ ] Blur capacity (Direct object blur application)
- [ ] Boxes as mask

<img width="519" alt="Screenshot 2023-06-29 234656" src="https://github.com/roboflow/supervision/assets/39372750/d05d19d2-bac2-4797-b6f5-26c79239626e">
image source: depthai blogs

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@hardikdava Haha I see you want to do annotators :) How about we do this first? https://github.com/roboflow/supervision/issues/49

**Comment by hardikdava** [comment]
Preliminary result: 
![result](https://github.com/roboflow/supervision/assets/39372750/e55a8775-fa73-425d-b972-a3b15d55a202)

**Comment by SkalskiP** [comment]
Uuuu! Looks cool! 🔥 

I drove for a few hours yesterday and thought a lot about our annotators. And I think we can use that opportunity to redesign that feature and make it even more flexible. I think we should split annotators and make them composable. What do you think @hardikdava? 

Here is my idea:

```python
import numpy as np

from abc import ABC, abstractmethod

from typing import List


# base annotator

class BaseAnnotator(ABC):

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        pass


class ComposableAnnotator(ABC):

    def __init__(self, annotators: List[BaseAnnotator]):
        self.annotators = annotators

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        annotated_image = scene
        for annotator in self.annotators:
            annotated_image = annotator.annotate(scene=scene, detections=detections)
        return annotated_image

# single responsibility annotator

class BoxAnnotator(BaseAnnotator):

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        pass


class PolygonMaskAnnotator(BaseAnnotator):

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        pass


class LabelAnnotator(BaseAnnotator):

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        pass


class PillowLabelAnnotator(BaseAnnotator):

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        pass


class TrackAnnotator(BaseAnnotator):

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        pass


class BoxMaskAnnotator(BaseAnnotator):

    def annotate(self, scene: np.ndarray, detections: Detections) -> np.ndarray:
        pass

# high level annotators

class DetectionAnnotator(ComposableAnnotator):

    @classmethod
    def init(cls):
        annotators = [
            BoxAnnotator(),
            LabelAnnotator()
        ]
        return cls(annotators=annotators)


class SegmentationAnnotator(ComposableAnnotator):

    @classmethod
    def init(cls):
        annotators = [
            BoxAnnotator(),
            LabelAnnotator()
        ]
        return cls(annotators=annotators)


class TrackedDetectionAnnotator(ComposableAnnotator):

    @classmethod
    def init(cls):
        annotators = [
            BoxAnnotator(),
            LabelAnnotator(),
            TrackAnnotator()
        ]
        return cls(annotators=annotators)
```

**Comment by hardikdava** [comment]
Hey @SkalskiP 👋 , this is actually a nice idea of having computer vision task based annotators along with single responsible annotators. `pillow` annotators are actually a good idea but I found that `pillow` is much slower than `opencv` in terms of drawing operations from my experience. But having it is a good option. Since there are a lot possibilites of drawing for example it allows to use custom fonts which opencv doesn't allow. It will be a feature for future release. I would suggest to create an issue for this for now. We should first try to solve the existing issues.

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻 ! I know `pillow` is slower than `opencv`, but `opencv` only allows you to use `ascii` characters in the text. We already had a lot of voices from the community that they would like to add text in Arabic or Chinese. 

But I mostly mean to give people base annotators that they could freely combine.

**Comment by hardikdava** [comment]
Hi @SkalskiP 👋 , I am 💯 agree with you about adding `pillow`. It is good to have.

**Comment by SkalskiP** [comment]
@hardikdava how about the overall idea? 💡

**Comment by hardikdava** [comment]
I would keep this as simple as possible. User can choose between `cv` and `pillow` with one command. Creating different Annotators will create lot of confusion in usage and practice.


```
class BoxAnnotator(BaseAnnotator):

    def annotate(self, scene: np.ndarray, detections: Detectionsm, use_pillow: bool=False) -> np.ndarray:
        if use_pillow:
            scene = self._annotate_pillow()
            return scene
        else:
            scene = self._annotate_cv()
            return scene
    def _annotate_cv(self):
        pass
     def _annotate_pillow(self):
        pass
```

**Comment by SkalskiP** [comment]
I don’t want to use pillow for drawing boxes. I want to use pillow only for text annotation and I want to separate drawing labels from drawing boxes.

**Comment by hardikdava** [comment]
@SkalskiP Overall, this is really good idea and your suggested APIs are good for future. It is highly scalabel.

**Comment by SkalskiP** [comment]
Exactly. Problem is that we would need to do it in the way that people could migrate from old API to new API.

**Comment by hardikdava** [comment]
I do not think of any problems of migration with the suggested API. This will work without any issue.

**Comment by SkalskiP** [comment]
@hardikdava I'll create the initial PR to set up the structure, and we will migrate all annotators one by one. Okey?

**Comment by hardikdava** [comment]
@SkalskiP okay. I will be waiting for the issue.

**Comment by SkalskiP** [comment]
@hardikdava can you open PR with this annotator into the `feature/redesigned_annotators` branch?

**Comment by hardikdava** [comment]
> @hardikdava can you open PR with this annotator into the `feature/redesigned_annotators` branch?

Of course. I will make a PR.

**Comment by SkalskiP** [comment]
Hi @hardikdava 👋🏻! Sorry I move so slowly. I'm doing a lot of stuff other than `supervision` this week. :/

**Comment by hardikdava** [comment]
@SkalskiP understood. It's fine. I am working on `Annotators` and trying to answer in the issues. Take your time and later try to test and merge the functions.

**Comment by maddust** [comment]
Just an idea I added to my project to have a visual queue of when an object is triggered by a PolygonZone or LineZone  

https://imgur.com/KyA3Pe2

![GIF](https://i.imgur.com/KyA3Pe2.gif)

**Comment by SkalskiP** [comment]
@maddust 🔥! This looks amazing! You are truly a `supervision` power user!

**Comment by SkalskiP** [comment]
This task is finally completed with: https://github.com/roboflow/supervision/releases/tag/0.15.0 🔥
