### ISSUE TITLE
`move_masks` only supports movement in positive direction

### ISSUE THREAD

**Issue by LinasKo** [roboflow/supervision#1715]
If you compare the code of `move_masks`, `move_detections` and `move_oriented_boxes`, you'll find that only mask code restricts offset direction:

```python
    if offset[0] < 0 or offset[1] < 0:
        raise ValueError(f"Offset values must be non-negative integers. Got: {offset}")
```

It should be possible to move masks in either direction, even if it results in cropping.

To complete this:
- [ ] Change the code so masks can be moved with negative offset
- [ ] Create a unit test suite for `move_masks`

---

It would help us immensely and speed up the review process if you could create a [Colab](https://colab.research.google.com/) showcasing the changes, but for this task it is optional. You may use the [Starter Template](https://colab.research.google.com/drive/1rin7WrS-UvVIe-_Gfxmu-yVslGphOq89?usp=sharing).

**Comment by Anirudh2112** [comment]
Hi @LinasKo, I would like to contribute to this. Can you assign it to me?

**Comment by SkalskiP** [comment]
Hi @Anirudh2112! I just reviewed your code. I made a few changes to take care of an edge case, and I think we’re ready to merge.

**Comment by Anirudh2112** [comment]
@SkalskiP Thank you for reviewing and merging the changes! I really enjoyed contributing to Supervision.
