### ISSUE TITLE
May I ask how to use the botsort tracker?

### ISSUE THREAD

**Issue by DreamerYinYu** [roboflow/supervision#1718]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

May I ask how to use the botsort tracker?Thank you!

**Comment by LinasKo** [comment]
Hi @DreamerYinYu 👋 

We don't have `BotSort` implemented at the moment.

However `sv.Detections` is a straightforward object and you should be able to get it working with some fiddling around. Each `Detections` basically has N-sized arrays `xyxy`, `mask`, `confidence`, `class_id`, `tracker_id`.

You need to create a method that takes `Detections` runs `BotSort` and updates the `tracker_id` value, assigning an `int` ID to each detected object.

Best of luck!
