### ISSUE TITLE
How to call YOLO's built-in API?

### ISSUE THREAD

**Issue by DreamerYinYu** [roboflow/supervision#1719]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

I want to call yolo's model.track so that I can use GPU or other yolo interfaces through yolo. Is this possible? thank you
![20241209110527](https://github.com/user-attachments/assets/372d6bcb-5b40-416d-b9c8-fd319cd946d8)

import cv2
import supervision
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
image = cv2.imread("videos/img.png")

#results = model(image)[0]
results = model.track(image, persist=True, classes=[0], verbose=False, device='0')[0]

detections = supervision.Detections.from_ultralytics(results)

**Comment by LinasKo** [comment]
Hi @DreamerYinYu 👋 

This is part of Ultralytics, so you should ask them in their forums.

However, we have the same tracker (`ByteTrack`) that you can use on any `Detections` object. 

Here's a step-by-step implementation:
* https://supervision.roboflow.com/latest/how_to/track_objects/
