### ISSUE TITLE
[Feature] To add support to Intel OpenVINO models

### ISSUE THREAD

**Issue by mahimairaja** [roboflow/supervision#174]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

## Native support to OpenVINO

Adding support to Intel OpenVINO intermediate representation (IR) could immensely increase the performance of the application. I would like to work on this. And would like to know if there already any team working on this?

Final output : 

```python
import supervision as sv
from utils import detect
from openvino.runtime import Core

ie = Core()
model = ie.read_model(model="model.xml")
compiled_model = ie.compile_model(model=model, device_name="CPU")

result = detect(input_image, compiled_model)[0]
detections = sv.Detections.from_openvino_object_detection(result)
```

### Use case

This could make the edge AI development much easier. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by hardikdava** [comment]
Hello @mahimairaja :wave, thank you for taking time to request the feature. Openvino is good inference accelerator. But the openvino only used for inference part which is common for most of the model but object detection model might need post processing which is different from model to model. Therefore it is very hard to make a dataset format conversion for every models. It is highly recommended to use main detection format i.e. `sv.Detection(xyxy, class_ids, confidence)` all other formats are uniquely designed for different popular models. Though, you can make some suggestions if there is any common output by openvino in specific format.

**Comment by mahimairaja** [comment]
Thanks for the response @hardikdava. 
The output from openvino would be a multidimensional tensor ( n x 6 ) that is similar to yolov8 

```python
result = detect(input_image, compiled_model)[0]
print(type(result))
print(np.shape(result))

# tensor 
# (n, 6)

# n -> no of objects in the frame
```

Hope, adding support for OpenVINO in supervision would be impactful.
> suggestion: OpenVINO could be added to extras so that only the needed edge ai community would leverage the usage.

**Comment by SkalskiP** [comment]
Hi, @mahimairaja 👋🏻! I share @hardikdava reservations. Are we 100% sure OpenVINO models have a consistent output structure?

**Comment by hardikdava** [comment]
@SkalskiP we can close this. The overall idea is nice but after doing a quick research, there is no specific format of output which then can be converted to supervision. So, unfortunately we can not do this.

**Comment by SkalskiP** [comment]
As there is no specific format of output that then can be converted to supervision, we probably won't integrate with OpenVINO.
