### ISSUE TITLE
Error while using yolov8.onnx file with Supervision's Tracking Algorithm

### ISSUE THREAD

**Issue by rdvanerel** [roboflow/supervision#175]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

I'am using Supervision with Yolov8's "yolov8n.pt" file. 
This code is working well. To improve performance, i should use .onnx file. How can i use ".onnx" file with supervision's tracking mode.
```
model = YOLO("yolov8n.pt")
for result in model.track(source=0, verbose = False, stream= True, agnostic_nms=True):
       frame = result.orig_img
       detections = sv.Detections.from_yolov8(result)
        #Box Writing
        frame = box_annotator.annotate(
            scene=frame, 
            detections=detections,
            labels=None,
            skip_label=True
        )

        #Some Code Here

        #Resize Frame
        frame = cv2.resize(frame, (frameWidth,frameHeight))

       #Grayscale Frame
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        cv2.imshow('frame', frame)

        if (cv2.waitKey(30) == 27):
            break
```
Changing model is not working:
`model = YOLO('yolov8n.onnx')`

Got an error:
`WARNING  Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.`

If even i tried some combinations of as follows:
`    for result in  model.track(source="0", stream= True, persist = False, task='detect', verbose = False, agnostic_nms=True, classes = 0) : 
`

Still not working. What should i do for solution? Is it yolo issue or supervision issue? 
Sorry if it is too specific or off-topic

**Comment by hardikdava** [comment]
@rdvanerel This is not an `supervision` issue. This issue belongs to `ultralytics` . You can post this question to `yolov8` repository [here](https://github.com/ultralytics/ultralytics/issues). A suggestion, modify `model = YOLO('yolov8n.onnx')` to `model = YOLO('yolov8n.onnx', task='detect')` though I am not sure. Please visit in `yolov8` project.

**Comment by SkalskiP** [comment]
Hi, @rdvanerel 👋🏻! 

`supervision` can help you to process detections, but if the problem originates from the model, we can't help you. Please follow @hardikdava's instructions. I'm closing the issue.

**Comment by xxz6** [comment]
aaa
