### ISSUE TITLE
Visualizer

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#178]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

`supervision` does not have any image or frame visualizer. Once the `sv.Detections` are processed then it is visualized by `matplotlib` or `opencv`. It would be nice to have a API for visualization. The idea is to create wrapper around `opencv` function as `opencv` is already dependency to the project.

### Use case

Usage:

```
import supervision as sv
image = (...)

sv.Visualizer("Result", image, 0) # for single image viewer

sv.Visualizer("Result", image, 1) # for video frames viewer
```

### Additional

Suggestion:
```
def Visualizer(window_name: str, frame: wait_key=0):
    cv2.imshow(window_name, frame)
    cv2.waitKey(wait_key)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @hardikdava 👋🏻! Thanks a lot for all the time you take to think about new `supervision` features. As for this one, let's keep it for later. I guess we have higher-priority stuff - model evaluation and composable annotators that we should build first. But let's save it for later.

**Comment by SkalskiP** [comment]
@hardikdava, should that task still be on our TODO list?

**Comment by hardikdava** [comment]
@SkalskiP It is a minor but very useful feature. I let you to decide on this.

**Comment by hardikdava** [comment]
@SkalskiP May be we can add it to `hacktoberfest` issue.

**Comment by onuralpszr** [comment]
@SkalskiP  @hardikdava  also please consider this, if we add Visualizer that means they need to use full version opencv instead of headless as well. Somehow we need to check that in case of visualizer via "cv"

**Comment by SkalskiP** [comment]
@onuralpszr, good point!

**Comment by hardikdava** [comment]
@SkalskiP Then let's cancel it.

**Comment by SkalskiP** [comment]
Closing ;)
