### ISSUE TITLE
Track and Count Objects Reset Counter

### ISSUE THREAD

**Issue by Tolgaisikp** [roboflow/supervision#18]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Every time I create a video from the model, the counter continues from where it is and does not reset.

**Comment by SkalskiP** [comment]
Hi, @Tolgaisikp 👋🏻! This is the problem with ByteTrack. There is no way to reset the tracker, which I'm aware of. The only way is to kill the app... But we could look for some better solution together.

**Comment by Tolgaisikp** [comment]
Thanks for your answer @SkalskiP , I can't kill the app because I'm working on colab.
