### ISSUE TITLE
PaddleDetection Support

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#187]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

This issue is regarding supporting [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection). Initially, providing detection conversion script generated from paddledet to supervision.

### Use case

Direct integration of `paddle-detection` model with `supervision`. This enables direct use of model with supervision in application.

### Additional

TODOs:

- Prepare Google Colab for inital tesing
- Integration with supervision

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by hardikdava** [comment]
@SkalskiP Find usage of colab for working example of conversion for `paddledetection` [here](https://colab.research.google.com/drive/1R8mLUFsoflwTK4PSfnOXmKtw7Keu2zlX#scrollTo=5ESh2QrCbbGn).

**Comment by SkalskiP** [comment]
Hi, @hardikdava 👋🏻! I like the idea. I'll mark it with the `version: 0.13.0` tag for now. I want to ensure we close all the other PRs and issues with `version: 0.12.0` first.
