### ISSUE TITLE
Line detection side should be returned

### ISSUE THREAD

**Issue by hamza-sentinel** [roboflow/supervision#190]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Supervision should have a feature in the line zone that would tell if, for a certain detection, we have counted up or down. This way anyone who wants to see the direction of detection can possibly do it.

If you want, I can add that feature.

### Use case

This would be helpful for those who wants to use supervision for counting based on a certain condition or something.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @hamza-sentinel 👋🏻! Thanks a lot for your interest in `supervision`.

We are planning a major `LineCounter` [redesign](https://github.com/orgs/roboflow/projects/5/views/1?pane=issue&itemId=33546612). There are many things that we plan to change, but one of those will be returning a `bool` `numpy` array that would store information if given detection crossed the line.

For now, I'm closing the issue and marking it as `duplicate`. Feel free to reopen the issue if you have more questions.
