### ISSUE TITLE
How to count each selected class individually in the robloflow code?

### ISSUE THREAD

**Issue by adamekcerv** [roboflow/supervision#194]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi,

I would like to ask if it is possible to count each class crossed the in and out line indivdually instead of every class together?

[https://blog.roboflow.com/yolov8-tracking-and-counting/]

I am using this code:

Thank you.

**Comment by SkalskiP** [comment]
Hi @adamekcerv 👋🏻 This is a duplicate of https://github.com/roboflow/supervision/issues/87 issue. We are not yet supporting individual class count, but in the linked issue you will find solutions proposed by the `supervision` community.
