### ISSUE TITLE
Tracking support

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#195]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Expected API

- Try to implement ByteTrack in such a way that more trackers can be added in the future
- Roboflow Inference Server requires:
   - possibility to reset the tracker
   - the possibility of initiating a tracker providing the state

```python
from abc import ABC, abstractmethod


class BaseTracker(ABC):

    @abstractmethod
    def update(self, detections: Detections) -> Detections:
        pass

class BYTETracker(BaseTracker):
   
    def __init__(self, state: dict):
        pass

    @classmethod
    def init(cls, config: dict) -> BYTETracker
        pass

    def update(self, detections: Detections) -> Detections:
        pass

```

### Resources

- ByteTrack official implementation - [link](https://github.com/ifzhang/ByteTrack)
- ByteTrack YOLOv8 implementation - [link](https://github.com/ultralytics/ultralytics/blob/9b723d7cfa4abbfd671f322b362f68d27cf894f8/ultralytics/trackers/byte_tracker.py#L167) 

### Use case

- `supervision` is expected to power tracking in the Roboflow Inference Server
- we want to enable `supervision` users to track objects regardless of the detection model they use easily

### Additional

- The code should be placed in the newly created `supervision.track` package
- Provide a Jupyter Notebook that allows testing of ByteTrack on an example video
- We don't require 100% test coverage but if possible try to add unit tests

**Comment by hardikdava** [comment]
Hi @SkalskiP  :wave:, I am going to love this feature. By the way, I have already done this in separate project of mine. Let me know if I can help you to contribute on this one.

**Comment by SkalskiP** [comment]
Hi, @hardikdava 👋🏻! This one is allocated for one of Roboflow's engineers. But I want the two of us to review the code. 

Could you share the link to your implementation? Or is it private?

By the way, I have a full week allocated for `supervision` support. 🔥

**Comment by hardikdava** [comment]
@SkalskiP I am afraid my project is private. But you can reference [this](https://github.com/kadirnar/bytetrack-pip/blob/main/bytetracker/byte_tracker.py). We can get inspiration from this and for a quick start just make detection format conversion. Later, it can be optimized for a speed.

**Comment by SkalskiP** [comment]
@hardikdava that is another excellent resource!

**Comment by hardikdava** [comment]
@SkalskiP on a side note, if you merger #170 and #171 regarding annotators, then it will be easier for @paulguerrie to verify tracker algorithm.

**Comment by SkalskiP** [comment]
@hardikdava I'm working on my GitHub todo list right now!

**Comment by SkalskiP** [comment]
Tracker is merged into `develop` with https://github.com/roboflow/supervision/pull/256 PR. Closing the task.
