### ISSUE TITLE
⚠️ Pillow `8.4.0` Critical Vulnerabilities

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#202]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

- Along with releasing the `0.12.0` version, `supervision` adds `Pillow` to its dependencies.
- Minimal version of Pillow required by `supervision` is `8.4.0`. It was decided for the sake of compatibility with Google Colab. `8.4.0` is the version of `Pillow` that comes pre-installed in the environment.
- It turns out, however, that version `8.4.0` has several known vulnerabilities, including critical ones.
   - https://github.com/roboflow/supervision/security/dependabot/4
   - https://github.com/roboflow/supervision/security/dependabot/3
   - https://github.com/roboflow/supervision/security/dependabot/1
   - https://github.com/roboflow/supervision/security/dependabot/6
   - https://github.com/roboflow/supervision/security/dependabot/2
   - https://github.com/roboflow/supervision/security/dependabot/5
- The `pip install supervision` command will automatically install the highest `Pillow` version that does not conflict with other packages. If you install `supervision` in a fresh environment, you will probably install the latest version of `Pillow`, which has no known vulnerabilities.
- However, Colab will automatically use the `8.4.0` version already installed in the environment. 
- ⚠️ **WE RECOMMEND** to execute:

    ```
    pip install supervision Pillow==10.0.0
    ```

**Comment by onuralpszr** [comment]
@SkalskiP  let's pin this issue as well. So it won't be loss in new issues (Security wise)

**Comment by SkalskiP** [comment]
@onuralpszr done.

**Comment by mayankagarwals** [comment]
FYI @SkalskiP @onuralpszr 
https://github.com/googlecolab/colabtools/issues/3868#issuecomment-1648602310

**Comment by onuralpszr** [comment]
> FYI @SkalskiP @onuralpszr Colab will close my issue in couple days, pillow version upgrade should reflect soon [googlecolab/colabtools#3868 (comment)](https://github.com/googlecolab/colabtools/issues/3868#issuecomment-1648602310)

Thank you for reporting it.

**Comment by SkalskiP** [comment]
Excellent job @mayankagarwals! I was not aware we could contact the Google Colab team like that.

**Comment by mayankagarwals** [comment]
@SkalskiP @onuralpszr This is closed now. 
https://colab.research.google.com/drive/18FgC-PR6uFUCySI3PQXLmXt9QifOlYXo?usp=sharing
Colab's default version of Pillow is 9.4.0

<img width="1085" alt="image" src="https://github.com/roboflow/supervision/assets/39498938/f5f73d0c-647d-4a53-8037-9ca575ac0bd0">

**Comment by onuralpszr** [comment]
@SkalskiP time close this one too. Thank you for PR and @mayankagarwals  thank you again for report.  You guys awesome 🥳

**Comment by mayankagarwals** [comment]
My pleasure ❤️

**Comment by SkalskiP** [comment]
Closing :)
