### ISSUE TITLE
Update `README.md` `install from source` instructions

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#211]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

With `supervision-0.12.0` release, we are migrating `pyproject.toml` and Poetry. We currently use the commands below for local installation. Do you know if we need to update those? I think it would also make sense to mention we offer `desktop` and `headless` install options.

```
# clone repository and navigate to root directory
git clone https://github.com/roboflow/supervision.git
cd supervision

# setup python environment and activate it
python3 -m venv venv
source venv/bin/activate

# install
pip install -e ".[dev]"
```

**Comment by SkalskiP** [comment]
@onuralpszr could you take a look at this?

**Comment by onuralpszr** [comment]
I will update all docs and also update development process as well

**Comment by SkalskiP** [comment]
@onuralpszr awesome! Thanks a lot for that. Could you also include instructions for manual package building locally? Would be super helpful for people like me.

**Comment by onuralpszr** [comment]
> @onuralpszr awesome! Thanks a lot for that. Could you also include instructions for manual package building locally? Would be super helpful for people like me.

Of course, I will include all and starting with readme.md first

**Comment by SkalskiP** [comment]
@onuralpszr thanks a lot for that! I plan to release `supervision-0.12.0` on Monday. Do you think you will make it on time?

**Comment by onuralpszr** [comment]
> @onuralpszr thanks a lot for that! I plan to release `supervision-0.12.0` on Monday. Do you think you will make it on time?

Almost done already and sending for review so we can do quick changes and get it done today hopefully
