### ISSUE TITLE
ConfusionMatrix - plot bug

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#212]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

ConfusionMatrixAPI is haveing following error

```python
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

### Minimal Reproducible Example

```python

import supervision as sv
from ultralytics import YOLO

ds = sv.DetectionDataset.from_yolo(images_directory_path="../data/coco128/images/train2017",
                                   annotations_directory_path="../data/coco128/labels/train2017",
                                   data_yaml_path="../data/coco128.yaml")

model = YOLO(model="yolov8n.pt")

predictions = []
gts = []

for image_name, image in ds.images.items():
    yolo_det = model.predict([image], imgsz=320, verbose=True)[0]
    det = sv.Detections.from_yolov8(yolov8_results=yolo_det)

    predictions.append(det)
    gts.append(ds.annotations[image_name])

mat = sv.ConfusionMatrix.from_detections(classes=ds.classes, conf_threshold=0.1, iou_threshold=0.5, predictions=predictions, targets=gts)

mat.plot(save_path="mattrix.png", title="coco128-yolov8n")

```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by kirilllzaitsev** [comment]
@hardikdava , thanks for finding it. This PR should address it https://github.com/roboflow/supervision/pull/216

**Comment by hardikdava** [comment]
@SkalskiP, `sv.ConfusionMatrix.convert_detections_to_tensor` should be a `staticmethod`.

**Comment by SkalskiP** [comment]
@hardikdava agree! Let me make it static in #223 PR.

**Comment by SkalskiP** [comment]
Solved with https://github.com/roboflow/supervision/pull/223
