### ISSUE TITLE
Developement - version issue

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#213]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I have not installed `supervision` but running directly for developement purpose.

But I got an following error when I import supervision code:

```
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: supervision
```

After a quick investigation, it is found that `__init__.py` of `supervision` where version information used. It is creating an issue. If I comment this line and the bug is gone.

@onuralpszr Can you take a look?

I think it should be ignorable, if valid version is not found then use `development` version. Though, I do not have concret idea, how to tackle it.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@onuralpszr we could really use your assistance here 🙏🏻
