### ISSUE TITLE
ConfusionMatrix error when no targets but predictions available

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#215]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

This is specific case when there is only background image but on objects are inside. Due to low accuracy of model, model is predicting `False Positives` on background image. I simulate this by  just removing `targets` from one of the image labels. 

Note: If you are using yolo format then open **first** `labels.txt` file and delete all the labels from it.

This action will raise following error:

```
    raise ValueError(
ValueError: Targets must have shape (N, 5). Got (0, 6) instead.
```

### Minimal Reproducible Example

```python

import supervision as sv
from ultralytics import YOLO


ds = sv.DetectionDataset.from_yolo(images_directory_path="../data/coco128/images/train2017",
                                   annotations_directory_path="../data/coco128/labels/train2017",
                                   data_yaml_path="../data/coco128.yaml")


model = YOLO(model="yolov8n.pt")


predictions = []
gts = []

for image_name, image in ds.images.items():
    yolo_det = model.predict([image], imgsz=320, verbose=True)[0]
    det = sv.Detections.from_yolov8(yolov8_results=yolo_det)

    predictions.append(det)
    gts.append(ds.annotations[image_name])


print(gts[0])
print(predictions[0])
mat = sv.ConfusionMatrix.from_detections(classes=ds.classes, conf_threshold=0.1, iou_threshold=0.5, predictions=predictions, targets=gts)

print(mat.matrix)
# mat.plot(save_path="mattrix.png", title="coco128-yolov8n")
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by kirilllzaitsev** [comment]
Hey @hardikdava. Could you try changes in https://github.com/roboflow/supervision/pull/216 and confirm that the issue is fixed? Using your code on my side, having set all targets to be empty:

```python
targets=[
        sv.Detections(xyxy=np.empty((0, 4)), class_id=np.empty((0)))
        for _ in range(len(predictions))
    ]
```

and subsequently running sv.ConfusionMatrix.from_detections, I get:
```python
np.sum(mat.matrix[-1]) == np.sum(mat.matrix)
True
```
