### ISSUE TITLE
`core.py` uses deprecated alias `np.bool`

### ISSUE THREAD

**Issue by cornking03** [roboflow/supervision#22]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Looks like NumPy [deprecated the `np.bool` alias](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) with release 1.20.0. They recommend changing `np.bool` to `bool`

![image](https://user-images.githubusercontent.com/84036755/218271176-0ff4d361-8e1a-4fa4-8e92-a2f63a0dc3a2.png)

### Environment

- Supervision 0.2.0
- Windows 10
- Python 3.9.11

### Minimal Reproducible Example

I got this error when trying to follow the [Detect and Count Objects in Polygon Zone with YOLOv5 / YOLOv8 / Detectron2 + Supervision](https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-detect-and-count-objects-in-polygon-zone.ipynb) tutorial on my machine at home (not using a notebook).

### Additional

In the /detection/core.py file https://github.com/roboflow/supervision/blob/2e76e3db0f4c3aa98892d9cb464cabc34023b518/supervision/detection/core.py#L175

Change `np.bool` to `bool`

I'm kind of curious why this error doesn't get thrown when following along in Colab.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @cornking03 👋🏻! Thanks for your interest in Supervision. It looks like you are right. I'll try to release a fix for that bug soon.

**Comment by SkalskiP** [comment]
Hi, @cornking03 👋🏻! I just released test version of supervision `0.2.1` with fix I promised. 

Could you install it `pip install -i https://test.pypi.org/simple/ supervision` and check if it works for you right now? If it's going to work I'll make the official release.

**Comment by cornking03** [comment]
Looks like that did the trick for me. Thanks for the fix!

Do you have any thoughts on why the error occurred locally, but not in Colab?

**Comment by SkalskiP** [comment]
Hi, @cornking03! Awesome! I released `0.2.1` in PyPI this morning.

> Do you have any thoughts on why the error occurred locally, but not in Colab?

My guess is a different version of `numpy`. Colab comes with pre-installed `numpy=1.21.0` and on that version `np.bool` is deprecated but does not cause the error. On newer versions, you can no longer use it, so it raises exceptions. When you installed it on your windows, you most likely installed the latest `numpy`, and that in effect caused the error.
