### ISSUE TITLE
Ultralytics all model support for detections

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#221]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

`sv.Detections.from_yolov8()` only supports `yolov8` object detection and segmentation result conversion. But there are several other models are implemented in `ultralytics` such as SAM, FastSAM, MobileSAM, RT-DETR.  Current method of conversion do not support all these models. 

### Use case

This feature will completely cover all object detection and segmentation results conversion to supervision detections.  This will make easy integration of future ultralytics models also. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@hardikdava, cool idea! 👍🏻

**Comment by hardikdava** [comment]
Thanks @SkalskiP , can you mark it for next release? Soon I will share colab for testing. It may requires to make one of the API as deprecated stage.

**Comment by SkalskiP** [comment]
Hi, @hardikdava 👋🏻! Yup, I marked it for the `supervision-0.13.0` release.
