### ISSUE TITLE
Object detection mAP score

### ISSUE THREAD

**Issue by mayankagarwals** [roboflow/supervision#232]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

mAP score continues to be one of the widely used model scoring mechanism. I believe something like that is essential for supervision to provide. 

A similar API to Confusion Matrix can be utilized. At a later point, both classes can be refactored to inherit from a evaluation metric interface. 

Functions supported: 
```python
@dataclass
class mAP:
    score: int
    classes: List[str]

    @classmethod
    def from_detections(
        cls,
        predictions: List[sv.Detections],
        target: List[sv.Detections],
        classes: List[str]
    ) -> mAP:
        pass

   @classmethod
    def benchmark(
        cls,
        dataset: sv.DetectionDataset,
        callback: Callable[[np.ndarray], sv.Detections]
    ) -> mAP:
        pass

```

Usage: Similar to Confusion matrix. Refer https://github.com/roboflow/supervision/issues/140

Points of Discussion: 
1. Consider exposing average precision per class per IOU threshold for debugging purposes

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @mayankagarwals 👋🏻 ! Thanks a lot for your passion and excitement. I'm not sure, but I think @hardikdava already started to work on mAP implementation: https://github.com/roboflow/supervision/discussions/206

@hardikdava could you confirm? :)

**Comment by hardikdava** [comment]
@SkalskiP @mayankagarwals Yeah, I have already started working on it. I will be able to finish it by the end of the week.

**Comment by mayankagarwals** [comment]
Oh, amazing. Didn't know this was getting tracked as a discussion. Thanks for pointing out @SkalskiP. Looking forward to the PR @hardikdava  :)

**Comment by SkalskiP** [comment]
@mayankagarwals, no worries :) GitHub allows you to do so many things it is sometimes hard to track. But I'm doing my best.

**Comment by mayankagarwals** [comment]
@SkalskiP anything else on the [backlog](https://github.com/orgs/roboflow/projects/5/views/1) that needs attention? 

Can probably take up[ Instance Segmentation Confusion Matrix](https://github.com/orgs/roboflow/projects/5/views/1?pane=issue&itemId=33897605)

I assume you mean confusion matrix based on overlap of segment instead of `box_iou_batch` on detections : https://github.com/kirilllzaitsev/supervision/blob/4b38634c6365e6f7465fd648fbf1c70ec6884a9a/supervision/metrics/detection.py#L265

**Comment by SkalskiP** [comment]
@mayankagarwals, that's right. Please start with implementing `mask_iou_batch.` It should be equivalent to our `box_iou_batch` but for segmentation. We will need it for all segmentation benchmarks.

**Comment by SkalskiP** [comment]
Added with https://github.com/roboflow/supervision/pull/236 🔥 Thanks a lot @hardikdava

**Comment by SkalskiP** [comment]
@hardikdava Having said that I think we can still work on mAP internals. We calculate so many things 
- Approximated precision/recall curve for every class at every threshold.
- AP for every class at every threshold.

It would be so awesome if we could print and plot it in future releases.

**Comment by hardikdava** [comment]
@SkalskiP Yeah, ofcouse that is already in my mind. Totally agree with you on this.

**Comment by hardikdava** [comment]
Here you go. #269

**Comment by mojeID68411305848-sudo** [comment]
()[g]()]()
