### ISSUE TITLE
Add comments system powered by GitHub Discussions to Supervision docs

### ISSUE THREAD

**Issue by mayankagarwals** [roboflow/supervision#242]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

We can add giscus to supervision docs and reduce the time/friction for anyone to report a bug or raise a query. 

Tracker:
https://github.com/orgs/roboflow/projects/5/views/1?pane=issue&itemId=33979859

I see supervision uses material-mkdocs. It supports theme extension: https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme 
Shouldn't take much time

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mayankagarwals** [comment]
I will require giscus script tag that can be generated by authorized users @SkalskiP @hardikdava

**Comment by SkalskiP** [comment]
Hi, @mayankagarwals 👋🏻 Thanks for doing the initial research. We will probably take a deeper look soon.

**Comment by SkalskiP** [comment]
I'm closing this issue as we just added the comments section to the supervision docs.

![Screenshot 2024-01-17 at 12 30 28](https://github.com/roboflow/supervision/assets/26109316/ea2de14f-f83c-49e6-a6e2-97117044706c)
