### ISSUE TITLE
Show errors for github actions

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#249]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Current github actions are running but whenever we get the errors are suppressed during steps like `code-quality` or `style`. If we know the error then it is possible to improve/fix the errors which is intended to maintain code quality for all the user and package.

@SkalskiP @onuralpszr It would be good to have. Can we do it?

**Comment by onuralpszr** [comment]
@hardikdava  pre-commit  PR I made already doing it.

**Comment by onuralpszr** [comment]
Link for you to check : https://github.com/roboflow/supervision/pull/241

**Comment by hardikdava** [comment]
@onuralpszr Perfect! Looking forward to see in action!

FYI, I am closing this issue for now.
