### ISSUE TITLE
Feature/Sliced Detection

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#250]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

When it comes to detecting small targets in the image normal model fails on a single pass. But the sliced image method can detect the small targets and improves the object detection accuracy. 

```python
from supervision.detections.core import Detections


Class SlicedDetections:

	def from_model(callback: Callable[[np.ndarray],Detections], sliced_image_size: int) -> Detections:
		pass
```

### Use case

Current `sv.Detections` supports many stanadard object detection model. This new API can be works as `callback` method which infers and maps detected objects to original image as `sv.Detections` format.

```python
            >>> import supervision as sv
            >>> from ultralytics import YOLO

            >>> dataset = sv.DetectionDataset.from_yolo(...)

            >>> model = YOLO(...)
            >>> def callback(image: np.ndarray) -> sv.Detections:
            ...     result = model(image)[0]
            ...     return sv.Detections.from_yolov8(result)

            >>> sliced_detections = sv.SlicedDetections.from_model(
            ...     image = image,
            ...     callback = callback,
            ...     sliced_image_size = 224,
            ... )
 ```

### Additional

Original implementation project: https://github.com/obss/sahi

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@hardikdava you read my mind! I was honestly thinking about it. So you would like it to work like https://github.com/obss/sahi?

But I was thinking about a different API. 

```python
import cv2
import supervision as sv
from ultralytics import YOLO

model = YOLO('yolov8s.pt')

# slice level inference
def callback(slice: np.ndarray) -> sv.Detections:
    result = model(slice)[0]
    return sv.Detections.from_yolov8(result)

# define slice parameters in constructor - slice resolution, slice overlay
slicer = sv.Slice(..., callback=callback)

image = cv2.imread(SOURCE_IMAGE_PATH)

# image level inference 
detection = slicer.infer(image=image)
```

**Comment by hardikdava** [comment]
Hey @SkalskiP, I can work on it. Can you make an overview of the API and we can discuss it.

**Comment by hardikdava** [comment]
@SkalskiP I will test out #203 and get  back to you by the end of tomorrow.
