### ISSUE TITLE
Append detection to Detections()

### ISSUE THREAD

**Issue by danigarciaoca** [roboflow/supervision#251]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi! I was wondering if Detections class has any method to easily append a new detection. For instance, to be used when tracking objects, to have a general Detections instance with all detections across frames.

Thanks!

**Comment by SkalskiP** [comment]
Hi, @danigarciaoca 👋🏻!

We support [`sv.Detections.merge`](https://roboflow.github.io/supervision/detection/core/#supervision.detection.core.Detections.merge). You can use it like this:

```python
>>> from supervision import Detections

>>> detections_1 = Detections(...)
>>> detections_2 = Detections(...)

>>> merged_detections = Detections.merge([detections_1, detections_2])
```

Is it what you are looking for?

**Comment by danigarciaoca** [comment]
Wow sorry, that was exactly what I was looking for. Thanks!
