### ISSUE TITLE
Drop `sv.Detections.from_yolov8` support

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#253]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

https://github.com/roboflow/supervision/pull/222 introduces general support for all models offered by `ultralytics` package. We added `sv.Detections.from_ultralytics` method, and that makes `sv.Detections.from_yolov8` redundant and deprecated. We will drop `sv.Detections.from_yolov8` support with `0.15.0`.

**Comment by capjamesg** [comment]
@SkalskiP Is there a reason to drop the deprecation notice so soon and remove the code entirely? We use the YOLOv5 and YOLOv8 data loaders in a few places on the Roboflow site that we'll need to update.

**Comment by SkalskiP** [comment]
Hi, @capjamesg 👋🏻! Is `supervision-0.15.0` soon? Given the frequency of our releases, I think this task will go into effect no sooner than in 1.5 months.

1. YOLOv5 support stays as it is.
2. YOLOv8 support is getting migrated. All you must do is change `from_yolov8` into `from_ultralytics`. No other changes should be required.
