### ISSUE TITLE
feature/FpsMonitor

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#255]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Computer vision practice often requires to monitor the speed of the algorithm to check the performance. The latency performance is measure with the help of `FPS-Monitor` which measures the processing time for defined steps.

### Use case

- Latency measurement for general case.

### Additional

```python
class FPSMonitor:	
	
	def __init__(self):
		self.last_tick = None
		self.fps = 0
	
	def tick(self)->None:
		pass
		
	def get_average_fps(self) -> float
		return self.fps
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
Fixed by #280
