### ISSUE TITLE
DetectionDataset.from_yolo support for subdirectories

### ISSUE THREAD

**Issue by hugo082** [roboflow/supervision#259]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Being able to import dataset with subdirectories like:
```py
dataset = sv.DetectionDataset.from_yolo(
    images_directory_path="./images",
    annotations_directory_path="./labels",
    data_yaml_path="..."
)

# .
# ├── images
#     └── group
#         ├── 00000.png
#         └── ...
# └── labels
#     └── group
#         ├── 00000.txt
#         └── ...
``` 

Currently we can only import:
```py
# .
# ├── images
#     ├── 00000.png
#     └── ...
# └── labels
#     ├── 00000.txt
#     └── ...
``` 

### Proposal

Replace `Path.glob` with [`Path.rglod`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.rglob) inside the [`list_files_with_extensions`](https://github.com/roboflow/supervision/blob/d6d4760fce51a2b6311493045d171ee600a2ff51/supervision/utils/file.py#L51) function

> This is like calling [Path.glob()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob) with “**/” added in front of the given relative pattern:

**Current implementation**
```python
def list_files_with_extensions(
    directory: Union[str, Path], extensions: Optional[List[str]] = None
) -> List[Path]:
    directory = Path(directory)
    files_with_extensions = []

    if extensions is not None:
        for ext in extensions:
            files_with_extensions.extend(directory.glob(f"*.{ext}"))
    else:
        files_with_extensions.extend(directory.glob("*"))

    return files_with_extensions
``` 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
I'm closing the issue.

**Comment by hugo082** [comment]
> Does it look useful?

Not really user-friendly if there are a lot of groups / sub-groups but I should be able to have something that works with `DetectionDataset.merge`, thank you
