### ISSUE TITLE
0.2.1 bug: AttributeError: 'list' object has no attribute 'boxes'

### ISSUE THREAD

**Issue by softwarelifecycle** [roboflow/supervision#26]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I was running the Roboflow tutorial: https://www.youtube.com/watch?v=QV85eYOb7gk

And after adding in this code:
while True:
        ret, frame = cap.read()
        result = model(frame)
        detections = sv.Detections.from_yolov8(result)

        frame = box_annotator.annotate(scene=frame, detections=detections)

        cv2.imshow("yolo8", frame)

        if (cv2.waitKey(30) == 27):
            break
            
It errored with this message:
  File "/Data/Dropbox/Python/YOLO/YOLO8/VehicleID/vehicleID_env/lib/python3.10/site-**packages/supervision/detection/core.py", line 130, in from_yolov8
    xyxy=yolov8_results.boxes.xyxy.cpu().numpy(),
AttributeError: 'list' object has no attribute 'boxes'**
            

### Environment

-Supervision 0.2.1  Latest PIP install on 2/20/2022
-Ultralytics: 8.0.26
-Ubuntu  22.04 LTS

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @softwarelifecycle 👋🏻 

Try to do `result = model(frame)[0]`. The model returns one element list. You can also take a look at this project: https://github.com/SkalskiP/yolov8-live for reference :)

**Comment by SkalskiP** [comment]
@softwarelifecycle did it worked?
