### ISSUE TITLE
Allow documentation versioning

### ISSUE THREAD

**Issue by capjamesg** [roboflow/supervision#279]

**Comment by capjamesg** [comment]
I really like this idea! You can use [mike](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) to retain multiple versions of documentation. I'm setting it up for another project right now. Note that `mike` replaces `mkdocs` commands, so there would be slight changes in how we deploy the docs.

Happy to implement this if we want it!

**Comment by SkalskiP** [comment]
Hi, @capjamesg 👋🏻! As I understand it, `mike` is built on top of `mkdocs`. So our docs would visually look the same?

**Comment by capjamesg** [comment]
@SkalskiP Yep! They would look the same. `mike` would add a dropdown for versions.

**Comment by SkalskiP** [comment]
Awesome! Can you work on a PR for the `supervision-0.14.0` release?

**Comment by capjamesg** [comment]
Yep! I'll do this in addition to the CONTRIBUTING.md updates for the next release!

**Comment by SkalskiP** [comment]
Awesome! In that case, I'll add it to our plan for `supervision-0.14.0`

**Comment by hardikdava** [comment]
Can we also add how to modify documentation in case of modifying existing feature and adding a new feature?

**Comment by capjamesg** [comment]
I'm working on this. I'm having a problem getting the version dropdown to show in the docs navigation bar. I'll keep working on it!

**Comment by SkalskiP** [comment]
@capjamesg Can't wait to see that! Any chance we could create docs for previous versions of `supervision`? We have git [tags](https://github.com/roboflow/supervision/tags) for all previous releases.

**Comment by onuralpszr** [comment]
Today we deploy multi version via mike and also deploy old versions as well.

@SkalskiP  thank you for your administration help.
