### ISSUE TITLE
YOLOv7 and supervision

### ISSUE THREAD

**Issue by matdealm** [roboflow/supervision#28]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi searched around and have not found any implimentations of supervision on YOLOv7. Have you experimented with this? Should it be the same method as demonstrated in the YOLOv8?

**Comment by SkalskiP** [comment]
That is perfectly possible. It is just a bit more work to set it up. Feel free to reach out in case of any problems :)
