### ISSUE TITLE
Make `CONTRIBUTION.md` :fire:

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#283]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Let's make our `CONTRIBUTION.md` :fire:! We can take a lot of inspiration from [YOLOv8](https://github.com/ultralytics/ultralytics/blob/main/CONTRIBUTING.md).

Here is a [previous PR](https://github.com/roboflow/supervision/pull/229) for additional context.

**Comment by SkalskiP** [comment]
I mostly focus on the visual part. But @hardikdava and @onuralpszr do you have any suggestions on what additional information should be added to `CONTRIBUTION.md`?

**Comment by onuralpszr** [comment]
@SkalskiP  based on  yolov8 example extra to add code-style with pre-commit and here how I wrote before


```markdown
#### Pre-commit Tool

This project utilizes the [pre-commit](https://pre-commit.com/) tool to maintain code quality and consistency. Before submitting a pull request or making any commits, it is important to run the pre-commit tool to ensure that your changes meet the project's guidelines.

To run the pre-commit tool, follow these steps:

1. Install pre-commit by running the following command: `poetry install`. It will not only install pre-commit but also install all the deps and dev-deps of project

2. Once pre-commit is installed, navigate to the project's root directory.

3. Run the command `pre-commit run --all-files`. This will execute the pre-commit hooks configured for this project against the modified files. If any issues are found, the pre-commit tool will provide feedback on how to resolve them. Make the necessary changes and re-run the pre-commit command until all issues are resolved.

4. You can also install pre-commit as a git hook by execute `pre-commit install`. Every time you made `git commit` pre-commit run automatically for you.
```

**Comment by hardikdava** [comment]
Here are some other contibution guidelines which I liked overall.

- [opencv](https://github.com/opencv/opencv/blob/4.x/CONTRIBUTING.md)
- [cvat](https://opencv.github.io/cvat/docs/contributing/)

General ideas:

- Add section for license agreement and if license of function/algorithm is not supporting MIT license then discuss issues with maintainers.
- Add section for modifying documentation for example modification of mkdocs file, etc
- For bug issue/new feature issue provide code snippet or colab(open access) for debug/testing
- Specific guidelines for docstring and coding style

**Comment by SkalskiP** [comment]
Thanks a lot, @hardikdava and @onuralpszr! 🙏🏻 @capjamesg would be awesome if you could work on it this week.

**Comment by onuralpszr** [comment]
We should also cover code-coverage too 

PR: https://github.com/roboflow/supervision/pull/284
