### ISSUE TITLE
Avast is detecting the landing page as infected

### ISSUE THREAD

**Issue by Rxbsxn** [roboflow/supervision#293]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hey, 
I just wanted to verify your landing page, but unfortunately I was blocked by Avast antivirus saying the page is infected

I thought it may be worth to know for you
![image](https://github.com/roboflow/supervision/assets/17426143/1c3871c1-1987-4c3c-96d9-c28aee1081df)

**Comment by Rxbsxn** [comment]
WOW! @onuralpszr thanks for really fast reply - I filled the form as well

**Comment by SkalskiP** [comment]
Yeah, great reflex @onuralpszr! 🔥 I filled form as well.

**Comment by Rxbsxn** [comment]
@onuralpszr @SkalskiP I think it's solved by now - I'm able to enter your landing page 🎉🎉🎉

Thanks for act quickly

**Comment by onuralpszr** [comment]
@Rxbsxn  awesome, glad it is solved.
