### ISSUE TITLE
No error check for an empty input array to supervision.detection.utils.polygon_to_mask

### ISSUE THREAD

**Issue by ShubhamKanitkar32** [roboflow/supervision#299]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

`cv2.fillPoly` can not handle empty arrays. 

Error: `cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/drawing.cpp:2431: error: (-215:Assertion failed) p.checkVector(2, CV_32S) >= 0 in function 'fillPoly'`

### Environment

- Supervision: 0.13.0
- OS: Ubuntu 20.04
- Python: 3.8.10

### Minimal Reproducible Example

```
import supervision as sv
import numpy as np

polygon = np.array([[]], dtype=np.int64)
resolution_wh = (2048, 1536)

sv.detection.utils.polygon_to_mask(polygon, resolution_wh)
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
Thank you for reporting the issue @ShubhamKanitkar32  

But technically error check done by "opencv" side.  So I believe there is nothing to fix for this case, because sending empty array should be  cause problem already, or can you show me case mask would be okay if return "np.zeros((height, width))"  only ?

**Comment by ShubhamKanitkar32** [comment]
Thank you for the response @onuralpszr 

There are cases when the `process_roboflow_result()` method is passed with empty (x, y) coordinates from the `roboflow` model response. In such scenarios, there either needs to be a way to make sure that they do not get added to the polygon [array](https://github.com/ShubhamKanitkar32/supervision/blob/develop/supervision/detection/utils.py#L364-L366) or Null check the polygon array before processing with fillPoly.

Apologies, the last part of your question is unclear to me. Hope ^this address it.

**Comment by SkalskiP** [comment]
Hi, @ShubhamKanitkar32 👋🏻

Thanks for submitting the issue. Before making too quick concessions, @ShubhamKanitkar32, could you provide an example of the Roboflow response causing the exception?

As I understand, it can only happen when the user runs a segmentation model. This is only when the `points` key exists in response. The question that comes to my mind is how it is possible that a valid segmentation response can have empty `points` key.

**Comment by ShubhamKanitkar32** [comment]
Hi @SkalskiP - sure, here is my testing setup.

- Yolov8 instance segmentation 
- Inference running using `roboflow/roboflow-inference-server-gpu` container
- Using `requests.post()` to query a response from a model hosted on a local roboflow server
- Output response is passed to `supervision.Detections.from_roboflow()`
- Plotting these detections using the `MaskAnnotator` object 

For one of the testing cycles, the response outputted 4 detections, one of which resulted in the following `polygon` numpy array - `array([], dtype=int64)`

(Looping in @Tyler-Odenthal)

**Comment by SkalskiP** [comment]
Awesome @ShubhamKanitkar32! Can you paste here the JSON you pass to `supervision.Detections.from_roboflow()`?

I want to understand what we should do with this object.

1. Filter out completely. If detection in the instance segmentation task contains less than 3 `points` we won't be able to produce the mask, so to keep things simple, we just skip it.
2. Keep it but produce a blank mask.

**Comment by onesky2015** [comment]
NameError: name 'IMAGE' is not defined,How can I solve the problem I have on colab?

**Comment by SkalskiP** [comment]
Hi @onesky2015. Looks your issue is unrelated to this thread.

**Comment by SkalskiP** [comment]
@ShubhamKanitkar32 I spoke with [inference](https://github.com/roboflow/inference) team and I guess I understand what is the reason: 

> There is a possibility that the contour finding operation fails. In that case we don't throw an error since there is still a good detection that we can return. Instead, we simply return an empty points array. Here's where that contour finding logic lives: https://github.com/roboflow/inference/blob/4ab4782384732f8beae4ce7a431b4997ab2265e4/inference/core/utils/postprocess.py#L87

In that case, I suggest modifying `process_roboflow_result()` and filtering out all results with an invalid `point` key. In this case invalid means less than 3 points.

**Comment by ShubhamKanitkar32** [comment]
@SkalskiP Sure, I can help with this one.

> Can you paste here the JSON you pass to `supervision.Detections.from_roboflow()`?

This might be tricky because when I encountered this issue, I was running live inference. It might be difficult to recreate that testing scene but I will give it a try sometime today/tomorrow.

**Comment by SkalskiP** [comment]
@ShubhamKanitkar32 

> This might be tricky because when I encountered this issue, I was running live inference. It might be difficult to recreate that testing scene, but I will give it a try sometime today/tomorrow.

No worries. As I said, I spoke with the `inference` team, and I understand the source of the issue. We can use this JSON as test cases:


```python
example_roboflow_result = {
    "predictions": [
        {
            "x": 500,
            "y": 500,
            "width": 100,
            "height": 100,
            "class": "car",
            "confidence": 0.8,
            "points": []
        }
    ],
    "image": {
        "width": 1000,
        "height": 1000
    }
}
```

Loading this should give the following result:

```python
import supervision as sv

class_list = ["person", "car", "dog"]

sv.Detections.from_roboflow(
    roboflow_result=example_roboflow_result,
    class_list=class_list
) == sv.Detections.empty()
```

> Sure, I can help with this one.

Awesome! 🔥 In that case please update your current PR to reflect that change. Let's add changes to `sv.Detections.from_roboflow` and to be precise to `process_roboflow_result` that runs most of the logic.

Right now the logic works like this:

```
- initiate xyxy, confidence, class_id and masks lists 
- loop over predictions:
    - extract xyxy, confidence, class_id from prediction and append them to the appropriate lists
    - if "points" in prediction:
        - extract mask from prediction and append it to the appropriate list
- return xyxy, confidence, class_id and masks lists 
```

After changes we want it to work like this:

```
- initiate xyxy, confidence, class_id and masks lists 
- loop over predictions:
    - extract xyxy, confidence, class_id from prediction
    - if "points" not in prediction:
        - append xyxy, confidence, class_id to the appropriate lists
    - else:
        - if "points" contain at least 3 points:
            - extract mask from prediction
            - append xyxy, confidence, class_id, mask to the appropriate lists
- return xyxy, confidence, class_id and masks lists 
```

**Comment by ShubhamKanitkar32** [comment]
@SkalskiP Appreciate the test setup and the pseudocode!

I have a couple of clarifying questions:
1. > if "points" contain at least 3 points:

Does this condition has to be at least 3 or at least 2 points? Based on the current implementation, I am seeing `prediction[points]` contain 2 points: `point['x']` and `point['y']`. Am I missing anything?

2. In the case of:
> if "points" not in prediction:

Are we supposed to skip masks list or append `None` to keep entries consistent in all the output lists?

**Comment by SkalskiP** [comment]
> Does this condition has to be at least 3 or at least 2 points? Based on the current implementation, I am seeing `prediction[points]` contain 2 points: `point['x']` and `point['y']`. Am I missing anything?

The thing is, we need at least 3 points to build a polygon on the plane. We look for this structure at minimum:

```
{
    "predictions": [
        {
            "x": 100,
            "y": 100,
            "width": 200,
            "height": 200,
            "class": "person",
            "confidence": 0.9,
            "points": [
                {
                    "x": 100,
                    "y": 100
                },
                {
                    "x": 100,
                    "y": 300
                },
                {
                    "x": 300,
                    "y": 300
                }
            ]
        },
        {
            "x": 500,
            "y": 500,
            "width": 100,
            "height": 100,
            "class": "car",
            "confidence": 0.8,
            "points": []
        }
    ],
    "image": {
        "width": 1000,
        "height": 1000
    }
}
```

> Are we supposed to skip masks list or append `None` to keep entries consistent in all the output lists?

If we process instance segmentation, `sv.Detections.mask` is `np.ndarray` if we process detections, `sv.Detections.mask` is None. Take a look at the current implementation of `process_roboflow_result`. Especially `masks = np.array(masks, dtype=bool) if len(masks) > 0 else None` at the end of the function. In the detection case `masks` will be empty and `process_roboflow_result` will return `None ` as the last tuple element.

If you feel it is a bit unclear. I'm happy to implement that fix. Just let me know. :)

**Comment by ShubhamKanitkar32** [comment]
That makes sense. Apologies, mixed up point and points variable names in my head. 
Pushed the change. Let me know if you think it is showing the expected behavior.

While validating the mask, it raises a ValueError when one of the output predictions contains less than 3 points. 
```
ValueError: mask must be 3d np.ndarray with (n, H, W) shape
```

**Comment by SkalskiP** [comment]
Hi @ShubhamKanitkar32 👋🏻 I committed a few changes to your PR branch and merge changes into `develop`. Would be awesome if you could test it. I'm closing the issue for now. Feel free to reopen if you notice any unwanted behaviors.

**Comment by ShubhamKanitkar32** [comment]
Looks good to me. Thanks for the quick fix @SkalskiP
