### ISSUE TITLE
LineZone and LineZoneAnnotator not exposed at top level

### ISSUE THREAD

**Issue by dceejay** [roboflow/supervision#30]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

fails to expose latest LineZone changes

line_counter = sv.LineZone(start=LINE_START, end=LINE_END)
AttributeError: module 'supervision' has no attribute 'LineZone'

### Environment

Supervision: 0.2.1

### Additional

just need to add
```
from supervision.detection.line_counter import LineZone, LineZoneAnnotator
```
to top level __init.py__

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @dceejay 👋🏻! Thanks a lot for pointing that out. Would you like to submit a PR with that change?

**Comment by dceejay** [comment]
ok - done.
also I note the annotator .annotate method is somewhat different to the zone one... not sure if they could be made more similar ?

**Comment by SkalskiP** [comment]
Yup. We actually plan to redesign our annotators. So it is on our TODO list for the near future.

**Comment by SkalskiP** [comment]
PR is merged. I'm closing the issue. Thanks for help :)
