### ISSUE TITLE
How to change the line text from "in/out" to something custom?

### ISSUE THREAD

**Issue by raj-kapil** [roboflow/supervision#304]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

<img width="143" alt="image" src="https://github.com/roboflow/supervision/assets/103250862/b3b7f699-c59b-46c4-be82-2c2eef0b45e1">

How to change the text from IN/OUT to something else?

**Comment by raj-kapil** [comment]
Never mind found it. LineZoneAnnotator has custom_in_text and custom_out_text parameters.

**Comment by SkalskiP** [comment]
Hi @raj-kapil 👋🏻! Awesome, you managed to find the answer on your own!
