### ISSUE TITLE
[Documentation Improvement] Document is missing description on line_counter.py and LineZone Class

### ISSUE THREAD

**Issue by grhaonan** [roboflow/supervision#335]
Hi team,

It seems line the current documentation https://supervision.roboflow.com/quickstart/detections/ doesn't have any description on LineZone class and it took me a while to look into the source code to realise the previous LineCounter has been replaced by Line Zone.

https://github.com/roboflow/supervision/blob/a3a19d93bc66491f48bdef8d657d5c5896dc128b/supervision/detection/line_counter.py#L11

I am not sure if this is by purpose or it is actually missing, thanks

**Comment by onuralpszr** [comment]
Hello Dustin, this is one of our important to do list that we need to make sure we have a updated documention. But  project is young and have very active changes. Sorry for the inconvenience.

**Comment by grhaonan** [comment]
all good, thanks :)

**Comment by hardikdava** [comment]
@onuralpszr @grhaonan It will be updated with improved feature for `sv.LineZone`. Take a look at PR: https://github.com/roboflow/supervision/pull/266

**Comment by SkalskiP** [comment]
@grhaonan we just merge update adding `LineZone` to docs: https://supervision.roboflow.com/detection/tools/line_zone/. I'm closing the issue.
