### ISSUE TITLE
InferenceSlicer doesn't work with fixed-input-size models

### ISSUE THREAD

**Issue by adrianboguszewski** [roboflow/supervision#352]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I'm not sure if it's a bug or feature request so feel free to change it.

The current implementation of InferenceSlicer assumes the model has dynamic inputs and can accept any size of the input, so it doesn't work for models with fixed input shapes. 

The first exception is in the constructor when validating.

### Environment

supervision 0.14.0
Ubuntu 22.04
Python 3.10

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hardikdava** [comment]
Thanks @adrianboguszewski for taking time to use supervision. Can you give us some more details? May be an example script would be great?

**Comment by adrianboguszewski** [comment]
I don't have any snippet of code to share, but please export YOLOv8 with a fixed input size e.g., 640x640, load it and then try to use sample code from https://github.com/roboflow/supervision/releases/tag/0.14.0

**Comment by adrianboguszewski** [comment]
Export can be done with 
```det_model.export(format="openvino", dynamic=False, half=True)```

**Comment by hardikdava** [comment]
The code snippet you shared is an example code which works with yolov8 dynamic image size. If you export the trained model in different configurations like fixed image size in this case then you have to modify `callback` based on your model prediction. It is not compulsory that you have to use the mentioned callback function. You can change it entirely but keep in mind that it should only returns detection in supervision format. You do not have to worry about anything else. 

I would suggest change model prediction part based on your trained model, convert your predictions to `supervision.Detections` and use new callback with `sv.infer`. Then you should be able to work with your model.

**Comment by SkalskiP** [comment]
Hi @adrianboguszewski and @hardikdava 👋🏻 I'm sorry for such a late response. I've been on vacation for the past two weeks, and now I'm trying to catch up. Where are we with this issue?

**Comment by hardikdava** [comment]
@SkalskiP we can close this.

**Comment by adrianboguszewski** [comment]
I didn't have time to spent more time on this so I gave up. But I'm almost sure it doesn't work for the model exported with the code I shared above.

**Comment by SkalskiP** [comment]
Hi @adrianboguszewski 👋🏻, please help me out to fully understand. That would mean that if the model only accepts, for example, 640x640 input, and you set the slice size to 640x640, some slices have a different size?

**Comment by adrianboguszewski** [comment]
That's correct. The code assumes dynamic shapes only. So:
1. validate_inference_callback creates a fixed-size tensor - this is the first fail 
![image](https://github.com/roboflow/supervision/assets/4547501/3eabe7ad-1231-4d22-80ff-4cf3877e4a6b)
2. If we skip the above, the slicer returns various shapes, which don't fit the model input size - this is the second fail. Test the code below:
```
import cv2
from ultralytics import YOLO
from openvino import runtime as ov
import supervision as sv

det_model = YOLO("yolov8n-seg")
out_dir = det_model.export(format="openvino", dynamic=False, half=True)

core = ov.Core()
model = core.read_model(f"{out_dir}/yolov8n-seg.xml")
model = core.compile_model(model, device_name="AUTO", config={"PERFORMANCE_HINT": "LATENCY"})

frame = cv2.imread("sample.jpg")

def callback(image_slice) -> sv.Detections:
    print(image_slice.shape)
    return sv.Detections.empty()

slicer = sv.InferenceSlicer(callback=callback, slice_wh=(640, 640))
detections = slicer(frame)
```

@SkalskiP I'm also going on a 2-week vacation tomorrow, so I'm leaving it to you. I hope the above explanation shows all issues with the implementation (at least all I discovered) :)
