### ISSUE TITLE
Real time video streaming

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [roboflow/supervision#357]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

I have a question around the `VideoSink`. I know that support for a static video file is there, but is there support for real time streaming? Maybe by using something like an RTSP address? 

I was digging through the docs and did not find anything that insinuated there was. 

Thanks!

**Comment by hardikdava** [comment]
@Alex-Wenner-FHR Thanks for raising an issue. Currently, it is not supported. If `cv2.VideoCapture` supports direct RTSP stream then you should be able to use it directly. Otherwise, I am afraid it is not supported yet.

**Comment by SkalskiP** [comment]
Hi @Alex-Wenner-FHR 👋🏻 Like @hardikdava said, it is not supported yet. But I like the idea a lot, I'd love to add this to our roadmap.

**Comment by Alex-Wenner-FHR** [comment]
Would you be willing to provide a tiny sample involving using the `cv2.VideoCapture` instead of the `VideoSink`? 

No big deal if not - just curious to see how you would implement this combination of supervision and opencv!

Feel free to close this comment whenever you see fit 😄

**Comment by hardikdava** [comment]
@Alex-Wenner-FHR after a quick search I found [this](https://lindevs.com/capture-rtsp-stream-from-ip-camera-using-opencv). But as I mentioned, we can not help you at the moment.

**Comment by Alex-Wenner-FHR** [comment]
@hardikdava thanks! I know that this is possible with cv2. I am just curious as to how to combine this with supervision code itself. No big deal though - I can work through it. 

I would love to see this feature implemented so I can stay on Supervision's level of abstraction! Thanks again.

**Comment by hardikdava** [comment]
You can do as following:


```python

import supervision as sv

video_info = VideoInfo(width=3840, height=2160, fps=25)

with sv.VideoSink(target_path='target_video.mp4', video_info=video_info) as sink:
    YOUR PART OF FRAME GENERATION
    sink.write_frame(frame=frame)

```

As of directly capturing RTSP stream with `sv.get_video_frames_generator()` is not supported yet.

@SkalskiP we could allow to use `sv.VideoSink()` with callback method.

**Comment by spencerswagger** [comment]
you can edit local source code in `supervision/util/video.py`.
```python
149:  if not success or frame_position >= end > 0:
```
I added `> 0`, because RTSP stream total frames always less than 0.

!!! It's only for local develoment, i'm not sure if it is stable.

**Comment by SkalskiP** [comment]
Hi @Alex-Wenner-FHR and @spencerswagger 👋🏻 I'm sorry for such a late response. I've been on vacation for the past two weeks and now I'm trying to catch up.

Would something like this work? 

```python 
import supervision as sv

video_info = VideoInfo(width=3840, height=2160, fps=25)

with sv.VideoSink(target_path='target_video.mp4', video_info=video_info) as sink:
    
    cap = cv2.VideoCapture(RTSP_ADDRESS)

    while True:
        ret, frame = cap.read()
        sink.write_frame(frame=frame)
```

**Comment by onuralpszr** [comment]
> Hello, how can we do this for an m3u8 url?

 Hello yes opencv already handle m3u8 streams as well so all good

**Comment by sanchex1018** [comment]
first of all congratulate you for the excellent work done with Supervision. To implement RTSP with Supervision you cannot make use of sv.videoSink(). But, if you check the car tracking and counting notebook you can use the code snippet in the case of a single frame. Then, openCV will only do the job with Supervision frame by frame. Here is an example of my own:

    `import cv2
    import supervision as sv
    from ultralytics import YOLO
    MODEL = "best.pt"
    model = YOLO(MODEL)
    model.fuse()
    CLASS_NAMES_DICT = model.model.names
    box_annotator = sv.BoxAnnotator(thickness=1, text_thickness=1, text_scale=1)
    line_zone_annotator = sv.LineZoneAnnotator(thickness=1, text_thickness=1, text_scale=1)
    LINE_START = sv.Point(50, 240)
    LINE_END = sv.Point(590, 240)
    line_zone = sv.LineZone(start=LINE_START, end=LINE_END)
    byte_tracker = sv.ByteTrack(track_thresh=0.25, track_buffer=100, match_thresh=0.8, frame_rate=30)
    cap = cv2.VideoCapture(0)  
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    print(f"FPS: {fps}")
    print(f"Resolución: {width}x{height}")
    while True:
        ret, frame = cap.read()
        if not ret:
            break
    
    
        results = model(frame)[0]
        detections = sv.Detections.from_ultralytics(results)
    
        detections = byte_tracker.update_with_detections(detections)
    
        labels = [
            f"#{tracker_id} {CLASS_NAMES_DICT[class_id]} {confidence:0.2f}"
            for _, _, confidence, class_id, tracker_id in detections
        ]
        
        box_annotated_frame=box_annotator.annotate(scene=frame.copy(),
                                    detections=detections,
                                    labels=labels)
    
        
        line_zone.trigger(detections)
    
        show=line_zone_annotator.annotate(box_annotated_frame, line_counter=line_zone)
    
    
        cv2.imshow("Counting", show)
    
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    
    
    cap.release()
    cv2.destroyAllWindows()
`

**Comment by iraadit** [comment]
Hi

I would also be interested in video streaming, specifically by a 'process_stream()' function to complement 'process_video()'

**Comment by wilsonlv** [comment]
I am also paying attention to this issue, does it work now ?

**Comment by SkalskiP** [comment]
Hi @wilsonlv 👋🏻 Are you interested in sending video streams or capturing them?

**Comment by wilsonlv** [comment]
@SkalskiP capture them and then track object, now i think i have worked it out, thank you all the same !

**Comment by wilsonlv** [comment]
@iraadit  First, capture the RTSP video stream using CV, and then just hand each frame over to SV for processing.

**Comment by g7crservice-harshita-gupta** [comment]
Hello All,
I am facing an issue where my RTSP streaming get stopped after 5 to 10 minutes. It will be great if some help can be provided. I invested enough about this but did not found any solution.

RTSP camera Specification: [https://signellent.com/uploads/media/HIKVISIONDS-2CD130P-I.pdf](url)
This error logged mostly:
**[h264 @ 0x55760b366d40] error while decoding MB 86 9, bytestream -14
[h264 @ 0x55760b366d40] left block unavailable for requested intra4x4 mode -1
[h264 @ 0x55760b366d40] error while decoding MB 0 6, bytestream 47281
[h264 @ 0x55760b366d40] error while decoding MB 37 65, bytestream -8**

I am using cv2 package:  cap = cv2.VideoCapture(url)

```import cv2
import time

#Replace with your RTSP URL
rtsp_url = 'xxxxx'

def connect_to_stream(url):
    cap = cv2.VideoCapture(url)
    start_time = time.time()
    return cap, start_time

def read_frame(cap):
    ret, frame = cap.read()
    return ret, frame

def reconnect_stream(url):
    print("Attempting to reconnect...")
    cap.release()
    time.sleep(5)  # Wait for 5 seconds before trying to reconnect
    cap, start_time = connect_to_stream(url)
    return cap, start_time

cap, start_time = connect_to_stream(rtsp_url)

if not cap.isOpened():
    print("Error: Could not open video stream")
else:
    while True:
        ret, frame = read_frame(cap)
        
        if not ret:
            end_time = time.time()
            total_run_time = end_time - start_time
            print(f"Stream ran for {total_run_time} seconds, exited with Error: Could not read frame")
            cap, start_time = reconnect_stream(rtsp_url)
            continue  # Continue to the next iteration of the loop
        gray_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow('RTSP Stream (Grayscale)', gray_frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()
```

**Comment by LinasKo** [comment]
@PawelPeczek-Roboflow, any insights on this?
