### ISSUE TITLE
Support Concurrent Processing with SAHI

### ISSUE THREAD

**Issue by capjamesg** [roboflow/supervision#358]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

At the moment, the `sv.InferenceSlicer` method runs inference iteratively. I propose that we offer a concurrent processing method so that inference can run faster. The API would remain the same, but `supervision` would run the callbacks concurrently and assemble the results rather than iteratively.

Running a benchmark on a single image using the Roboflow hosted API resulted in the following results:

```
Detections w/o SAHI: 127
--- 1.460580825805664 seconds ---
Detections w/ SAHI: 146
--- 13.294042110443115 seconds ---
```

Most of this time is likely API calls, but the time taken for the SAHI approach could be significantly reduced with concurrent processing.

### Use case

This feature has been requested by a Roboflow customer.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by hardikdava** [comment]
@SkalskiP I am closing it as it is completed.

**Comment by SkalskiP** [comment]
Thanks for the cleanup, @hardikdava!
