### ISSUE TITLE
Support for python3.6 

### ISSUE THREAD

**Issue by Batselot** [roboflow/supervision#359]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi there! 

It seems that you have already stated that this works for python3.8 and the other versions but I wonder if there was a way to implement this to python3.6 especially line counter. What would you recommend on that? I don't think package versions are that much of a deal here are they?

**Comment by onuralpszr** [comment]
Hello @Batselot, the reason we don't support python 3.6 is same reason we drop for py37 (https://github.com/roboflow/supervision/issues/179). Main issue is pytorch and tf drop their support already and it would be also require extra work but we passed that point python 3.6 and 3.7 are already EOL.  

Second option is you can clone the repository change python version limit and insert py36 and try see can it work but you gonna have to install py36 supported ML libraries (they will be old versions as well) and try it. 

I hope that answer your question :) 
Thank you.

**Comment by onuralpszr** [comment]
I assume that you have an answer. So for that reason I am closing the issue, If you need any other help please let us know. 

Thank you.
