### ISSUE TITLE
Make `InferenceSlicer` compatible with segmentation models 

### ISSUE THREAD

**Issue by mario-dg** [roboflow/supervision#368]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

The problem probably originates in the Detections class, where merging a list of Detections with masks predicted from a YOLOv8 segmentation model might fail to merge.
The step of merging the predicted masks [code-snippet](https://github.com/roboflow/supervision/blob/fa6238dbc4d9cddfc029c4c2cdf1c553dbd6d37a/supervision/detection/core.py#L632) can fail, when the final slices in the row and column dimensions are smaller than the specified slice dimension.

In addition, when calling [move_detections](https://github.com/roboflow/supervision/blob/fa6238dbc4d9cddfc029c4c2cdf1c553dbd6d37a/supervision/detection/tools/inference_slicer.py#L103) only the bounding boxes are considered.
It would be nice to maybe have a contours attribute in the Detections class, that additionally stores a list of contours for each mask, which then can be correctly moved according to the offset.
 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
@mario-dg  do you have small code or collab for trigger it ?

**Comment by mario-dg** [comment]
Is there any plan to further looking into correctly retrieving segmentation results from the InferenceSlicer?

If somebody can point me to an idea or an entry, I could work on a PR.

**Comment by hardikdava** [comment]
@SkalskiP yes, Slicer only works with bounding box for now.

**Comment by SkalskiP** [comment]
Okey. In that case, let me update the title and tag of this issue. I'll convert it from a bug report into a feature request.

**Comment by SkalskiP** [comment]
Hi everyone 👋🏻 We are already tracking this issue in: https://github.com/roboflow/supervision/issues/678. I'm marking this issue as a duplicate. For your information, we plan to tackle this feature in the first quarter of 2024.
