### ISSUE TITLE
Multiple Annotation Type Option

### ISSUE THREAD

**Issue by sanaullah-code** [roboflow/supervision#370]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Currently Supervision can only draw rectangles as an annotation. It would be cool if we add option for drawing circle, triangle, polygon etc.
![aa52476a-ead3-4661-934c-29f2f1d6f6a2](https://github.com/roboflow/supervision/assets/76161635/de4997f9-2316-446d-bb77-5ad9b8ece9ea)
![e3baae74-6f0e-4c2d-9064-9039a8925a90](https://github.com/roboflow/supervision/assets/76161635/6c3dd304-7c32-4f67-9947-19934a3445c2)
![44357787-38e6-4244-972a-dc2a1e74dfa0](https://github.com/roboflow/supervision/assets/76161635/e297945e-d601-4b73-aa02-7231f804b660)

### Use case

Sometime Rectangle makes annotations looks messy. So need other means for annotations

### Additional

I am new to contributions so be humble with me ! haha

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by sanaullah-code** [comment]
I would love to start it or you can say I have already worked on it however need some suggestion from you like currently we have **BoxAnnotator** Class which have the annotate method/function so, we can do it in two ways 

1- A whole new **TriangleAnnotator** class same as the **BoxAnnotator**


2- We can give parameter in the **annotate** method e.g annotation_type and it might be like circle triangle etc

`def annotate(
        self,
        scene: np.ndarray,
        detections: Detections,
        labels: Optional[List[str]] = None,
        skip_label: bool = False,
        annotation_type: str = "rectangle",  # Default to drawing rectangles

    ) -> np.ndarray:
       
        font = cv2.FONT_HERSHEY_SIMPLEX
        for i in range(len(detections)):
            x1, y1, x2, y2 = detections.xyxy[i].astype(int)
            class_id = (
                detections.class_id[i] if detections.class_id is not None else None
            )
            idx = class_id if class_id is not None else i
            color = (
                self.color.by_idx(idx)
                if isinstance(self.color, ColorPalette)
                else self.color
            )
            if annotation_type == "rectangle":
                # Draw rectangles
                cv2.rectangle(
                    img=scene,
                    pt1=(x1, y1),
                    pt2=(x2, y2),
                    color=color.as_bgr(),
                    thickness=self.thickness,
                )
            elif annotation_type == "pointer":
                # Draw pointers (dots)
                cv2.circle(
                    img=scene,
                    center=((x1 + x2) // 2, (y1 + y2) // 2),  # Center of the box
                    radius=self.pointer_radius,
                    color=color.as_bgr(),
                    thickness=cv2.FILLED,
                )
            elif annotation_type == "circle":
                # Draw circles
                center_x = (x1 + x2) // 2
                center_y = (y1 + y2) // 2
                radius = max((x2 - x1) // 2, (y2 - y1) // 2)
                cv2.circle(
                    img=scene,
                    center=(center_x, center_y),
                    radius=radius,
                    color=color.as_bgr(),
                    thickness=self.thickness,
                )
            if skip_label:
                continue

            text = (
                f"{class_id}"
                if (labels is None or len(detections) != len(labels))
                else labels[i]
            )

            text_width, text_height = cv2.getTextSize(
                text=text,
                fontFace=font,
                fontScale=self.text_scale,
                thickness=self.text_thickness,
            )[0]

            text_x = x1 + self.text_padding
            text_y = y1 - self.text_padding

            text_background_x1 = x1
            text_background_y1 = y1 - 2 * self.text_padding - text_height

            text_background_x2 = x1 + 2 * self.text_padding + text_width
            text_background_y2 = y1

            cv2.rectangle(
                img=scene,
                pt1=(text_background_x1, text_background_y1),
                pt2=(text_background_x2, text_background_y2),
                color=color.as_bgr(),
                thickness=cv2.FILLED,
            )
            cv2.putText(
                img=scene,
                text=text,
                org=(text_x, text_y),
                fontFace=font,
                fontScale=self.text_scale,
                color=self.text_color.as_rgb(),
                thickness=self.text_thickness,
                lineType=cv2.LINE_AA,
            )
        return scene`

just tell me which one you would prefer and hope you enjoyed your vacations

**Comment by onuralpszr** [comment]
@sanaullah-code  

https://github.com/roboflow/supervision/pull/372
https://github.com/roboflow/supervision/pull/170 (this is big one) 

we are having a huge change for annotators, first let's merge this two, then we can work on others

**Comment by SkalskiP** [comment]
Hi @sanaullah-code 👋🏻 Please create the whole `TriangleAnnotator` class.

**Comment by SkalskiP** [comment]
Hi @onuralpszr and @sanaullah-code, I created separate issues for different annotators:
- https://github.com/roboflow/supervision/issues/397
- https://github.com/roboflow/supervision/issues/396
- https://github.com/roboflow/supervision/issues/395

I'm closing this issue. Let's move the conversation to specific issues.
