### ISSUE TITLE
Update Supervision Quickstart and provide full end-to-end example along with explanation 

### ISSUE THREAD

**Issue by hongbo-miao** [roboflow/supervision#376]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Currently, the quickstart does not have a complete code which is not friendly. https://supervision.roboflow.com/quickstart/detections/

```py
import supervision as sv

detections = sv.Detections(...)
detections = detections[detections.class_id == 0]
```

It would be great to provide a complete code. Thanks! ☺️

**Comment by onuralpszr** [comment]
Hello, Changing document in a better way already in our list. But certain changes are coming so after those changes we will going to change docs as well.

**Comment by SkalskiP** [comment]
Hi @hongbo-miao 👋🏻! As @onuralpszr said, one of our main goals for the next weeks and months is to expand our documentation. In the meantime, please look at the catalog with [examples](https://github.com/roboflow/supervision/tree/develop/examples), and don't hesitate to ask questions in the [discussions](https://github.com/roboflow/supervision/discussions) section.

**Comment by SkalskiP** [comment]
Hi @hongbo-miao 👋🏻 With the latest release, we added the `🚀 Quickstart` section to the main docs page. Those links lead to end-to-end examples showing how to do basic stuff (like tracking and annotating) with supervision.

![Screenshot 2024-01-26 at 10 09 36](https://github.com/roboflow/supervision/assets/26109316/464a7b7e-cc6a-431b-b11c-92bd1cce1809)
