### ISSUE TITLE
VideoSink Fourcc changeable

### ISSUE THREAD

**Issue by cawilchesp** [roboflow/supervision#380]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

When using sv.VideoSink, there's no way to change `fourcc`:

`self.__fourcc = cv2.VideoWriter_fourcc(*"mp4v")`

I tried forcing H264 this way, without success:

```
with sv.VideoSink(target_path=target, video_info=video_info) as sink:
        for frame in tqdm(frame_generator, total=video_info.total_frames):
            sink.__fourcc = cv2.VideoWriter_fourcc(*"H264")
            sink.write_frame(frame=frame)
```

Perhaps, it could be implemented this way:

```
def __init__(self, target_path: str, video_info: VideoInfo, fourcc: str = "mp4v"):
        self.target_path = target_path
        self.video_info = video_info
        self.__fourcc = cv2.VideoWriter_fourcc(*fourcc)
        self.__writer = None
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @cawilchesp 👋🏻 Four are right, we should make it customizable. I see @Killua7362 has already opened a PR adding such a possibility. Stay tuned!

**Comment by Killua7362** [comment]
Hello @SkalskiP I created the pull request for this, But I wanted to ask if the codec entered by user is wrong should we default it to mp4v or should we let user change it after showing the error

**Comment by SkalskiP** [comment]
@Killua7362 Yup, I was having the same dilemma, but I think defaulting to `mp4v` is okey for now. Code is in `develop` for now, so we can still do some updates.

**Comment by Killua7362** [comment]
> @Killua7362 Yup, I was having the same dilemma, but I think defaulting to `mp4v` is okey for now. Code is in `develop` for now, so we can still do some updates. 

That sounds good!
