### ISSUE TITLE
Update `sv.Detections.from_roboflow` and remove `class_list` requirement

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#394]
### Description

After the recent [roboflow/inference](https://github.com/roboflow/inference) update, `class_id` is returned as part of the response. 

```python
result = {
    "predictions": [
        {
            "x": 0.5,
            "y": 0.5,
            "width": 0.2,
            "height": 0.3,
            "class": "person",
            "class_id": 0,
            "confidence": 0.9
        },
        # ... more predictions ...
    ]
}
```

As a result, we no longer need to ask users to provide `class_list` to map `class` value to `class_id`. We can retrieve this value directly from the response. We can simplify the [sv.Detections.from_roboflow](https://supervision.roboflow.com/detection/core/#supervision.detection.core.Detections.from_roboflow) API and remove extra argument.

**Comment by akashAD98** [comment]
@SkalskiP i did few changes let me know if i need to do anything else
