### ISSUE TITLE
Create `sv.BlurAnnotator`

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#395]
### Description

Supervision is expanding its range of [annotators](https://supervision.roboflow.com/annotators/). Following the example of [BoundingBoxAnnotator](https://supervision.roboflow.com/annotators/#boundingboxannotator), [MaskAnnotator](https://supervision.roboflow.com/annotators/#maskannotator), or [EllipseAnnotator](https://supervision.roboflow.com/annotators/#ellipseannotator), create `BlurAnnotator` - whose task is to blur boxes associated with [`sv.Detections`](https://supervision.roboflow.com/detection/core/#detections).

**Comment by hardikdava** [comment]
@SkalskiP Assign it to me. I can handle this.

**Comment by SkalskiP** [comment]
Hi @hardikdava, if possible, I'd like to leave `hacktoberfest` issues for potential new contributors. I plan to promote them and encourage new people to be involved in the project.

If no one new will pick it, I'm happy for you to implement it.

**Comment by SkalskiP** [comment]
Hi, @Rajarshi-Misra 👋🏻 Absolutely! Do you need any help?

**Comment by Rajarshi-Misra** [comment]
I'll let you know if I need help. Thanks for asking

**Comment by SkalskiP** [comment]
Thanks for taking the time to play with `supervision`!

**Comment by Rajarshi-Misra** [comment]
Hi
I've written a class to resolve for burring. Can you suggest anything regarding how the testing can be done(if there is any script for that)?
![image](https://github.com/roboflow/supervision/assets/72802594/f0dd5e77-c367-4764-929c-9c5dbf76075b)
![image](https://github.com/roboflow/supervision/assets/72802594/1bf46002-4a3f-4906-b38b-0eda7d1e8470)

**Comment by hardikdava** [comment]
@Rajarshi-Misra You can create a draft PR and we can communicate over there. It makes more sense. Looking forward to your PR :)

**Comment by Rajarshi-Misra** [comment]
I've made a draft PR.

**Comment by SkalskiP** [comment]
Hi @Rajarshi-Misra, I already left 2 comments under your PR. I also created Google Colab for debugging ;) Awesome work!
