### ISSUE TITLE
Create `sv.DotMarkerAnnotator`

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#396]
### Description

Supervision is expanding its range of [annotators](https://supervision.roboflow.com/annotators/). Following the example of [BoundingBoxAnnotator](https://supervision.roboflow.com/annotators/#boundingboxannotator), [MaskAnnotator](https://supervision.roboflow.com/annotators/#maskannotator), or [EllipseAnnotator](https://supervision.roboflow.com/annotators/#ellipseannotator), create `DotMarkerAnnotator` - whose task is to mark objects related to [`sv.Detections`](https://supervision.roboflow.com/detection/core/#detections) with dots.

Like other annotators, it should allow you to choose a color palette and a color mapping strategy - `index`, `class`, `track`. It should also allow you to control the position of the dot in relation to the box using [`sv.Position`](https://supervision.roboflow.com/geometry/core/#position).

### Pseudocode

```python
class DotMarkerAnnotator(BaseAnnotator):

    def __init__(
        self,
        color: Union[Color, ColorPalette] = ColorPalette.default(),
        radious: int = 4,
        position: Position = Position.CENTER,
        color_map: str = "class",
    ):
        pass

    def annotate(
        self,
        scene: np.ndarray,
        detections: Detections,
    ) -> np.ndarray:
        pass
```

### Documentation

Upenij that the new annotator is well documented. Read more in our [contributor guidelines](https://github.com/roboflow/supervision/blob/develop/CONTRIBUTING.md).

**Comment by SkalskiP** [comment]
@PolliArthur and @ugly-custard, would any of you be interested in this issue? It is very similar to https://github.com/roboflow/supervision/issues/397, and no one has been assigned to this one yet.

**Comment by PolliArthur** [comment]
> @PolliArthur and @ugly-custard, would any of you be interested in this issue? It is very similar to #397, and no one has been assigned to this one yet. 

I’m still interested in this issue !

**Comment by SkalskiP** [comment]
@PolliArthur should I assign you?

**Comment by PolliArthur** [comment]
> @PolliArthur should I assign you?

Yessss, I’ll appreciate

**Comment by SkalskiP** [comment]
Done! Let me know if you'll need any help with implementation.

**Comment by PolliArthur** [comment]
> Done! Let me know if you'll need any help with implementation. 

At this moment it's ok! I'll read Documentation to understand better how this will be implemented, if I have any doubt I share here!

Tkssss @SkalskiP 🙌

**Comment by SkalskiP** [comment]
Hi @PolliArthur 👋🏻 How's it going? Need any help?

**Comment by PolliArthur** [comment]
> Hi @PolliArthur 👋🏻 How's it going? Need any help?

Hi @SkalskiP, sorry for the delay, I'll start this weekend!

**Comment by SkalskiP** [comment]
@PolliArthur, no worries! As I said, you have time till the end of October ;) Also, I know you asked... we have Discord: https://discord.gg/RCdPHXCU
