### ISSUE TITLE
Create `sv.TriangleMarkerAnnotator`

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#397]
### Description

Supervision is expanding its range of [annotators](https://supervision.roboflow.com/annotators/). Following the example of [BoundingBoxAnnotator](https://supervision.roboflow.com/annotators/#boundingboxannotator), [MaskAnnotator](https://supervision.roboflow.com/annotators/#maskannotator), or [EllipseAnnotator](https://supervision.roboflow.com/annotators/#ellipseannotator), create `TriangleMarkerAnnotator` - whose task is to mark objects related to [`sv.Detections`](https://supervision.roboflow.com/detection/core/#detections) with triangles.

Like other annotators, it should allow you to choose a color palette and a color mapping strategy - `index`, `class`, `track`. It should also allow you to control the position of the triangle in relation to the box using [`sv.Position`](https://supervision.roboflow.com/geometry/core/#position).

### Pseudocode

```python
class TriangleMarkerAnnotator(BaseAnnotator):

    def __init__(
        self,
        color: Union[Color, ColorPalette] = ColorPalette.default(),
        height: int = 10,
        position: Position = Position.TOP_CENTER,
        color_map: str = "class",
    ):
        pass

    def annotate(
        self,
        scene: np.ndarray,
        detections: Detections,
    ) -> np.ndarray:
        pass
```

### Documentation

Upenij that the new annotator is well documented. Read more in our [contributor guidelines](https://github.com/roboflow/supervision/blob/develop/CONTRIBUTING.md).

**Comment by PolliArthur** [comment]
@SkalskiP I'm interested, please assign it for me <3

**Comment by ugly-custard** [comment]
hello, I'm also interested in this issue
is the triangle supposed to look like one of those rpg games like below?

![annotated](https://github.com/roboflow/supervision/assets/63342464/b488ae04-c69a-46c6-b568-296ffc53a478)

**Comment by onuralpszr** [comment]
> hello, I'm also interested in this issue is the triangle supposed to look like one of those rpg games like below?
> 
> ![annotated](https://user-images.githubusercontent.com/63342464/272361115-b488ae04-c69a-46c6-b568-296ffc53a478.png)

Triangle is already under work :) sorry

**Comment by PolliArthur** [comment]
> > hello, I'm also interested in this issue is the triangle supposed to look like one of those rpg games like below?
> > ![annotated](https://user-images.githubusercontent.com/63342464/272361115-b488ae04-c69a-46c6-b568-296ffc53a478.png)
> 
> Triangle is already under work :) sorry

So why this is issue is with hacktoberfest label and still open? 

In cases of detecting people, it would be interesting for the triangle to be centered with the person's head, but I didn't understand if MarkerAnnotator is used to annotate or to draw predictions, depending on the answer, what I said doesn't make sense

**Comment by onuralpszr** [comment]
> So why this is issue is with hacktoberfest label and still open?
> 

it is open because PR still going on ? 

https://github.com/roboflow/supervision/issues/397

Also related comment : https://github.com/roboflow/supervision/issues/370#issuecomment-1744856519

**Comment by ugly-custard** [comment]
> Triangle is already under work :) sorry

ah okay, no one was assigned for this issue so I asked :)

**Comment by PolliArthur** [comment]
i see, but doesn't make sense for me, this issue was open 6 hours go, whereas other issue was open 2 weeks ago....

**Comment by SkalskiP** [comment]
Hi, @PolliArthur and @ugly-custard 👋🏻 I'm sorry for the confusion. It is all my fault. 

@sanaullah-code started to work on the implementation, but he was not active in this issue, and I couldn't assign him directly. I'm genuinely sorry I wasted your time.

@PolliArthur and @ugly-custard, would any of you be interested in https://github.com/roboflow/supervision/issues/396? It is very similar but not assigned yet.

**Comment by SkalskiP** [comment]
@DanRHowarth sure thing! Feel free to let me know if you need any help. Keep in mind that there was already one PR submitted: https://github.com/roboflow/supervision/pull/385. But we lost contact with the collaborator. :/ Still, there is some value there.

**Comment by DanRHowarth** [comment]
> @DanRHowarth sure thing! Feel free to let me know if you need any help. Keep in mind that there was already one PR submitted: #385. But we lost contact with the collaborator. :/ Still, there is some value there.

Thanks! There's a bit of a learning curve for me but will crack on and see how far I can get, will let you know if there are any issues

**Comment by SkalskiP** [comment]
> There's a bit of a learning curve for me but will crack on and see how far I can get

That is usually the best strategy!

**Comment by kapter** [comment]
Some thoughts:
**KKNDAnnotator** 
line in white box is confidence, red if conf lower than .50
<img width="526" alt="2023-10-10 в 01 58 37" src="https://github.com/roboflow/supervision/assets/6329901/d97d9039-711c-4994-8df1-b5c1d1323ad3">
**ImageAnnotator**
image above head (default sim's gem)
![image](https://github.com/roboflow/supervision/assets/6329901/6b0ea345-bb22-4c3d-9e67-6a91371f852e)

**Comment by SkalskiP** [comment]
The creativity you bring to this project 🙌🏻 want to build it? I could create a tasks for other contributors as well. I know you mentioned heat map annotator on Twitter/X.

**Comment by kapter** [comment]
Сreate tasks pls. I will concentrate on heat map. Tnx.

**Comment by SkalskiP** [comment]
@kapter tasks created:
- https://github.com/roboflow/supervision/issues/459
- https://github.com/roboflow/supervision/issues/460

**Comment by kapter** [comment]
result of heat map 

https://github.com/roboflow/supervision/assets/6329901/396f7b85-6ace-403a-b18d-9ab0d8ff1013

**Comment by DanRHowarth** [comment]
Hi @SkalskiP, quick update: had a bit of set-up pain but I've got things working locally have dug into the existing triangle annotator code and got that working too. Probably won't be able to do much on the weekend but will pick this Monday. Let me know if there are any time issues to get this done sooner. Cheers :)
