### ISSUE TITLE
Create HF 🤗 space to showcase Supervision Annotators

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#398]
### Description

Supervision is expanding its range of [annotators](https://supervision.roboflow.com/annotators/). Create an HF space 🤗 allowing users to upload a photo and use checkboxes to select the combination of annotators they want to use. The Gradio app would fire up a model for detection/segmentation (for example YOLOv8) and annotate the results.

The goal is to show the flexibility of annotators and how they can be combined with each other.

**Comment by fdloopes** [comment]
I'm interested in working on a solution! 

I just have a question as to what an HF space would be?

**Comment by SkalskiP** [comment]
You ask a general question: What is HF space? Or a more specific one: what we would like to include there?

**Comment by jayaBalaR** [comment]
@fdloopes , basically  HF Spaces (huggingFace spaces) are git repositories to build application code for Machine learning demos. Visit [hf](https://huggingface.co/)] create an account , and then click on new space, provide the details on the page, select Gradio as the SDK and make it public. Then you can write code in app.py and define dependencies in requirements.txt and once its checked in to github it will hot deeply the code and app will run based on your changes in the app.py.  I hope this overview helps you

**Comment by SkalskiP** [comment]
@jayaBalaR, do you need any help from our side to get started?

**Comment by fdloopes** [comment]
@jayaBalaR Cool, thanks for clearing up my question. I really didn't know about the platform, very interesting. I'll follow the steps you mentioned and take a look at the HuggingFace spaces. To make it easier for us to communicate about the task, is there any other channel we can use? Linkedin doesn't allow me to send you direct messages. :(

**Comment by jayaBalaR** [comment]
@SkalskiP , I am going through the PR description above and will come up with my understanding and ask questions here in this thread. @fdloopes , I am not sure about any other channels, yes I don't have Premium account on Linkedin that's the reason. If there is a discord channel or a slack channel we can communicate there

**Comment by jayaBalaR** [comment]
@SkalskiP , The following is my understanding of this requirement:
1.  Design a Gradio app
2. It should have an upload file and multiselect boxes
3. The multiselect should have all the options of annotators BoundingBox,Mask,Ellipse,BoxCorner,Circle,Label and Trace
4. Also we have the Object detection and segmentation as another two check box group
5. On submit the model should annotate the image and show the results on a tab or result area.

Is this understanding correct?

Please let us know how many annotators we need to add to our Gradio app demo. Also let us know whether its only a demo for detection and segmentation or even for labelling and classification also.

**Comment by SkalskiP** [comment]
> The multi-select should have all the options of annotators BoundingBox, Mask, Ellipse, BoxCorner, Circle, Label and Trace

`Trace` works only with video. You won't see any trace for a single frame. So we can skip it. As for the rest you are right. `multi-select` is a key part here as we want to show how to combo annotators.

> Also we have the Object detection and segmentation as another two check box group

I'd say we can always run segmentation to make the app a bit simpler. [sv.Detections.from_ultralytics](https://supervision.roboflow.com/detection/core/#supervision.detection.core.Detections.from_ultralytics) works with detection and segmentation. If you provide segmentation results we will extract boxes as well. 

> On submit the model should annotate the image and show the results on a tab or result area.

The result image would be awesome! 

Also, I know that Gradio allows to have some "cached examples" we could have 3 of those to allow people to test how it works even without running the app. But I'd say is extra and not mandatory.

**Comment by jayaBalaR** [comment]
@SkalskiP , yes please invite us to the Slack channel so that it's easier to communicate.

**Comment by fdloopes** [comment]
@SkalskiP and @jayaBalaR I followed the points discussed, they helped me to better understand the task and the important points.
@SkalskiP Great, having a Slack channel will make it easier for us to talk.

**Comment by SkalskiP** [comment]
@jayaBalaR and @fdloopes I'll need your email addresses ;)

**Comment by fdloopes** [comment]
Sure, fdloopes@gmail.com. Just let me know when you add it so I don't leave my e-mail in public. 😄

**Comment by jayaBalaR** [comment]
> @jayaBalaR and @fdloopes I'll need your email addresses ;)

jayabalambika.r@gmail.com

**Comment by SkalskiP** [comment]
Hi both 👋🏻! I'll invite you now, but I'll need approval from one of our operations managers - she is in the US. So you can expect that invite to go through in a few hours.

**Comment by jayaBalaR** [comment]
> Hi both 👋🏻! I'll invite you now, but I'll need approval from one of our operations managers - she is in the US. So you can expect that invite to go through in a few hours.

Sure np.   I have another query, if we both need to share development work on the same HF space, then would you be creating one for us and add us to the space .

**Comment by jayaBalaR** [comment]
@SkalskiP If slack is going to be difficult for you, we can mail each other or create a group mail with you to clarify the queries, maybe discuss over google meet if that is fine with you

**Comment by SkalskiP** [comment]
> Sure np. I have another query, if we both need to share development work on the same HF space, then would you be creating one for us and add us to the space.

Yeah, it would make sense, for me or Roboflow to be the owner of that HF space. You can work on building the Gradio app. In the meantime, I'll try to resolve that technicality. 

> If slack is going to be difficult for you, we can mail each other or create a group mail with you to clarify the queries, maybe discuss over google meet if that is fine with you

Don't worry about it. I'm trying to build a community here. The community needs to be able to talk. :)

**Comment by jayaBalaR** [comment]
> > Sure np. I have another query, if we both need to share development work on the same HF space, then would you be creating one for us and add us to the space.
> 
> Yeah, it would make sense, for me or Roboflow to be the owner of that HF space. You can work on building the Gradio app. In the meantime, I'll try to resolve that technicality.
> 
> > If slack is going to be difficult for you, we can mail each other or create a group mail with you to clarify the queries, maybe discuss over google meet if that is fine with you
> 
> Don't worry about it. I'm trying to build a community here. The community needs to be able to talk. :)

Sure thank you.

**Comment by Milindk1** [comment]
hey @SkalskiP , I've gone through the problem statement and i'd be happy to contribute to the solution. I have some prior experience with HF(still learning) and would love to help in building the space. I'd love to join the team.

**Comment by SkalskiP** [comment]
Hi @Milindk1 👋🏻 welcome to `supervison`! We already have two people on this task. But maybe you'd be interested in different Hacktoberfest task? We could also think about other HF space you could build for us.
