### ISSUE TITLE
sv.MaskAnnotator not working

### ISSUE THREAD

**Issue by cyborgdennett** [roboflow/supervision#415]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Hi, there is an issue with the sv.MaskAnnotator.
![image](https://github.com/roboflow/supervision/assets/40475862/7da82b10-2f13-40fe-a3cd-6d609fff858f)
This notebook used to work a few weeks ago, this is the official one from RoboFlow.
From notebook: https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-segment-anything-with-sam.ipynb#scrollTo=qkNDZqBEj5Cr

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
@cyborgdennett please do this

`mask_annotator = sv.MaskAnnotator(color_map = "index")`  it should work. Default color map is "class" but for sam it doesn't have "class_id" so you need to use "index"

**Comment by cyborgdennett** [comment]
Thank you, yes this is a broken since this commit: https://github.com/roboflow/supervision/commit/d7a5624d602be04042b698ca532f359448ae1a36

**Comment by SkalskiP** [comment]
@onuralpszr I'll check if it works, and if so, patch the notebook. @cyborgdennett, the API has changed a bit. Please give me a sec to take a look.

**Comment by onuralpszr** [comment]
@SkalskiP  https://colab.research.google.com/drive/1ScAyh8jljqPJgvotaLSTClOD_E-TtzhE?usp=sharing

**Comment by SkalskiP** [comment]
@cyborgdennett I just fixed https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-segment-anything-with-sam.ipynb. Could you take a look?

**Comment by cyborgdennett** [comment]
Yes works gj
