### ISSUE TITLE
Make `sv.TraceAnnotator` work with different `sv.Position` values

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#420]
### Description

Currently, [`sv.TraceAnnotator`](https://supervision.roboflow.com/annotators/#supervision.annotators.core.TraceAnnotator) allows you to specify the `position` argument. It allows you to choose which point belonging to the bounding box should be the source of the trace. Regardless of the selected value of `sv.Position` the trace always comes out from `BOTTOM_CENTER`. The implementation should be corrected so that the `position` argument is respected.

https://github.com/roboflow/supervision/assets/26109316/243de7f3-1093-4d49-9c2e-5faee9038b7f

**Comment by sitamgithub-MSIT** [comment]
@SkalskiP I want to work on this issue. Can you assign me this?

**Comment by SkalskiP** [comment]
Hi, @sitamgithub-MSIT 👋🏻! Awesome! I assigned you to the issue. Let me know if you need any help.
