### ISSUE TITLE
ValueError: Could not resolve color by class becauseDetections do not have class_id

### ISSUE THREAD

**Issue by bb6698** [roboflow/supervision#427]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

Hi!! I'm using supervision for it can view the result of segment-anything following tutorial: https://blog.roboflow.com/how-to-use-segment-anything-model-sam/ 

The problem is when I want to draw masks on an image using provided detections with Segment-Anything (SAM). 

The error is: 

  annotated_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)
  File "/home/oem/.local/lib/python3.8/site-packages/supervision/annotators/core.py", line 143, in annotate
    idx = resolve_color_idx(
  File "/home/oem/.local/lib/python3.8/site-packages/supervision/annotators/utils.py", line 34, in resolve_color_idx
    raise ValueError(
ValueError: Could not resolve color by class becauseDetections do not have class_id

### Environment

- Supervision: 0.15.0
- Python: 3.8
- Ubuntu: 20.04
- python-opencv: 4.8.1.78 
- Segment-Anything 

### Minimal Reproducible Example

import cv2
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator, SamPredictor
import supervision as sv
import time

IMAGE_PATH = "image1.jpg"

if __name__ == '__main__':
    sam_checkpoint = "sam_vit_h_4b8939.pth"
    model_type = "default"
    device = "cuda"

    sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
    sam.to(device=device)

    mask_generator = SamAutomaticMaskGenerator(sam)

    image_bgr = cv2.imread(IMAGE_PATH)
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)

    
    result = mask_generator.generate(image_rgb)
    
    mask_annotator = sv.MaskAnnotator()
    detections = sv.Detections.from_sam(result)
    annotated_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
Hello, please do this

`mask_annotator = sv.MaskAnnotator(color_map = "index")`  should work. Default color map is "class" but for sam it doesn't have "class_id" so you need to use "index"

**Comment by SkalskiP** [comment]
Hi, @bb6698 👋🏻! Please use the tip provided by @onuralpszr. I just updated our blog post to use the latest API. I'm closing the issue, but feel free to reopen it if you will face more issues.

**Comment by bb6698** [comment]
Thanks!! I probe mask_annotator = sv.MaskAnnotator(color_map = "index")  and now it works. 

Cheers :)
