### ISSUE TITLE
Fix `sv.ByteTrack.tracker_id` return value when `sv.Detections` is empty

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#429]
### Bug

When `sv.Detections` is empty (`len(detections) == 0`) `sv.ByteTrack` returns `tracker_id` equal `None`. Correct that behavior, make it more consistent, and return `np.array([], dtype=int)`.

### Fix

Add `else` statement here: https://github.com/roboflow/supervision/blob/89c1b63979d43f8ed651a9701ca8333034d0bc07/supervision/tracker/byte_tracker/core.py#L239

**Comment by akashpambhar** [comment]
Working on it
