### ISSUE TITLE
Update `sv.Detections.from_roboflow` to extract `tracker_id` values from inference response

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#434]
### Description

[Inference](https://github.com/roboflow/inference) now makes it possible to track detected objects. However, our `sv.Detections.from_roboflow` is not extracting `tracker_id` values from the inference response.

We need to update `sv.Detections.from_roboflow` and `process_roboflow_result` to make sure we are getting `tracker_id` from the response JSON and saving them into `sv.Detections.tracker_id` `np.array`.

Here are a few response examples. We need to be sure we can handle all of those cases.

- empty

  ```
  {'visualization': None, 'frame_id': 54, 'time': None, 'image': {'width': 1920, 'height': 1080}, 'predictions': []} 
  ```

- non-empty without `tracker_id` key

  ```
  {'visualization': None, 'frame_id': 58, 'time': None, 'image': {'width': 1920, 'height': 1080}, 'predictions': [{'x': 942.0, 'y': 348.0, 'width': 58.0, 'height': 88.0, 'confidence': 0.805433988
  571167, 'class': '7D', 'class_confidence': None, 'class_id': 25}]}  
  ```

- non-empty with `tracker_id` key and `None` value

  ```
  {'visualization': None, 'frame_id': 58, 'time': None, 'image': {'width': 1920, 'height': 1080}, 'predictions': [{'x': 942.0, 'y': 348.0, 'width': 58.0, 'height': 88.0, 'confidence': 0.805433988
  571167, 'class': '7D', 'class_confidence': None, 'class_id': 25, 'tracker_id': None}]}   
  ```

- non-empty with `tracker_id` key and not `None` value

  ```
  {'visualization': None, 'frame_id': 68, 'time': None, 'image': {'width': 1920, 'height': 1080}, 'predictions': [{'x': 826.0, 'y': 353.0, 'width': 58.0, 'height': 106.0, 'confidence': 0.8455425500869751, 'class': '10D', 'class_confidence': None, 'class_id': 1, 'tracker_id': 5}]}
  ```

**Comment by SandeepaDevin** [comment]
Is the tracker_id need to extracted in a similar way how ckadd_id has been ?

**Comment by SkalskiP** [comment]
Yes, but like you can see `class_id` is always provided and not `None` and `tracker_id` is optional. So there are some sattle differences.

**Comment by Rajarshi-Misra** [comment]
@SkalskiP can you assign this issue issue to me? I'd like to contribute to this

**Comment by SkalskiP** [comment]
@SandeepaDevin and @Rajarshi-Misra, it looks like we already have a PR for this issue: https://github.com/roboflow/supervision/pull/437 :/

**Comment by hanbangzou** [comment]
Hi 

I have supversion 0.17.0 installed. 

In my data, I have track ids as None. When I try to run the video inference code, Ive got the following error: 

File ~\anaconda3\envs\py38\lib\site-packages\supervision\utils\video.py:203, in process_video(source_path, target_path, callback)
    199 with VideoSink(target_path=target_path, video_info=source_video_info) as sink:
    200     for index, frame in enumerate(
    201         get_video_frames_generator(source_path=source_path)
    202     ):
--> 203         result_frame = callback(frame, index)
    204         sink.write_frame(frame=result_frame)

Cell In[20], line 16, in annotate_frame(frame, frame_number)
     10 detection_data = results["protist"][index]
     12 roboflow_format = {
     13     "predictions": detection_data['predictions'],
     14     "image": {"width": frame.shape[1], "height": frame.shape[0]}
     15 }
---> 16 detections = sv.Detections.from_roboflow(roboflow_format)
     17 detections = tracker.update_with_detections(detections)
     18 labels = [pred['class'] for pred in detection_data['predictions']]

File ~\anaconda3\envs\py38\lib\site-packages\supervision\detection\core.py:431, in Detections.from_roboflow(cls, roboflow_result)
    395 @classmethod
    396 def from_roboflow(cls, roboflow_result: dict) -> Detections:
    397     """
    398     Create a Detections object from the [Roboflow](https://roboflow.com/)
    399         API inference result.
   (...)
    429         ```
    430     """
--> 431     xyxy, confidence, class_id, masks, trackers = process_roboflow_result(
    432         roboflow_result=roboflow_result
    433     )
    435     if np.asarray(xyxy).shape[0] == 0:
    436         return cls.empty()

File ~\anaconda3\envs\py38\lib\site-packages\supervision\detection\utils.py:379, in process_roboflow_result(roboflow_result)
    377 class_id = np.array(class_id).astype(int) if len(class_id) > 0 else np.empty(0)
    378 masks = np.array(masks, dtype=bool) if len(masks) > 0 else None
--> 379 tracker_id = np.array(tracker_ids).astype(int) if len(tracker_ids) > 0 else None
    381 return xyxy, confidence, class_id, masks, tracker_id

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

 {'visualization': None,
  'frame_id': None,
  'time': 0.14675871800864115,
  'image': {'width': 804, 'height': 804},
  'predictions': [{'x': 380.0,
    'y': 426.0,
    'width': 94.0,
    'height': 126.0,
    'confidence': 0.8908122777938843,
    'class': 'hemimastix',
    'class_confidence': None,
    'class_id': 0,
    'tracker_id': None}]},

**Comment by hanbangzou** [comment]
> Hi
> 
> I have supversion 0.17.0 installed.
> 
> In my data, I have track ids as None. When I try to run the video inference code, Ive got the following error:
> 
> File ~\anaconda3\envs\py38\lib\site-packages\supervision\utils\video.py:203, in process_video(source_path, target_path, callback) 199 with VideoSink(target_path=target_path, video_info=source_video_info) as sink: 200 for index, frame in enumerate( 201 get_video_frames_generator(source_path=source_path) 202 ): --> 203 result_frame = callback(frame, index) 204 sink.write_frame(frame=result_frame)
> 
> Cell In[20], line 16, in annotate_frame(frame, frame_number) 10 detection_data = results["protist"][index] 12 roboflow_format = { 13 "predictions": detection_data['predictions'], 14 "image": {"width": frame.shape[1], "height": frame.shape[0]} 15 } ---> 16 detections = sv.Detections.from_roboflow(roboflow_format) 17 detections = tracker.update_with_detections(detections) 18 labels = [pred['class'] for pred in detection_data['predictions']]
> 
> File ~\anaconda3\envs\py38\lib\site-packages\supervision\detection\core.py:431, in Detections.from_roboflow(cls, roboflow_result) 395 @classmethod 396 def from_roboflow(cls, roboflow_result: dict) -> Detections: 397 """ 398 Create a Detections object from the [Roboflow](https://roboflow.com/) 399 API inference result. (...) 429 ``` 430 """ --> 431 xyxy, confidence, class_id, masks, trackers = process_roboflow_result( 432 roboflow_result=roboflow_result 433 ) 435 if np.asarray(xyxy).shape[0] == 0: 436 return cls.empty()
> 
> File ~\anaconda3\envs\py38\lib\site-packages\supervision\detection\utils.py:379, in process_roboflow_result(roboflow_result) 377 class_id = np.array(class_id).astype(int) if len(class_id) > 0 else np.empty(0) 378 masks = np.array(masks, dtype=bool) if len(masks) > 0 else None --> 379 tracker_id = np.array(tracker_ids).astype(int) if len(tracker_ids) > 0 else None 381 return xyxy, confidence, class_id, masks, tracker_id
> 
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> 
> {'visualization': None, 'frame_id': None, 'time': 0.14675871800864115, 'image': {'width': 804, 'height': 804}, 'predictions': [{'x': 380.0, 'y': 426.0, 'width': 94.0, 'height': 126.0, 'confidence': 0.8908122777938843, 'class': 'hemimastix', 'class_confidence': None, 'class_id': 0, 'tracker_id': None}]},

My solution is to remove track ids from the results and it fixs the error. 

 # Remove 'tracker_id' from each prediction
        for prediction in detection_data['predictions']:
            prediction.pop('tracker_id', None)
