### ISSUE TITLE
Create `draw_image` to enable watermarking images and videos  

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#439]
### Description

Create `draw_image` to enable watermarking images and videos. The utility should be located in [`supervision/draw/utils.py`](https://github.com/roboflow/supervision/blob/develop/supervision/draw/utils.py) and allow:
- loading watermark image from the path or as `np.ndarray`
- scaling watermark image
- drawing watermark image on the frame with selected opacity

### Pseudocode

```python
def draw_image(
    scene: np.ndarray, 
    image: Union[str, np.ndarray],
    opacity: float,
    rect: Rect
) -> np.ndarray:
    """
    Draws an image onto a given scene with specified opacity and dimensions.
    
    Args:
        scene (np.ndarray): The background image onto which the image will be drawn.
        image (Union[str, np.ndarray]): The image to be drawn. Can be either a file path or a NumPy array.
        opacity (float): The opacity level of the image to be drawn, ranging from 0.0 to 1.0.
        rect (Rect): A Rect object specifying the dimensions and position where the image will be drawn.
        
    Returns:
        np.ndarray: The scene with the image drawn onto it.
        
    Example:
        >>> scene = np.zeros((400, 400, 3), dtype=np.uint8)
        >>> image_path = "path/to/image.jpg"
        >>> opacity = 0.5
        >>> rect = Rect(x=50, y=50, width=200, height=200)
        >>> new_scene = draw_image(scene, image_path, opacity, rect)
    """
    pass
```

### Documentation

Upenij that the new annotator is well documented. Read more in our [contributor guidelines](https://github.com/roboflow/supervision/blob/develop/CONTRIBUTING.md).

**Comment by mario-dg** [comment]
I would like to tackle this small PR :)

**Comment by SkalskiP** [comment]
Hi, 👋🏻 @mario-dg! I just updated the task description to give you a bit more guidelines. You are assigned. 

Feel free to reach out if you have any questions.

**Comment by mario-dg** [comment]
Should I add asserts for checking the existence of the file path and the validity of the rect inside the scene?
Or how do you want me to handle possible issues, since the other draw_ functions don't have any?

**Comment by SkalskiP** [comment]
Hi, @mario-dg 👋🏻! It's nice if the function tells you what to correct when it returns an error.  It would be great if you could handle this as well.

**Comment by mario-dg** [comment]
Great, will do so!

What about transparency in the watermark image?

**Comment by SkalskiP** [comment]
The `opacity` parameter should regulate it. We use this naming convention in other utils we have.

**Comment by mario-dg** [comment]
I meant png images that have a transparent background.
Should the alpha channel in the image be used as a mask to cut out the RGB channels for a correct overlay?

**Comment by SkalskiP** [comment]
Oh... sorry, I misunderstood your question. 
1. We should use full watermark image size as a reference. So, if the input image is PNG, in 100x100 resolution, we should use 100x100 as a reference, even if the non-transparent part would take only 50x50 of the whole image. 
2. It would be awesome to make transparent parts of PNG, be transparent in overlay.

**Comment by mario-dg** [comment]
![opaque_watermark](https://github.com/roboflow/supervision/assets/46304415/9f6885ba-6f31-430c-a923-c077122ffecb)
![transparent_watermark](https://github.com/roboflow/supervision/assets/46304415/297fae52-e775-45df-a368-3edfede0329b)

Does this work for you like this? :)

**Comment by mario-dg** [comment]
Perfect!
I've created the PR, @SkalskiP.
Any feedback is greatly appreciated :)
