### ISSUE TITLE
Create "How to: detect and annotate" docs page

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#441]
### Description

One of our primary goals is to improve the quality of our documentation. Many people say they are a tad overwhelmed by the amount of functionality offered by Supervision and don't know where to start.

- Fill ["How to: detect and annotate"](https://supervision.roboflow.com/how_to/detect_and_annotate/) docs page with instructions. Make sure to cover the topic below:
  - Loading image using OpenCV
  - Loading Ultralytics YOLOv8 model
  - YOLOv8 inference
  - Converting YOLOv8 result to [`sv.Detections`](https://supervision.roboflow.com/detection/core/)
  - Annotating image
  - Different models
- Provide code examples when necessary
- Link to other docs pages when necessary

**Comment by SuryaCreatX** [comment]
Hey, Can you assign me this issue.

**Comment by SkalskiP** [comment]
Hi, @SuryaCreatX 👋🏻! Absolutely! You are assigned. Let me know if you have any questions.

**Comment by SkalskiP** [comment]
Hi @SuryaCreatX 👋🏻! We wanted to have this docs page for `supervision-0.16.0` that is happening tomorrow. @capjamesg took care of this task and created https://github.com/roboflow/supervision/pull/489. Feel free to take another task from our [roadmap](https://github.com/roboflow/supervision/issues). I hope you will understand 🤞🏻 💜
