### ISSUE TITLE
Create "How to: track objects" docs page

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#442]
### Description

One of our primary goals is to improve the quality of our documentation. Many people say they are a tad overwhelmed by the amount of functionality offered by Supervision and don't know where to start.

- Fill ["How to: track objects"](https://supervision.roboflow.com/how_to/track_objects/) docs page with instructions. Make sure to cover the topic below:
  - Plugging [`sv.ByteTrack`](https://supervision.roboflow.com/trackers/#supervision.tracker.byte_tracker.core.ByteTrack) into inference pipeline
  - Using [`sv.LabelAnnoator`](https://supervision.roboflow.com/annotators/#supervision.annotators.core.LabelAnnotator) to display tracker ID
  - Using [`sv.TraceAnnoator`](https://supervision.roboflow.com/annotators/#supervision.annotators.core.TraceAnnotator) to display path of moving objects
- Provide code examples when necessary
- Link to other docs pages when necessary

### Pseudocode

Here's a simple code you can use to get started.

```python
>>> import supervision as sv
>>> from ultralytics import YOLO

>>> model = YOLO(...)
>>> byte_tracker = sv.ByteTrack()
>>> annotator = sv.BoxAnnotator()

>>> def callback(frame: np.ndarray, index: int) -> np.ndarray:
...     results = model(frame)[0]
...     detections = sv.Detections.from_ultralytics(results)
...     detections = byte_tracker.update_with_detections(detections)
...     labels = [
...         f"#{tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
...         for _, _, confidence, class_id, tracker_id
...         in detections
...     ]
...     return annotator.annotate(scene=frame.copy(),
...                               detections=detections, labels=labels)

>>> sv.process_video(
...     source_path='...',
...     target_path='...',
...     callback=callback
... )
```

**Comment by Rajarshi-Misra** [comment]
I'm interested in working on this one. Can you assign this one to me so that I can work a bit more flexibly? @SkalskiP

**Comment by SkalskiP** [comment]
Hi, @Rajarshi-Misra 👋🏻! Sure! Let me know if you need any guidance or assistance.

**Comment by Rajarshi-Misra** [comment]
@SkalskiP I'm working on this as a kind of tutorial. I'll also attach links to my Colab notebook. Should I proceed in that manner?
(For a proper tutorial I'll need about 3-4 days, so just confirming before proceeding)
Also, I really want to contribute more to this codebase. It would be awesome if you can assign any future Hacktoberfest issue to me.

**Comment by Rajarshi-Misra** [comment]
@SkalskiP Thanks for the reply
Also, just one more thing. I'm more interested in contributing to the codebase than just the docs. It would be awesome if you could assign any future issues

**Comment by SkalskiP** [comment]
Hi @Rajarshi-Misra 👋🏻 I'll keep that in mind. Could you give me a bit more info on your background? What do you do at work?

We will have a new wave of thanks coming soon. The problem is that people are picking those tasks 2 minutes after I create them 😆 We have some important tasks but a bit hard. That's why I ask.

**Comment by Rajarshi-Misra** [comment]
I'm an engineering student. Currently, I'm a full-stack development intern at a startup. I've worked on a few projects related to deep learning(my main interest is computer vision). Currently, I'm working on a research project in 3D vision and medical imaging.

**Comment by SkalskiP** [comment]
> The reason I asked you to assign me any new issue was just because I couldn't find a lot of issues unassigned 😅

I can just tell you we originally started with 5 issues for Hacktoberfest. Now we have 18 and it is still not enough. 😅

**Comment by Rajarshi-Misra** [comment]
@SkalskiP I've made a pull request. Please check that out

**Comment by Rajarshi-Misra** [comment]
@SkalskiP @hardikdava Can any one of you please look into the PR?

**Comment by Rajarshi-Misra** [comment]
> > The reason I asked you to assign me any new issue was just because I couldn't find a lot of issues unassigned 😅
> 
> I can just tell you we originally started with 5 issues for Hacktoberfest. Now we have 18 and it is still not enough. 😅

@SkalskiP

**Comment by SkalskiP** [comment]
Closing the issue as [How to Track Object](https://supervision.roboflow.com/how_to/track_objects) docs is already live.
