### ISSUE TITLE
Create sv.Keypoint API

### ISSUE THREAD

**Issue by capjamesg** [roboflow/supervision#452]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

I would love to see a `sv.Keypoint` API that allows manipulating keypoint detections with supervision.

To start, it would be nice to have a `sv.Keypoint` object that contains:

1. Keypoint vectors
2. Confidence levels for each keypoint vector

A `sv.Keypoint.from_ultralytics()` method would be helpful as a starting point; we can add more data loaders later. With a data loader, we can add a `sv.KeypointAnnotator` that lets someone visualize keypoint detections.

Eventually, it would be useful to have a method for calculating the angle between two keypoints, useful for comparing poses ([example implementation in JavaScript](https://github.com/capjamesg/hand-pose-detection/blob/main/pose.html#L79)).

### Use case

We want to make it as easy as possible for people to work with keypoints.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
For annotating, we would have an annotator in `supervision/annotators/core` called `KeypointAnnotator` that looks something like this:

```python
class BoundingBoxAnnotator(BaseAnnotator):
    """
    A class for drawing bounding boxes on an image using provided detections.
    """

    def __init__(
        self,
        color: Union[Color, ColorPalette] = ColorPalette.default(),
        thickness: int = 2,
        color_map: str = "class",
    ):
        """
        Args:
            color (Union[Color, ColorPalette]): The color or color palette to use for
                annotating detections.
            radius (int): Radius of the keypoints.
            color_map (str): Strategy for mapping colors to annotations.
                Options are `index`, `class`, or `track`.
        """
        self.color: Union[Color, ColorPalette] = color
        self.thickness: int = thickness
        self.color_map: ColorMap = ColorMap(color_map)

    def annotate(self, scene: np.ndarray, keypoints: Keypoints) -> np.ndarray:
        """
        Annotates the given scene with bounding boxes based on the provided keypoints.

        Args:
            scene (np.ndarray): The image where bounding boxes will be drawn.
            keypoints (Keypoints): Keypoints to annotate.

        Returns:
            np.ndarray: The annotated image.

        Example:
            # TODO
        """
        # draw circular keypoints on the image at the given locations

        return scene
```

**Comment by capjamesg** [comment]
Notes on data loaders that we should prioritize:

- YOLOv8
- YOLOv7
- MediaPipe

**Comment by SkalskiP** [comment]
@onuralpszr, just for clarity. I removed `tag:hacktoberfest` from this issue. We will handle that issue internally in the core team.

**Comment by onuralpszr** [comment]
> @onuralpszr, just for clarity. I removed `tag:hacktoberfest` from this issue. We will handle that issue internally in the core team. I want people to use `tag:hacktoberfest` to easily search for issues they can pick during hacktoberfest.

Okay no problem.

**Comment by capjamesg** [comment]
Keypoint detection is now supported in Roboflow. With that said, it makes sense to revisit this issue.

It might make sense for keypoints to be part of `sv.Detections` rather than introducing a new API. This is because keypoint detections come with bounding box coordinates that represent the region to which a keypoint prediction relates. With that said, there is a notable drawback: it might be confusing if people see all our data loaders for detections and assume they work with keypoint detection.

At a minimum, we should have a data loader that lets someone process predictions from Roboflow. YOLOv8 support would be great to have, too.

In any case, we should add helper functions for common tasks that one might use with keypoint detection (i.e. calculate the angle between two points).

**Comment by yeldarby** [comment]
You should be able to define a skeleton (point names and which vertices are connected to each other and ideally their colors). I don't think having separate things for Human Pose & Facial Landmarks is needed -- those are just two special cases of a keypoint skeleton.

**Comment by LinasKo** [comment]
Tiny tidbit for the future, as I've done a project with Mediapipe before: using `visibility` is a great starting point for `confidence` as it isn't provided, but there's cases (e.g. Tree Pose in yoga) where well-estimated points are invisible, and clearly visible points are massively mislocated - especially in the `z` coordinate.

**Comment by onuralpszr** [comment]
> Tiny tidbit for the future, as I've done a project with Mediapipe before: using `visibility` is a great starting point for `confidence` as it isn't provided, but there's cases (e.g. Tree Pose in yoga) where well-estimated points are occluded and clearly visible points are massively mislocated - especially the `z` coordinate.

I also used MP and know exactly what you mean by mislocation when face/pose not clearly visible or effected but high level of light makes unrecognizable cases, for first PR I go with xy I will take xyz parts next as well.
