### ISSUE TITLE
Create `sv.PercentageBarAnnotator`

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#459]
### Description

Supervision is expanding its range of [annotators](https://supervision.roboflow.com/annotators/). Following the example of [BoundingBoxAnnotator](https://supervision.roboflow.com/annotators/#boundingboxannotator), [MaskAnnotator](https://supervision.roboflow.com/annotators/#maskannotator), or [EllipseAnnotator](https://supervision.roboflow.com/annotators/#ellipseannotator), create `PercentageBarAnnotator` - whose task is to draw percentage bars related to [`sv.Detections`](https://supervision.roboflow.com/detection/core/#detections). The inspiration for this annotator is, of course, video games.

<img width="526" alt="273726518-d97d9039-711c-4994-8df1-b5c1d1323ad3" src="https://github.com/roboflow/supervision/assets/26109316/af53c037-a9ae-45f1-95d7-87bf90c337bc">

It should also allow you to control the bar's position in relation to the box using [`sv.Position`](https://supervision.roboflow.com/geometry/core/#position). The color of the bar and border should be configurable as well. By default, the bar should visualize `sv.Detections.confidence` value. Bar color should change across `sv.ColorPalette` provided as `color` argument. 

### Pseudocode

```python
class PercentageBarAnnotator(BaseAnnotator):

    def __init__(
        self,
        color: Union[Color, ColorPalette] = ColorPalette.default(),
        border_color: Color = Color.black(),
        position: Position = Position.TOP_CENTER
    ):
        pass

    def annotate(
        self,
        scene: np.ndarray,
        detections: Detections,
    ) -> np.ndarray:
        pass
```

### Documentation

Upenij that the new annotator is well documented. Read more in our [contributor guidelines](https://github.com/roboflow/supervision/blob/develop/CONTRIBUTING.md).

**Comment by jayaBalaR** [comment]
I would like to work on this task.

**Comment by SkalskiP** [comment]
Sure thing!

**Comment by xaristeidou** [comment]
@SkalskiP 

How does that look like?


https://github.com/roboflow/supervision/assets/65918758/4839c788-bf5e-4849-97ef-85614c3afb26

**Comment by xaristeidou** [comment]
https://github.com/roboflow/supervision/assets/65918758/ce5d7a2d-9d8a-4ffe-850d-9c310a49747b

**Comment by xaristeidou** [comment]
@SkalskiP 

How does that look like? 

![Screenshot from 2023-10-13 14-56-55](https://github.com/roboflow/supervision/assets/65918758/a360ba0c-b263-40aa-9300-4f56fb9fad2a)

Find whole video sample in link below:
https://drive.google.com/file/d/14wkO9FVAjxJd8QHVMwknuKhRASwrMPJp/view?usp=drive_link

**Comment by SkalskiP** [comment]
This task was completed in https://github.com/roboflow/supervision/pull/720. Closing the issue.
