### ISSUE TITLE
[IconAnnotator] - mark objects with custom icons / images

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#460]
### Description

Create `IconAnnotator` - whose task is to mark objects related to [`sv.Detections`](https://supervision.roboflow.com/detection/core/#detections) with custom icons.

![273726799-6b0ea345-bb22-4c3d-9e67-6a91371f852e](https://github.com/roboflow/supervision/assets/26109316/2f184480-c424-4724-a494-189d59592d13)

It should also allow you to control the icon position in relation to the box using [`sv.Position`](https://supervision.roboflow.com/geometry/core/#position).

### API

```python
class IconAnnotator(BaseAnnotator):

    def __init__(
        self,
        icon_path: str,
        position: Position = Position.TOP_CENTER
    ):
        pass

    def annotate(
        self,
        scene: np.ndarray,
        detections: Detections,
    ) -> np.ndarray:
        pass
```

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will definitely speed up the review process. Each change must be tested by the reviewer. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by Rajarshi-Misra** [comment]
@SkalskiP I'm interested in working on this one.

**Comment by SkalskiP** [comment]
@Rajarshi-Misra you are assigned!

**Comment by Shishuii** [comment]
@SkalskiP Is this still available ? I would be glad to contribute to this. :)

**Comment by onuralpszr** [comment]
@Shishuii I am re-assigning to you. You can start working on it.

**Comment by Shishuii** [comment]
Hi @onuralpszr , 
Below is the final output of IconAnnotator.
Shall I submit a PR for review?
![final_ouput_v2](https://github.com/roboflow/supervision/assets/22843318/426a70d3-5804-4161-b3c1-90052d13d807)

**Comment by onuralpszr** [comment]
@Shishuii looking nice do please PR let's talk about on PR as well.

**Comment by Shishuii** [comment]
Hi @onuralpszr , 
Please review the PR.
The PR can be tested on this colab link :
https://colab.research.google.com/drive/1rjwO76QwA-W5WhA0Tvy3uSFtmCtbd9rA?usp=sharing

**Comment by dfreilich** [comment]
@SkalskiP I'd like to take this (based on the work in https://github.com/roboflow/supervision/pull/579).

**Comment by SkalskiP** [comment]
Hi @dfreilich 👋🏻 ! I'm very sorry for the late response. I was a bit busy with other duties. I'm looking at your PR now.

**Comment by arpit2167407** [comment]
@SkalskiP I want to contribute for this issue

**Comment by LinasKo** [comment]
Hi @arpit2167407 👋 

We're a bit behind with reviewing user submissions at the moment. As it stands, there's a PR for this already, so I wouldn't encourage new contributions.

**Comment by arpit2167407** [comment]
Ok thanks,

Arpit
