### ISSUE TITLE
Extend `sv.Detections` with `data` field to support custom payload

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#461]
### Description

Add `data: Dict[str, np.ndarray] = field(default_factory=dict)` to `sv.Detections` to support the custom payload. That can be `class_name`, or other detection-related metadata. To ensure full compatibility, the `__post_init__`, `__iter__`, `__eq__`, `merge` and `__getitem__` methods should be updated.

### ⚠️ Disclaimer

Maintaining data consistency is critical. We use `np.ndarray`s to store information: 

- `xyxy` with `(N, 4)` shape
- `mask` with `(N, H, W)` shape
- `confidence` with `(N, )` shape
- `class_id` with `(N, )` shape
- `tracker_id` with `(N, )` shape

Notice that the shape of every `np.ndarray` is dictated by `N` - detections count. When designing `data: Dict[str, np.ndarray]`, we must ensure that every value in that dictionary has `(N, ...)` shape.

**Comment by subhajit20** [comment]
hey @SkalskiP want to work on this.
Can you assign it to me?

**Comment by SkalskiP** [comment]
Yup, @subhajit20 you are assigned! Let me know if you will need any help. That task might be a bit tricky.

**Comment by subhajit20** [comment]
> Yup, @subhajit20 you are assigned! Let me know if you will need any help. That task might be a bit tricky.

can you guide me on how to solve this?

**Comment by hiteshhedwig** [comment]
hi, @SkalskiP can you explain or provide an example. what's problem does this task we are trying to solve? it'd really help in the context of solving it

**Comment by SkalskiP** [comment]
Hi @subhajit20 and @hiteshhedwig 👋🏻! The idea is to make `sv.Detections` more flexible and applicable to more use cases. 

Imagine you want to use supervision in an OCR project. In such projects, it is usually a matter of knowing what text was read and where it was located. You can store text bounding boxes in `sv.Detection.xyxy`, but where do you put associated text? Right now, this cannot be done with `sv.Detections` alone. 

We aim to allow users to store additional information in this example text extracted from the image.

```python
detections = sv.Detections(...)
extracted_text = [...]
detections.store('extracted_text', extracted_text)
```

Of course, OCR is just an example. There is an infinite amount of similar scenarios.

**Comment by beasteers** [comment]
This is the modification I've been using.

The nice thing about this is that you can add arbitrary data the same as you would define `mask` or `confidence`.

```python
detections = Detections(
    xyxy=np.array([...]),
    mask=np.array([...]),
    labels=np.array([...]),
    source=np.array([...]),
)
for xyxy, mask, confidence, class_id, tracker_id, data in detections:
    ...

for d in detections:
    print(d.xyxy, d.label, d.source)
```

```python
import dataclasses
import numpy as np
import supervision as sv


class Detections(sv.Detections):
    def __init__(self, xyxy, mask=None, confidence=None, class_id=None, tracker_id=None, **kw):
        super().__init__(xyxy, mask, confidence, class_id, tracker_id)
        self.__dict__.update(**kw)

    def __get_data(self, index):
        return {
            k: v[index] if isinstance(v, np.ndarray) else v 
            for k, v in self.__dict__.items()
        }

    def __iter__(self):
        for i in range(len(self.xyxy)):
            yield Detection.new(**self.__get_data(i))

    def __getitem__(self, i):
        return Detections(**self.__get_data([i] if isinstance(i, int) else i))
    
    @classmethod
    def merge(cls, detections):
        keys = {k for d in detections for k in d.__dict__}
        keys = {k for k in keys if all(isinstance(d.__dict__.get(k), np.ndarray) for d in detections)}
        return Detections(**{
            k: np.concatenate([getattr(d, k) for d in detections])
            for k in keys
        })


@dataclasses.dataclass
class Detection:
    xyxy: np.ndarray
    mask: np.ndarray|None = None
    confidence: np.ndarray|None = None
    class_id: np.ndarray|None = None
    tracker_id: np.ndarray|None = None
    data: "dict[np.ndarray]" = None

    @classmethod
    def new(cls, **data):
        kw = {f.name: data.pop(f.name) for f in dataclasses.fields(Detection) if f.name in data}
        return cls(data=data, **kw)
    
    def __getattr__(self, key):
        return self.data[key]
    
    def __iter__(self):
        yield from (getattr(self, f.name, None) for f in dataclasses.fields(self))
```

**Comment by SkalskiP** [comment]
Hi, @beasteers 👋🏻 ! I like this idea a lot! Would you be so kind as to create a PR with this change?
