### ISSUE TITLE
Make `sv.LineZone.trigger` return bool `np.ndarray` informing which detections have crossed the line this frame

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#464]
### Description

Currently, [`sv.LineZone.trigger`](https://github.com/roboflow/supervision/blob/5b5e0eb88daec92643834b2284e750ad5a1c7dc6/supervision/detection/line_counter.py#L30) updates `in_count` and `out_count` values but does not return information on which object crossed the line. Unlike [`sv.PolygonZone.trigger`](https://github.com/roboflow/supervision/blob/5b5e0eb88daec92643834b2284e750ad5a1c7dc6/supervision/detection/tools/polygon_zone.py#L45), which returns such information.

Information about who has crossed the line is needed to update `in_count` and `out_count` and is already calculated in the `trigger` method but does not surface. Let's change that.

**Comment by hardikdava** [comment]
Related PR: #264

**Comment by abhishek7kalra** [comment]
Hey, I would love to work on this issue. From what I could understand, all we need is initialise a bool array of size "detections", and checking where the object's state changes (indicating it has crossed the line), and setting it to True, and finally returning the array, just like in the polygon_zone.py

**Comment by SkalskiP** [comment]
Hi @abhishek7kalra 👋🏻! Looks like you got it. 🤞🏻 That's exactly what you have to do.

**Comment by hardikdava** [comment]
Hey @abhishek7kalra, this part is already implemented. Feel free to look at other open issues. Thank you for taking interest in supervision. 


 @SkalskiP please review #264

**Comment by abhishek7kalra** [comment]
No worries. Do let me know @SkalskiP if this needs to be fixed. Thank you @hardikdava for the info.

**Comment by SkalskiP** [comment]
Hi once again, @abhishek7kalra. #264 is doing a lot of other things. I will handle that update separately. Try to focus on returning that numpy array. You can take some inspiration from #264, made by @hardikdava.

**Comment by abhishek7kalra** [comment]
Hi @SkalskiP, I have done the changes as discussed above and have created a PR [here](https://github.com/roboflow/supervision/pull/482)
