### ISSUE TITLE
Make `sv.MaskAnnotator` as fast as annotators in popular detection frameworks

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#472]
### Description

We have done much work recently dedicated to speeding up our [`sv.MaskAnnotator`](https://supervision.roboflow.com/annotators/#supervision.annotators.core.MaskAnnotator).

- https://github.com/roboflow/supervision/issues/417
- https://github.com/roboflow/supervision/pull/426
- https://github.com/roboflow/supervision/pull/431

As a result, we made it 2x faster, but it is still far from what is possible. A comparison of our sv.MaskAnnotator with the segmentation annotator available in popular detection libraries showed that theirs is still 4-5x faster.

Let's analyze their solution and make changes to match their speed.

**Comment by abhishek7kalra** [comment]
Hey @SkalskiP , I was hoping to pick this up next. Will be reviewing the past work you mentioned above. Any insights or approach which I should try first?

**Comment by xenteros** [comment]
@SkalskiP Do you have any dataset to profile the code on?

**Comment by SkalskiP** [comment]
Hi @abhishek7kalra and @xenteros 👋🏻 Take a look here: https://github.com/roboflow/supervision/pull/426#issuecomment-1751006460

I did that profiling using this Google Colab: https://colab.research.google.com/drive/1i07VTrhmML3Z3EgnO3HubQhIM8iYs5RA?usp=sharing

**Comment by abhishek7kalra** [comment]
Hey @SkalskiP , would love to give this issue a try.

**Comment by xenteros** [comment]
@SkalskiP I cut the complexity by a factor of 2. Further improvements will require down scaling and up scaling the image, thus reducing the output precision.
