### ISSUE TITLE
Filter detections by position of bbox coordinates

### ISSUE THREAD

**Issue by yieniggu** [roboflow/supervision#491]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Is there a way to exclude detections that are outside a given area of detection?

Something similar to:

`detections = detections[detections.class_id == 0]`

Currently I have a zone restricted as:
```
  top_start_point = (0, int(height * 0.2))
  top_end_point = (width, int(height * 0.2))
  bot_start_point = (0, int(height * 0.7))
  bot_end_point = (width, int(height * 0.7))

  frame = cv2.line(frame, top_start_point, top_end_point, (0, 255, 0), 4)
  frame = cv2.line(frame, bot_start_point, bot_end_point, (0, 255, 0), 4)
```

I tried something like 

`detections = detections[
        [i for i in detections.xyxy if i[1] < height * 0.7 and i[1] > height * 0.2]
    ]`

But it didn't work

**Comment by SOBAN50** [comment]
@yieniggu There are different possibilities/options for that:

- Exclude detection if even only 1 pixel of detection is outside the `restricted_zone` i.e only include if whole detection box lies inside
- Exclude detection only if 50% (or a given percentage) of detection is outside the `restricted_zone`
- Include detection if even only a very small portion of detection lies inside

![image](https://github.com/roboflow/supervision/assets/53044938/370f84f5-7c63-4de4-8e89-a5c0f816ed92)

**Comment by SkalskiP** [comment]
Hi @yieniggu 👋🏻 Let me convert this question into a discussion and move it into the Q&A section.
