### ISSUE TITLE
`MaskAnnotator` not working

### ISSUE THREAD

**Issue by SOBAN50** [roboflow/supervision#495]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I don't know what might be the issue but the `MaskAnnotator` is not working  on my side.

- I created a new conda env
- installed python 3.10.0
- installed `supervision` and `ultralytics`
- tried to run the jupter notebook `demp.py`
- `BoxAnnotator` runs fine both with and without labels 
![Screenshot 2023-10-18 203537](https://github.com/roboflow/supervision/assets/53044938/236999f0-74ab-40e2-b2e8-22a854322c5a)  

- but when I run `MaskAnnotator`, it returns me the same image without any masks drawn.
![Screenshot 2023-10-18 203602](https://github.com/roboflow/supervision/assets/53044938/79fd651c-3e47-4101-ac9b-0e9dc2dfa295)  

- I checked the `detections` variable and there `mask=None`:
```py
Detections(xyxy=array([[     59.891,      250.41,      647.94,      1272.8]], dtype=float32), mask=None, confidence=array([    0.79679], dtype=float32), class_id=array([16]), tracker_id=None)
```

I don't know if its an `ultralytics` issue or `MaskAnnotator`.
Please enlighten me.

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
Thank you for opening this Issue! What model are you using? `MaskAnnotator` will only work if you are using a segmentation model.

**Comment by SOBAN50** [comment]
@capjamesg doesn't YOLO-NAS provide segmentation?

**Comment by SkalskiP** [comment]
@SOBAN50 I don't think so :/ What model are you using?

**Comment by SOBAN50** [comment]
@SkalskiP I tried both YOLOv8 and YOLOnas ( as in the notebook )

My question only these 2 models have been used in the notebook. If both don't give segmentations, how is this image produced in the notebook?
![image](https://github.com/roboflow/supervision/assets/53044938/73ea75ba-bf15-4538-bb65-9622c2260ff9)

**Comment by SkalskiP** [comment]
YOLOv8 can produce detections. YOLO-NAS can't.

**Comment by SOBAN50** [comment]
@SkalskiP You mean segmentations?

`YOLOv8 can produce *segmentations. YOLO-NAS can't.`

**Comment by SkalskiP** [comment]
Yeah! Sorry I was coding for 15 hours straight when I responded yesterday.

**Comment by SOBAN50** [comment]
I tried both of them. None of them give a mask.

Both have the same structure where mask = None:
```py
Detections(xyxy=array([[a, b, c, d]], dtype=float32), mask=None, confidence=array([x], dtype=float32), class_id=array([y]), tracker_id=None)

**Comment by SkalskiP** [comment]
Hi again, @SOBAN50 👋🏻 I can't comment on code I don't see. I can tell you that code below will draw masks because it displays the result of the segmentation model.

```python
import cv2
from ultralytics import YOLO
import supervision as sv

model = YOLO("yolov8n-seg.pt")
image = cv2.imread("image.jpg")
results = model(image)[0]
detections = sv.Detections.from_ultralytics(results)

mask_annotator = sv.MaskAnnotator()
annotated_frame = mask_annotator.annotate(
    scene=image.copy(),
    detections=detections
)

sv.plot_image(annotated_image)
```

**Comment by SOBAN50** [comment]
Right. Thankyou for clarifying. In the code its actually:

```py
model = YOLO("yolov8s.pt")
```

Instead of
```py
model = YOLO("yolov8n-seg.pt")
```

**Comment by SkalskiP** [comment]
Exactly. And YOLO-NAS does not support segmentation, and that's why you don't see masks :/ Glad we could help. I'm closing the issue. :)
