### ISSUE TITLE
Show_frame_in_notebook not working in Jupyter notebooks by default 

### ISSUE THREAD

**Issue by moaaztaha** [roboflow/supervision#5]
I'm following **how-to-track-and-count-vehicles-with-yolov8** notebook on my local machine and found that `show_frame_in_notebook()` runs but the output frame is not rendered.

After some googling I found out that we need to add `%matplotlib inline` to the cell where we use the function for it to work. and it is used only once. 

Also when I try to add it to the first cell of the notebook the function doesn't render too it needs to be in the same cell or after it for the first run.

I know my problem is solved but I'd like to see if it can be added to the library directly and that it was not used on colab.

**Comment by SkalskiP** [comment]
Hi, I did some reading and we can't include`%matplotlib inline` in python code (the library) as it is only understandable by Jupyter Notebook. I guess we just need to do better robe with documenting.

**Comment by moaaztaha** [comment]
I understand, by the way, I used the library with Yolov5 and Deep sort and It's amazing as this is my first tracking objects.

**Comment by SkalskiP** [comment]
@moaaztaha I'm so happy to hear that! It is not even officially released and it is already useful for you!
