### ISSUE TITLE
3D object tracking

### ISSUE THREAD

**Issue by Mars-204** [roboflow/supervision#504]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Is the supervision capable of performing 3D object tracking from 3D bounding boxes?

**Comment by onuralpszr** [comment]
@Mars-204  Sv doesn't have 3D object or "objectron" type of tracker support yet but you are very welcome to implement If you want to be happened. :)

**Comment by onuralpszr** [comment]
I am also converting this issue to Q&A discussion
