### ISSUE TITLE
Mask annotator from SAM error

### ISSUE THREAD

**Issue by Giacroix** [roboflow/supervision#509]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I'm following the tutorial for computing the mask with SAM, I already changed 

```python
mask_annotator = sv.MaskAnnotator(color_map = "INDEX")
```

to

```python
mask_annotator = sv.MaskAnnotator(color_lookup = "INDEX")
```

But I get this error

```console
  annotated_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)
  File "/usr/local/lib/python3.8/site-packages/supervision/annotators/core.py", line 154, in annotate
    color = resolve_color(
  File "/usr/local/lib/python3.8/site-packages/supervision/annotators/utils.py", line 83, in resolve_color
    return get_color_by_index(color=color, idx=idx)
  File "/usr/local/lib/python3.8/site-packages/supervision/annotators/utils.py", line 68, in get_color_by_index
    return color.by_idx(idx)
  File "/usr/local/lib/python3.8/site-packages/supervision/draw/color.py", line 181, in by_idx
    if idx < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

### Environment

- Supervision 0.16.0
- python 3.8

### Minimal Reproducible Example

```python
  sam = sam_model_registry\[MODEL_TYPE\](checkpoint=weights)
  sam.to(device)
  
  mask_generator = SamAutomaticMaskGenerator(sam)
  
  image_bgr = cv2.imread(image_path)
  image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
  result = mask_generator.generate(image_rgb)
  
  print(result[0].keys())
  
  mask_annotator = sv.MaskAnnotator(color_lookup = "INDEX")
  
  detections = sv.Detections.from_sam(result)
  
  annotated_image = mask_annotator.annotate(scene=image_bgr.copy(), detections=detections)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

Update : (Issue formatting updated by @onuralpszr )

**Comment by maliozer** [comment]
I changed the version to 0.5.0 as on tutorial but still same error

**Comment by xzkeee** [comment]
same error

**Comment by onuralpszr** [comment]
@xzkeee  @Giacroix  @maliozer 

@maliozer  please update your supervision to latest blog page needs to be updated I will notify @SkalskiP  so he can update the blog page

And about sam and for the fix visually you should be see this 

![image](https://github.com/roboflow/supervision/assets/1688848/dd7c254e-64ef-4dee-bbd3-1b824f29d497)


```python
import torch
from segment_anything import sam_model_registry
import cv2
from segment_anything import SamAutomaticMaskGenerator

DEVICE = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
MODEL_TYPE = "vit_h"

sam = sam_model_registry[MODEL_TYPE](checkpoint=CHECKPOINT_PATH)
sam.to(device=DEVICE)

mask_generator = SamAutomaticMaskGenerator(sam)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
result = mask_generator.generate(image_rgb)

import supervision as sv
mask_annotator = sv.MaskAnnotator(color_lookup = sv.ColorLookup.INDEX)
detections = sv.Detections.from_sam(result)
annotated_image = mask_annotator.annotate(image, detections)
```

**Comment by maliozer** [comment]
![image](https://github.com/roboflow/supervision/assets/1297458/83103bd4-a318-4d23-8be6-c419ac135225)

Is this colab notebook official?

https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-segment-anything-with-sam.ipynb

still has value error;
ValueError: Could not resolve color by class becauseDetections do not have class_id

**Comment by onuralpszr** [comment]
@maliozer  I think you deleted a comment but for information I already sent PR for those to fix as well. 

Link : https://github.com/roboflow/notebooks/pull/215 (notebooks also going to be fix as well)

**Comment by maliozer** [comment]
I realized the parameter name should be given also, it is not default

**Comment by onuralpszr** [comment]
> I realized the parameter name should be given also, it is not default

Default is "sv.ColorLookup.CLASS" but SAM works by index
