### ISSUE TITLE
annotate masks

### ISSUE THREAD

**Issue by s4ifbn** [roboflow/supervision#52]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

if we use the segmentation model, we should annotate the segments masks with supervision, as you did with boses and ids
thanks :)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @s4ifbn 👋🏻! Do you need anything more or just annotators for now? What segmentation model do you use?

**Comment by s4ifbn** [comment]
@SkalskiP I'm using YOLOv8 for segmentation and trying to estimate the size of detected objects while applying perspective projection.

**Comment by s4ifbn** [comment]
That would be very helpful, thanks

**Comment by SkalskiP** [comment]
I'll try to add that as soon as possible, but I can't make any promises on the timeline.

**Comment by SkalskiP** [comment]
Hi @s4ifbn 👋🏻! Mask support is here! 🎉 Take a look [here](https://roboflow.github.io/supervision/detection/core/#detections) to learn about new `Detections.mask` property and [here](https://roboflow.github.io/supervision/detection/annotate/#maskannotator) to learn about our new `MaskAnnotator`. I'm closing this issue but feel free in case you would like to ask some questions.

**Comment by s4ifbn** [comment]
Thats awesome 

I tried to use the MaskAnnotator but the mask in detections always None. I used a YOLOv8 segmentation model

'''
mask_annotator = sv.MaskAnnotator(color=RED)
for result in model.track(source=VIDEO, show=False, tracker=TRACKER, classes=CLASSES, device=MPS, stream=True, conf=0.5):
      detections = sv.Detections.from_yolov8(result)
       frame = mask_annotator.annotate(scene=frame, detections=detections, opacity=0.5)
'''

**Comment by SkalskiP** [comment]
Hi 👋🏻 @s4ifbn! For YOLOv8 connector is not extracting masks. :/ You can still use it, but would need to extract masks manually from YOLOv8 result and pass to Detections. We will and that support at some point. For now post of the mask work we do is with SAM.

**Comment by s4ifbn** [comment]
I see, thank you @SkalskiP
