### ISSUE TITLE
How to use yolov8 track with supervision?

### ISSUE THREAD

**Issue by wynshiter** [roboflow/supervision#55]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

i know if we ues object detection we can use the following code
```python
>>> from ultralytics import YOLO
>>> from supervision import Detections

>>> model = YOLO('yolov8s.pt')
>>> results = model(frame)[0]
>>> detections = Detections.from_yolov8(results)
```
if i am using yolov8 tracking api 
results = model.track(source=0, stream=True,show=True,classes=[0])
then how can i put the results in our Detection?

**Comment by SkalskiP** [comment]
Hi 👋🏻! We have a YouTube video about it: https://youtu.be/Mi9iHFd0_Bo 

I'm closing the issue. But feel free to reopen it if you'll still have questions.

**Comment by wynshiter** [comment]
> Hi 👋🏻! We have a YouTube video about it: https://youtu.be/Mi9iHFd0_Bo
> 
> I'm closing the issue. But feel free to reopen it if you'll still have questions.

Thank you very much for your reply. I would like to ask one more question about how to obtain the LineZone result? For example, the int values of in and out？

**Comment by SkalskiP** [comment]
@wynshiter I'm glad you managed to solve that problem on your own :) Best of luck :)
