### ISSUE TITLE
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)

### ISSUE THREAD

**Issue by 0livet0** [roboflow/supervision#550]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### **Failure when trying to run supervision on jetson orin with the following environment:**

1. ****jetson@jetson-desktop:~$ cat /etc/nv_tegra_release****

`# R35 (release), REVISION: 3.1, GCID: 32827747, BOARD: t186ref, EABI: aarch64, DATE: Sun Mar 19 15:19:21 UTC 2023`

2. **jetson@jetson-desktop:~$ cat /etc/lsb-release** 

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

3. **jetson@jetson-desktop:~$ docker --version**

Docker version 20.10.21, build 20.10.21-0ubuntu1~20.04.2

4. **within ultralytics/ultralytics:latest-jetson docker with the following opencv apt packages already installed:**

**root@5b300f35bad3:/usr/src/ultralytics# apt list --installed | grep opencv**

opencv-dev/now 4.5.0 arm64 [installed,local]
opencv-libs/now 4.5.0 arm64 [installed,local]
opencv-licenses/now 4.5.0 arm64 [installed,upgradable to: 4.5.4-8-g3e4c170df4]
opencv-main/now 4.5.0 arm64 [installed,local]
opencv-python/now 4.5.0 arm64 [installed,local]
opencv-scripts/now 4.5.0 arm64 [installed,local]

5. **jetson@jetson-desktop:~$ docker run -it --rm --runtime=nvidia ultralytics/ultralytics:latest-jetson sh -c "pip3 install supervision && python3 -c 'import supervision'"**

Collecting supervision
  Downloading supervision-0.16.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: matplotlib<4.0.0,>=3.7.1 in /usr/local/lib/python3.8/dist-packages (from supervision) (3.7.3)
Requirement already satisfied: numpy<2.0.0,>=1.20.0 in /usr/local/lib/python3.8/dist-packages (from supervision) (1.23.0)
Collecting opencv-python-headless<5.0.0.0,>=4.8.0.74 (from supervision)
  Downloading opencv_python_headless-4.8.1.78-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata (19 kB)
Requirement already satisfied: pillow<11.0,>=9.4 in /usr/local/lib/python3.8/dist-packages/Pillow-9.4.0-py3.8-linux-aarch64.egg (from supervision) (9.4.0)
Requirement already satisfied: pyyaml<7.0,>=6.0 in /usr/local/lib/python3.8/dist-packages (from supervision) (6.0.1)
Requirement already satisfied: scipy<2.0.0,>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from supervision) (1.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.8/dist-packages (from matplotlib<4.0.0,>=3.7.1->supervision) (6.1.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib-resources>=3.2.0->matplotlib<4.0.0,>=3.7.1->supervision) (3.17.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.7.1->supervision) (1.14.0)
Downloading supervision-0.16.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.2/72.2 kB 8.1 MB/s eta 0:00:00
Downloading opencv_python_headless-4.8.1.78-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (28.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.7/28.7 MB 6.4 MB/s eta 0:00:00
Installing collected packages: opencv-python-headless, supervision
Successfully installed opencv-python-headless-4.8.1.78 supervision-0.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/supervision/__init__.py", line 9, in <module>
    from supervision.annotators.core import (
  File "/usr/local/lib/python3.8/dist-packages/supervision/annotators/core.py", line 4, in <module>
    import cv2
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.8/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)

**AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)**

### Environment

1. Nvidia Jetson Nano 16 GB
2. L4T 35.3.1
3. Ubuntu 20.04
4. Docker 20.10.21

### Minimal Reproducible Example

```
jetson@jetson-desktop:~$ docker run -it --rm --runtime=nvidia ultralytics/ultralytics:latest-jetson sh -c "pip3 install supervision && python3 -c 'import supervision'"
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @0livet0 👋🏻 Do we know if installing supervision breaks the `cv2`? What would happen if you wouldn't install `supervision`, and just run `python3 -c 'import cv2'"`?

**Comment by 0livet0** [comment]
Hi Piotr! 
yep it breaks cv2... At least when installing supervision inside ultralytics:jetson-latest docker image.
Without installing supervision, cv2 works fine.
Running:

`docker run -it --rm --runtime=nvidia --platform=linux/arm64 ultralytics/ultralytics:latest-jetson sh -c "python3 -c 'import cv2; print(cv2.__version__)'"`

outputs:  `4.5.0`

**Comment by SkalskiP** [comment]
Hi @0livet0 👋🏻 

Could you try to install `supervision` without dependencies?

```
pip install supervision --no-deps
```

This should only install supervision code and not install dependencies. Importantly it will not mess up your `cv2` install.

**Comment by 0livet0** [comment]
Works fine! 
Thanks @SkalskiP !

**Comment by SkalskiP** [comment]
Awesome! 🔥 I'm closing the issue. I know @onuralpszr is already thinking about some permanent solutions.
