### ISSUE TITLE
Use shapely for shapes 

### ISSUE THREAD

**Issue by linchiyu** [roboflow/supervision#551]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi, I was wondering if there would be interest in using shapely for working with geometrycs in this project. Seems like it could speed up implementation time and get more done. 
Is this something that can be on radar?

**Comment by onuralpszr** [comment]
Preferably, no, because we want to keep our dependencies at minimum, we may find use case if really needed.

**Comment by SkalskiP** [comment]
Hi @linchiyu 👋🏻! As @onuralpszr said we try to keep our dependency list as short as possible. Thanks for your interest in our project! 🙏🏻
