### ISSUE TITLE
Issue using Supervision with Yolov5 custom dataset - cannot plot image

### ISSUE THREAD

**Issue by yeongnamtan** [roboflow/supervision#581]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

I am learning to use supervision and was going thru the demo.jpynb.

I managed to import the weights for yolov5 as follow:
model = torch.hub.load('ultralytics/yolov5', 'custom', path='/root/supervision/best_yolov5x_3Nov2023.pt') 

# detections using Yolov5
results = model(image)
detections = sv.Detections.from_yolov5(results)
detections = detections[detections.confidence > 0.3]
"detections", len(detections)

The detections work well but somehow I can't display the image when I use BoundingBoxAnnotator:

Appreciate any guidance !!

### Additional

![supervison ](https://github.com/roboflow/supervision/assets/105199717/44a95861-e30d-4d06-99fd-be3cc5adbc6e)

**Comment by yeongnamtan** [comment]
Thank you very much @Shishuii

**Comment by SkalskiP** [comment]
@Shishuii, thanks a lot for pointing @yeongnamtan in the right direction. I'm closing the issue.
