### ISSUE TITLE
No argument called 'color_map' in MaskAnnotator, and neither does 'color_lookup' exist

### ISSUE THREAD

**Issue by olyashok** [roboflow/supervision#588]
In the latest update, it seems there is no argument called 'color_map' in MaskAnnotator, and neither does 'color_lookup' exist, which is given in the documentation of MaskAnnotator on Roboflow, and seems to be similar in functionality to 'color_map'

_Originally posted by @SambitPrabhu in https://github.com/roboflow/supervision/discussions/428#discussioncomment-7482934_

**Comment by onuralpszr** [comment]
@olyashok  would you share your current supervision version and where did you ran it ? Collab,local,kaggle and picture also would be nice for showing infos also minimum code or entire code share would be extra awesome to figure out problem.

**Comment by olyashok** [comment]
You can close this. This works:

result = mask_generator.generate(image_rgb)
mask_annotator = sv.MaskAnnotator(color_lookup = sv.ColorLookup.INDEX)

**Comment by SkalskiP** [comment]
Awesome! Closing the issue!
