### ISSUE TITLE
Parameters to finetune ByteTrack

### ISSUE THREAD

**Issue by yeongnamtan** [roboflow/supervision#595]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Where can I find information on how to finetune the parameters in Bytetrack ?

https://supervision.roboflow.com/trackers/#bytetrack

**Comment by rafaelgildin** [comment]
Probably you can change the parameters from the documentation you've sent.
If you need more parameters you can change the class in your python environment.
Finally, you can use bytetrack without using supervision, then you'll be able to change all params from their github.

**Comment by SkalskiP** [comment]
We are planning extensive improvements in ByteTrack in the coming months - https://github.com/roboflow/supervision/issues/754. The changes will include, among others, the names and documentation of arguments. Please be patient for a little longer. 🙏🏻
