### ISSUE TITLE
How to flash the zones when an object is detected in the zone?

### ISSUE THREAD

**Issue by PiyushKamboj1503** [roboflow/supervision#60]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Use Case:
There are zones in a mall which have restricted access. People can walk around the zone. I want to flash the zone(not annotating it earlier) as soon as a person walks right into it.

Methodology: The zone should get annotated as soon as an object is detected inside the zone defined by the polygon method.

**Comment by SkalskiP** [comment]
Hi 👋🏻! Could you describe a bit more precisely how this is different from what we already have?

**Comment by SkalskiP** [comment]
but you can do it now I think. The zone is only annotated on the screen if `PolygonZoneAnnotator. annotate` is called. If you don't call it it is not annotated. So you can decide to only call it when `PolygonZone.current_count` is changed. Does that solution work for you?

**Comment by PiyushKamboj1503** [comment]
![image](https://user-images.githubusercontent.com/54760385/231760298-f273e908-a195-42c1-b2fa-9a0813dc5095.png)

**Comment by SkalskiP** [comment]
That's because `current_count` does not live in type `PolygonZone` but in the instance of an object of that type. You first need to create object `polygon_zone = sv.PolygonZone(...)` and then access that count `polygon_zone.current_count`.

**Comment by PiyushKamboj1503** [comment]
Got
