### ISSUE TITLE
How to label the zone?

### ISSUE THREAD

**Issue by epigraphe** [roboflow/supervision#604]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hello. Please tell me, is it possible to give a name for a zone on the screen? I have 8 cameras, each with 4 zones. I record the values from these zones every 10 seconds for further processing.
Is there a native naming option for each zone?
This would make it much easier to associate a zone with its value.

Like that:

![image](https://github.com/roboflow/supervision/assets/6083395/09dda775-56ca-4ac7-9616-c2acf9de493f)

**Comment by SkalskiP** [comment]
Hi, @epigraphe 👋🏻 ! Thanks for your interest in `supervision`. I am sorry I have not been responsive for the last few days. Before Christmas, I was busy with duties unrelated to supervision and was off for the last few days.

As for your question, you can do it with [`draw_text`](https://supervision.roboflow.com/draw/utils/#supervision.draw.utils.draw_text). It allows you to draw text anywhere on the screen. You can choose a place that is one of the polygon zone vertices. 

I'm closing the issue. Feel free to reopen if you have more questions.
