### ISSUE TITLE
type object 'Detections' has no attribute 'from_yolov8'

### ISSUE THREAD

**Issue by andysingal** [roboflow/supervision#614]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

```
0: 384x640 1 car, 7.3ms
Speed: 1.7ms preprocess, 7.3ms inference, 1.4ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs/detect/predict4
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-a08dc210e550>](https://localhost:8080/#) in <cell line: 25>()
     38             # Visualize the results on the frame
     39             annotated_frame = results[0].plot()
---> 40             detections = sv.Detections.from_yolov8(results[0])
     41 
     42             # Plot the tracks and count objects crossing the line

AttributeError: type object 'Detections' has no attribute 'from_yolov8'
```

### Environment

```
!pip install ultralytics supervision gdown -q
```

### Minimal Reproducible Example

please find the colab: https://colab.research.google.com/drive/1c2cRP4iAQl9Kb137YfrzI6Gs2ynYczCf?usp=sharing 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by DylanLoader** [comment]
You might be referencing an old notebook, in the current version of supervision (0.16.0) it should be:

detections = sv.Detections.from_ultralytics(result) 

reference: https://github.com/roboflow/supervision/blob/10c44b0143c13b33c1951509f9f11c37c6373752/supervision/classification/core.py#L43

**Comment by SkalskiP** [comment]
Hi, @andysingal! 👋🏻 `from_yolov8` was deprecated for a few months and finally was replaced by `from_ultralytics` in `supervision-0.16.0`.

I'm closing this issue. Feel free to reopen if you will face more problems.

**Comment by andysingal** [comment]
@DylanLoader Thanks alot, it works now. But counting on the vehicles for some reason stopped working : https://colab.research.google.com/drive/1c2cRP4iAQl9Kb137YfrzI6Gs2ynYczCf?usp=sharing

**Comment by lixl4433** [comment]
detections = sv.Detections.ffrom_yolov8(result)   --->   detections = sv.Detections.from_ultralytics(result)

**Comment by lixl4433** [comment]
somethings changed,  and this
for _, confidence, class_id, tracker_id  in detections ---->  for a,b, confidence, class_id, tracker_id  in detections

**Comment by SkalskiP** [comment]
@lixl4433 is right. We made those API changers. @andysingal We don't plan to change that code, but nevertheless it is always good idea to pin your version. 🙏🏻
