### ISSUE TITLE
Car speed calculation with LineCounter

### ISSUE THREAD

**Issue by whatisslove11** [roboflow/supervision#619]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi!
I use a line counter to count the cards, but I also need to calculate the speed of the car
I have two lines on the road and I know the distance between them
How can I calculate the speed of passing cars at a distance exactly between these two lines?

**Comment by kapter** [comment]
You can find time of position of car at line1 as t1, at line2 as t2, distance as d.
Speed is d/(t2-t1)

**Comment by SkalskiP** [comment]
We recently released deep tutorial showing how to calculate vehicle speed using supervision. https://github.com/roboflow/supervision/tree/develop/examples/speed_estimation

I'm closing the issue :)
