### ISSUE TITLE
LineZone expecting 4 values rather than the new 5 from adding mask to Detections Class. 

### ISSUE THREAD

**Issue by ChaseDDevelopment** [roboflow/supervision#62]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

After upgrading to the latest commit today, (v0.5.1) The LineZone Class tries to iterate over the detections and unpack 4 values rather than the new 5. 

https://github.com/roboflow/supervision/blob/e091f9c9594bcb1d04a8fbfffc885722c4c2c765/supervision/detection/line_counter.py#L38

For now on my end I just added `_` as I'm not using mask at all. and it solved the error message of:

```too many values to unpack (expected 4)```

I don't know if mask is needed or is planned to be implemented in the LineZone trigger function, otherwise I would just submit a PR with the line changed to:

```for xyxy, _, confidence, class_id, tracker_id in detections:```

### Environment

- Supervision 0.5.1
- Ubuntu 22.10
- Python 3.8.10
- YOLOv8

### Minimal Reproducible Example

```python
import supervision as sv

line_zone = sv.LineZone(start=LINE_START, end=LINE_END)
result = model.predict(source=frame, stream=False)
detections = Detections(
            xyxy=result.boxes.xyxy.cpu().numpy(),
            confidence=result.boxes.conf.cpu().numpy(),
            class_id=result.boxes.cls.cpu().numpy().astype(int),
        )
tracker_ids = match_detections_with_tracks(detections=detections, tracks=tracks)
detections.tracker_id = np.array(tracker_ids)
detections = detections[detections.tracker_id != None]
labels = [
                f"Item: #{tracker_id} {model.names[class_id]} {confidence:0.2f}"
                for _, _, confidence, class_id, tracker_id in detections
            ]
line_zone.trigger(detections)  <--------- This is where it fails
        
```

### Additional

I'm using Yolov8, and using ByteTracker stuff from some of the previous videos to get my tracker_id's. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
@ChaseDDevelopment good catch! Would you be keen to submit PR with `for xyxy, _, confidence, class_id, tracker_id in detections:` fix?

**Comment by ChaseDDevelopment** [comment]
@SkalskiP Yes I can do that, will create one shortly.

**Comment by SkalskiP** [comment]
@ChaseDDevelopment awesome!

**Comment by ChaseDDevelopment** [comment]
@SkalskiP 

#63 is now up. Closing this issue.
