### ISSUE TITLE
Dataset size of 0

### ISSUE THREAD

**Issue by alexeidinca-ro** [roboflow/supervision#626]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hello! Hope you are well!

I am trying to run a Supervision Benchmark (confusion matrix) on a custom dataset and everytime it gives me the dataset size of zero and a confusion matrix of zero. What am i doing wrong in this approach? The data set is a test one, the format is a YOLO one with images and annotations in txt format. The YAML file is the classic YOLO one. 

I am attaching the code and content of the YAML file.

data.yaml below:

```
train: ../ita-my-patch/train/images
val: ../ita-my-patch/valid/images
test: ../ita-my-patch/test/images

nc: 1
names: ["HH"]
```

Notebook code below: 

```python
import supervision as sv
from ultralytics import YOLO
import numpy as np 

dataset = sv.DetectionDataset.from_yolo(
    images_directory_path='ita-my-patch/test/images',
    annotations_directory_path='ita-my-patch/test/labels',
    data_yaml_path='data.yaml'
)

model = YOLO("runs/detect/train27/weights/best.pt")

print('dataset classes:', dataset.classes)
print('dataset size:', len(dataset))

def callback(image: np.ndarray) -> sv.Detections:
    result = model(image)[0]
    return sv.Detections.from_ultralytics(result)


confusion_matrix = sv.ConfusionMatrix.benchmark(
   dataset = dataset,
   callback = callback
)

confusion_matrix.matrix
```

**Comment by SkalskiP** [comment]
Hi @alexeidinca-ro! 👋🏻 Let me convert that question into the discussion and put it into the Q&A section.
