### ISSUE TITLE
Add legend text on video frames

### ISSUE THREAD

**Issue by dimpolitik** [roboflow/supervision#676]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi All!

I'm trying to find a way to add a legend text at each frame (with the number of frame assigned) during the object tracking. Does supervision has a way to do that? I checked the available annotators, but I didn't find something relevant.
Thank you!

**Comment by SkalskiP** [comment]
Hi @dimpolitik 👋🏻 Did you try to use [`draw_text`](https://supervision.roboflow.com/draw/utils/#draw_text)?

**Comment by SkalskiP** [comment]
Hi @dimpolitik. Did my idea solve your problem?

**Comment by dimpolitik** [comment]
> Hi @dimpolitik. Did my idea solve your problem?
@SkalskiP  Thank you for your help, it solved my issue :) . 
The scene image is black, so the text is not visible. I tried this and it works fine:

`import supervision as sv
img = cv.imread('test_image.png')
text_anchor = sv.Point(x=50, y=50)
img_text = sv.draw_text(scene=img, text="Hello, world!",text_anchor=text_anchor)
sv.plot_image(img_text) 
`

**Comment by SkalskiP** [comment]
Yeah my example was mostly showing how to apply it on the scene. Awesome!
