### ISSUE TITLE
Add annotator EdgeBoundingBoxAnnotator which has rectangle with thick edges

### ISSUE THREAD

**Issue by xaristeidou** [roboflow/supervision#694]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

I have created a new annotator class named `EdgeBoundingBoxAnnotator` which draws bounding box with thick edges and the ability to select different colors.

`EdgeBoundingBoxAnnotator` has the same attributes with `BoundingBoxAnnotator` including three (3) extra attributes `edge_color`, `edge_thickness`, `edge_length` which accept respectively:

- Union[Color, ColorPalette]
- int (edge_thickness >= thickness)
- float (0 < edge_length < 1.0 )

`edge_box_annotator = sv.EdgeBoundingBoxAnnotator(color=sv.Color.black(), edge_thickness=5, edge_length=0.6)`

Below is a video demo of the annotator. Let me know your thoughts about it, for any possible changes, and if its good I can submit a PR.

https://github.com/roboflow/supervision/assets/65918758/5f2444ea-1b7f-4dbc-9f2d-e7e85568f762

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @xaristeidou 👋🏻 ! I see that you have been very active in Supervision over the last few days. As for this annotator, it is already possible. All you have to do is combo [BoundingBoxAnnotator](https://supervision.roboflow.com/annotators/#boundingboxannotator) and [BoxCornerAnnotator](https://supervision.roboflow.com/annotators/#boxcornerannotator). For this reason, I am closing the issue, but I am waiting for more super ideas.
