### ISSUE TITLE
Add annotator `sv.PercentageBarAnnotator` which shows percentage bar of confidence level in specified position

### ISSUE THREAD

**Issue by xaristeidou** [roboflow/supervision#695]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

I have created a new annotator class named `PercentageBarAnnotator` which draws a percentage bar based on the confidence for each prediction, in a specific position around the box.

An issue already exists, issue #459 , but it seems to be inactive since it's 2+ months old. I had posted there a demo video from a previous try to implement that but it was not pretty and uncompleted.

`PercentageBarAnnotator` accepts the following attributes:

```
-   height: int = 14,
-   width: int = 80,
-   color: Union[Color, ColorPalette] = ColorPalette.default(),
-   border_color: Color = Color.black(),
-   position: Position = Position.TOP_CENTER,
-   color_lookup: ColorLookup = ColorLookup.CLASS,
```

`percentage_bar_annotator = sv.PercentageBarAnnotator()`

Below is a video demo of the annotator. Let me know your thoughts about it, for any possible changes, and if its good I can submit a PR.

https://github.com/roboflow/supervision/assets/65918758/e214fab1-ba12-4479-95cd-33cfcd42fcd6

Some more examples regarding the height attribute of the percentage bar:
`
sv.PercentageBarAnnotator(height=12)`

![percentage_bar_height_12](https://github.com/roboflow/supervision/assets/65918758/ac0874b8-8607-4cda-8c6a-5c91cd7d9648)

`sv.PercentageBarAnnotator(height=22)`

![percentage_bar_height_22](https://github.com/roboflow/supervision/assets/65918758/089f4ee2-b17d-47f8-a187-197afb7caff8)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @xaristeidou 👋🏻 ! I love your progress. I think you should open PR with what you have already.
