### ISSUE TITLE
track_ids of Detections in different videos

### ISSUE THREAD

**Issue by kenwaytis** [roboflow/supervision#698]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

In different videos (or from different angles), are the track_ids of Detections the same? I want to use the consistency of track_id for cross-video tracking.

**Comment by SkalskiP** [comment]
Hi, @kenwaytis 👋🏻 ! Thanks for your interest in `supervision`. As for your question, `track_id` is only consistent across a single video. There is no consistency across multiple videos. 

Having said that, we plan to add features capable of solving your problem. But it is quite far on our TODO list.

I'm closing this issue. Feel free to reopen if you have more questions.
