### ISSUE TITLE
Does the model output analysis support YOLOv8 OBB rotation target detection

### ISSUE THREAD

**Issue by KTXKIKI** [roboflow/supervision#715]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

Does the model output analysis support YOLOv8 OBB rotation target detection

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @KTXKIKI 👋🏻 ! Sorry for the late response. I was out for the past couple of days.

We are not yet supporting OBB, but it is on our TODO list.

**Comment by SkalskiP** [comment]
I'm closing this issue as OBB support will be added within https://github.com/roboflow/supervision/issues/749
