### ISSUE TITLE
speed estimation issue

### ISSUE THREAD

**Issue by yeongnamtan** [roboflow/supervision#722]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

I run the speed estimate code and get the error below:

Code:

```console
!python ultralytics_example.py \
  --source_video_path data/vehicles.mp4 \
  --target_video_path data/vehicles-result.mp4 \
  --confidence_threshold 0.3 \
  --iou_threshold 0.5
```

Error:

```console
0: 384x640 (no detections), 65.5ms
Speed: 3.5ms preprocess, 65.5ms inference, 0.7ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):
  File "ultralytics_example.py", line 114, in <module>
    points = view_transformer.transform_points(points=points).astype(int)
  File "ultralytics_example.py", line 34, in transform_points
    return transformed_points.reshape(-1, 2)
AttributeError: 'NoneType' object has no attribute 'reshape'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by onuralpszr** [comment]
Hello, @yeongnamtan first did you download the video and did you use the same code or did you change something If yes what is it ?

**Comment by yeongnamtan** [comment]
@onuralpszr I downloaded the video and use the same code. I didn't change anything.

**Comment by onuralpszr** [comment]
> @onuralpszr I downloaded the video and use the same code. I didn't change anything.

What is your Python env, and also share the pip list please, too. Also, what is your operation system ?

**Comment by yeongnamtan** [comment]
@onuralpszr  I used sagemaker studio python 3.8.   

Package                     Version
--------------------------- --------------------
apex                        0.1
appdirs                     1.4.4
asttokens                   2.4.1
attrs                       22.2.0
awscli                      1.27.70
awsio                       0.0.1
backcall                    0.2.0
bcrypt                      4.0.1
bokeh                       2.4.3
boto3                       1.26.70
botocore                    1.29.70
brotlipy                    0.7.0
cached-property             1.5.2
certifi                     2022.12.7
cffi                        1.15.1
charset-normalizer          2.1.1
click                       8.1.3
cloudpickle                 2.2.1
cmake                       3.18.2.post1
colorama                    0.4.4
conda                       22.11.1
conda-content-trust         0.1.3
conda-package-handling      2.0.2
conda_package_streaming     0.7.0
contextlib2                 21.6.0
contourpy                   1.0.7
cryptography                39.0.1
cycler                      0.11.0
Cython                      0.29.33
decorator                   5.1.1
deepspeed                   0.6.1+b3d766e
dgl                         0.9.1.post1
dill                        0.3.6
docutils                    0.16
einops                      0.6.0
executing                   2.0.1
flash-attn                  0.1
fonttools                   4.38.0
fsspec                      2023.1.0
gevent                      22.10.2
google-pasta                0.2.0
greenlet                    2.0.2
h5py                        3.8.0
hjson                       3.1.0
horovod                     0.24.3
idna                        3.4
imageio                     2.25.1
importlib-metadata          4.13.0
importlib-resources         5.10.2
inotify-simple              1.2.1
ipykernel                   5.5.6
ipython                     8.12.3
ipython-genutils            0.2.0
jedi                        0.19.1
Jinja2                      3.1.2
jmespath                    1.0.1
joblib                      1.2.0
jsonpatch                   1.32
jsonpointer                 2.3
jupyter-client              6.1.5
jupyter_core                5.7.0
kiwisolver                  1.4.4
lapx                        0.5.5
libmambapy                  1.1.0
llvmlite                    0.36.0
mamba                       1.1.0
MarkupSafe                  2.1.2
matplotlib                  3.7.0
matplotlib-inline           0.1.6
mpi4py                      3.1.3
multiprocess                0.70.14
networkx                    3.0
ninja                       1.11.1
numba                       0.53.1
numpy                       1.23.5
opencv-python               4.7.0.68
packaging                   23.0
pandas                      1.5.3
paramiko                    3.0.0
parso                       0.8.3
pathos                      0.3.0
pexpect                     4.9.0
pickleshare                 0.7.5
Pillow                      9.4.0
pip                         23.0
platformdirs                4.1.0
plotly                      5.13.0
pluggy                      1.0.0
pooch                       1.6.0
portalocker                 2.7.0
pox                         0.3.2
ppft                        1.7.6.6
prompt-toolkit              3.0.43
protobuf                    3.20.2
protobuf3-to-dict           0.1.5
psutil                      5.9.4
ptyprocess                  0.7.0
pure-eval                   0.2.2
py-cpuinfo                  9.0.0
pyarrow                     11.0.0
pyasn1                      0.4.8
pybind11                    2.10.3
pycosat                     0.6.4
pycparser                   2.21
pyfunctional                1.4.3
Pygments                    2.17.2
pyinstrument                3.4.2
pyinstrument-cext           0.2.4
PyNaCl                      1.5.0
pyOpenSSL                   23.0.0
pyparsing                   3.0.9
PySocks                     1.7.1
python-dateutil             2.8.2
pytz                        2022.7.1
PyYAML                      5.4.1
pyzmq                       25.1.2
requests                    2.28.2
retrying                    1.3.4
rsa                         4.7.2
ruamel.yaml                 0.17.21
ruamel.yaml.clib            0.2.7
s3fs                        0.4.2
s3transfer                  0.6.0
sagemaker                   2.132.0
sagemaker-experiments       0.1.42
sagemaker-pytorch-training  2.7.0
sagemaker-training          4.4.5
schema                      0.7.5
scikit-learn                1.2.1
scipy                       1.10.0
seaborn                     0.12.2
setuptools                  65.6.3
shap                        0.41.0
six                         1.16.0
slicer                      0.0.7
smclarify                   0.3
smdebug                     1.0.24b20230214
smdebug-rulesconfig         1.0.1
smdistributed-dataparallel  1.6.0
smdistributed-modelparallel 1.13.0
stack-data                  0.6.3
tabulate                    0.9.0
tenacity                    8.2.1
thop                        0.1.1.post2209072238
threadpoolctl               3.1.0
toolz                       0.12.0
torch                       1.12.1+cu113
torchaudio                  0.12.1+cu113
torchdata                   0.4.1
torchnet                    0.0.4
torchvision                 0.13.1+cu113
tornado                     6.2
tqdm                        4.64.1
traitlets                   5.14.1
typing_extensions           4.9.0
ultralytics                 8.1.2
urllib3                     1.26.14
visdom                      0.2.4
wcwidth                     0.2.13
websocket-client            1.5.1
Werkzeug                    2.2.3
wheel                       0.38.4
zipp                        3.13.0
zope.event                  4.6
zope.interface              5.5.2
zstandard                   0.19.0

**Comment by SkalskiP** [comment]
@yeongnamtan, did you run the script on the same input file? I noticed `0: 384x640 (no detections), 65.5ms`. This does not happen with our video example. 

In the meantime, I know the reason - incorrect handling of cases when there are no detections. I'll work on the fix now.

**Comment by yeongnamtan** [comment]
@SkalskiP  yes i followed the instructions.   See attached.
![Uploading Screenshot 2024-01-16 185318.png…]()

**Comment by SkalskiP** [comment]
Hi, @yeongnamtan 👋🏻 ! I just created a [PR](https://github.com/roboflow/supervision/pull/733) that will hopefully fix your issue. Could you run:

```
python ultralytics_example.py \
  --source_video_path data/vehicles.mp4 \
  --target_video_path data/vehicles-result.mp4 \
  --confidence_threshold 0.3 \
  --iou_threshold 0.5
```

But using code that is currently on `fix/speed-estimation-issue-when-detections-empty`.

**Comment by yeongnamtan** [comment]
@SkalskiP I get below error ...
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8x.pt to 'yolov8x.pt'...
100% 131M/131M [00:00<00:00, 263MB/s]

0: 384x640 3 cars, 1 truck, 122.9ms
Speed: 3.1ms preprocess, 122.9ms inference, 577.4ms postprocess per image at shape (1, 3, 384, 640)
Traceback (most recent call last):
  File "/content/ultralytics/examples/YOLOv8-Region-Counter/ultralytics_example.py", line 116, in <module>
    points = view_transformer.transform_points(points=points).astype(int)
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by SkalskiP** [comment]
@yeongnamtan, oooh? Could you share what was the issue? I'm super curious.
