### ISSUE TITLE
The project could not run with python ultralytics_example.py.  The error report is: FileNotFoundError: /root/autodl-tmp/Roboflow/supervision/examples/speed_estimation/[[[172 146 126]......    

### ISSUE THREAD

**Issue by spring-wreath** [roboflow/supervision#732]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

![image](https://github.com/roboflow/supervision/assets/135488847/63641c90-9007-4daf-83d3-77fbdcbfee2e)

### Minimal Reproducible Example

python ultralytics_example.py \
>   --source_video_path data/vehicles.mp4 \
>   --target_video_path data/vehicles-result.mp4 \
>   --confidence_threshold 0.3 \
>   --iou_threshold 0.5

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @spring-wreath 👋🏻 I just ran the code on my machine to confirm it works, and it looks like it does. Now, we need to figure out why it fails for you.

 - Can you tel me more about your machine? Are you running Linux / Windows / Mac?
 - Is it a desktop or a server? 
 - Did you make any changes to the code I distributed?

**Comment by spring-wreath** [comment]
Thanks for your timely reply! 

My machine is server running with Linux. I tried both of your commands that you have given, but it still shows the same error. I am quite confused, cause this server can run with other project using yolov8 and deepsort, hope to hear from you soon, your works are really great, thanks!

**Comment by spring-wreath** [comment]
I am sure that i haven't change the original code. Still the same error.
![image](https://github.com/roboflow/supervision/assets/135488847/33be8828-257e-4bac-91b5-7fed108c4e95)

**Comment by spring-wreath** [comment]
It seems like it reads the data from the video and feedback matrix.

**Comment by SkalskiP** [comment]
@spring-wreath notice that you run:

```
python ultralytics_example.py \
>   --source_video_path data/vehicles.mp4 \
>   --target_video_path data/vehicles-result.mp4 \
>   --confidence_threshold 0.3 \
>   --iou_threshold 0.5
```

We do not want those `>` as part of the command. Please try the one below:

```
python ultralytics_example.py \
--source_video_path data/vehicles.mp4 \
--target_video_path data/vehicles-result.mp4 \
--confidence_threshold 0.3 \
--iou_threshold 0.5
```

**Comment by spring-wreath** [comment]
python ultralytics_example.py \--source_video_path data/vehicles.mp4 \--target_video_path data/vehicles-result.mp4 \--confidence_threshold 0.3 \--iou_threshold 0.5
![image](https://github.com/roboflow/supervision/assets/135488847/6226168a-fa58-4e14-b5ae-bcaf2318e48b)
I tried to put them on the same line, and it's still the same outcome. As for those > , when i copy your code into the vscode terminal, it will show > at the front of each line.

**Comment by spring-wreath** [comment]
I think it might be the problem of my machine and environment. I'll change it and try it again. Hope it will work.

**Comment by spring-wreath** [comment]
I change my machine, and it works! Having a good hardware is truly important.

**Comment by SkalskiP** [comment]
Hi, @spring-wreath 👋🏻 ! It's fantastic to hear you managed to run the example.
