### ISSUE TITLE
Black zones has black text in count box

### ISSUE THREAD

**Issue by PiyushKamboj1503** [roboflow/supervision#74]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

While using the black color for zone annotator, the number of objects detected in written with black text inside the black box.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @PiyushKamboj1503 👋🏻! You can use `text_color` parameter to change that. For example, use `Color.white()`. Take a look here: https://roboflow.github.io/supervision/detection/tools/polygon_zone/#polygonzoneannotator. I'm closing the issue for now, but feel free to reopen it in you will have any more related questions.
