### ISSUE TITLE
Using ByteTrack to track frames with moving detections AND moving backgrounds (i.e camera movement).

### ISSUE THREAD

**Issue by adaiale** [roboflow/supervision#743]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hi,

 I'm having an possible issue using ByteTrack on a 63 frame test clip to track two objects as they move and the camera observing them moves.  The bounding box model works very well, but when implementing ByteTrack the bounding box the tracker returns is not usable.  

  There is only one instance of each object in each frame and detection confidence is set to 0.5.  I've attached a screen shot of a print out of the detection before using byte track and after.  Without in the image implies without ByteTrack and are all over 90% confidence (to my eye close to 100%).  Notably the last frame ignores an object.  This is setting match_thresh=0.8.  This is also several frames in.
![byte_track_default](https://github.com/roboflow/supervision/assets/61034820/6ab83472-b0c1-4ec3-bee6-4c632e986eee)

The tracker correctly tracks the objects when setting match_thresh very close to 1,  but grossly mistakes the size of the boxes as opposed to using the original. Otherwise (at default) it either entirely ignores a proper detection, or labels a new track.  I'm trying to find more from the documentation but I'm struggling to understand why the boxes are being resized, and not using the original detections.  So without going deeper and testing I am asking here.

I have workarounds for my use case, but I am more curious to see if there is something I am missing or if there is an issue with the implementation (I haven't used ByteTrack from scratch, but will probably get around to it in the next week or so and update if needed).

Any pointers, questions, or just a "read / do this you dummy" are welcome.

**Comment by SkalskiP** [comment]
Hi, @adaiale 👋🏻! No, I don't think it is a dummy question. In general, the ByteTrack returns a prediction of the new location. Quote from [ByteTrack: Multi-Object Tracking by Associating Every Detection Box](https://arxiv.org/pdf/2110.06864.pdf) paper:


> After separating the low score detection boxes and the
high score detection boxes, we adopt Kalman filter to predict the new locations in the current frame of each track in T (line 14 to 16 in Algorithm 1).

I don't like it either.

**Comment by adaiale** [comment]
Thanks so much for the quick response, it saved me a lot time!
