### ISSUE TITLE
crop bounding boxes as separate image

### ISSUE THREAD

**Issue by ahmed-gaal** [roboflow/supervision#75]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Im curious as to how one can crop the sv.Detections as a separate image for further analysis >

**Comment by SkalskiP** [comment]
@maddust is right! That should work. We can also add some small utilities that would crop image bassed on `Detections.xyxy` values. Something like that:

```python
def crop_image(image: np.ndarray, xyxy: np.ndarray) -> List[np.ndarray]:
    pass
```

**Comment by ahmed-gaal** [comment]
@maddust Thanks a lot💯.
@SkalskiP Yes absolutely.

**Comment by SkalskiP** [comment]
In that case, I'll keep that issue open and add `crop_image` whenever I'll have a bit of time.

**Comment by sceddd** [comment]
You can checkout this one:
i'm trying to crop out the traffic light in the frame to detect it's color. So it'll be like:
```
def crop_image(image: np.ndarray, xyxy: np.ndarray,index:int) -> List[np.ndarray]:
  xyxy = [round(elem) for elem in xyxy ]
  x1,y1,x2,y2 = xyxy
  cropped_image = image[y1:y2,x1:x2]
  plot_image(cropped_image)
  cv2.imwrite(f"{HOME}/traffic_light{index}.jpg",cropped_image)
def process_trafficLight(frame: np.ndarray, i) -> np.ndarray:
  results = TLmodel(frame)[0]
  detections = Detections.from_yolov8(results)
  tracks = byte_tracker.update(
      output_results=detections2boxes(detections=detections),
      img_info=frame.shape,
      img_size=frame.shape
  )
  tracker_id = match_detections_with_tracks(detections=detections, tracks=tracks)
  detections.tracker_id = np.array(tracker_id)
  for i,xyxy in enumerate(detections.xyxy):
    crop_image(frame,xyxy,i)
  return frame

**Comment by SkalskiP** [comment]
Thanks a lot, @sceddd! We will release that functionality with `0.9.0` release.

**Comment by SkalskiP** [comment]
Cropping function was just added to `supervision` 🔥
