### ISSUE TITLE
`LineZone` 2.0

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#752]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

TODO

### Use case

TODO

### Additional

- delivery per class in/out count
- new ways to visualize results

**Comment by tiago-hansen** [comment]
It would be interesting if the trigger() method could return the tracker_id that changed the counter. This way we could measure if the same object is crossing in and out and how long it took.

**Comment by SkalskiP** [comment]
Hi @tiago-hansen, `trigger()` will not do it. But you get a tuple with in/out boolean masks showing which objects have crossed the line in the current frame. You can use this information to find out which tracker_ids were responsible for the change.

```
detections = sv.Detections()

crossed_in, crossed_out = line_zone.trigger(detections)

crossed_in_ids = detections[crossed_in].tracker_id
crossed_out_ids = detections[crossed_out].tracker_id
```
