### ISSUE TITLE
Remove `>>>` and `...` from docs and examples, and make code snippets easy to use

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#758]
### Bug

TODO

### Environment

TODO

### Minimal Reproducible Example

TODO

### Additional

TODO

**Comment by RaghavvGupta** [comment]
Hey, I am willing to work on this issue. Can it be assigned to me?

**Comment by onuralpszr** [comment]
@RaghavvGupta  good luck :)

**Comment by RaghavvGupta** [comment]
@onuralpszr thanks a lot, also do you have anything particular in mind for making the code snippets easy to use

**Comment by onuralpszr** [comment]
> @onuralpszr thanks a lot, also do you have anything particular in mind for making the code snippets easy to use

If you just remove ">>>" and "..." it is already makes easier because when we copy code via copy-button or select manually. It is pretty much make easier in the first place. So that would be first step. If you think any extra improvement you could of bring please let us know as well.

**Comment by RaghavvGupta** [comment]
Hey @onuralpszr, I have submitted the PR#761. Please tell me about changes if required.
