### ISSUE TITLE
mmdetection instance segmentation inference

### ISSUE THREAD

**Issue by DrawingProcess** [roboflow/supervision#765]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

mmdetection is detection and 'instance segmentation' framework. 
so, I think If there is a mask area, I think it should be return.

like below
```
return cls(
            xyxy=mmdet_results.pred_instances.bboxes.cpu().numpy(),
            mask=mmdet_results.pred_instances.masks.cpu().numpy(),
            confidence=mmdet_results.pred_instances.scores.cpu().numpy(),
            class_id=mmdet_results.pred_instances.labels.cpu().numpy().astype(int),
        )
```

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @DrawingProcess 👋🏻 Thanks a lot for your interest in supervision. I'd love to bring support for MMDetection segmentation models to Supervision.

I see you checked `Yes, I'd like to help by submitting a PR!`. Would you like to help us and add this feature?

**Comment by DrawingProcess** [comment]
Thank you for your quick reply. I sent you PR. Please check it.
See #766

**Comment by SkalskiP** [comment]
This issue was solved with https://github.com/roboflow/supervision/pull/767. Closing the issue.
