### ISSUE TITLE
How do I know where's "inside" and "outside" when using LineZone?

### ISSUE THREAD

**Issue by tiago-hansen** [roboflow/supervision#779]
### Discussed in https://github.com/roboflow/supervision/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **tiago-hansen** January 25, 2024</sup>
Hi everyone!

When I have a vertical LineZone, for example, and one object crosses the line from the left to the right. Does it sum up in "crossed_in" or "crossed_out", and how should I figure it out where is "inside" and "outside" on the image?

And what if I had an inclined or horizontal line, what is the parameter used in the trigger() method of LineZone to differentiate if it should add in "crossed_in" or "crossed_out" attributes?

I'm having a little bit of trouble trying to figure that on my own and would appreciate any help.

Thanks!</div>

**Comment by SkalskiP** [comment]
Hi @tiago-hansen 👋🏻 I'm closing this issue as we are already talking about it in the discussion Q&A section.
