### ISSUE TITLE
[CropAnnotator] - mark objects with zoomed in crop 

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#786]
### Description

Create `CropAnnotator` - whose task is to mark objects related to [`sv.Detections`](https://supervision.roboflow.com/detection/core/#detections) with zoomed-in crops.

Below is an example found on the internet. Of course, as part of this task, we would only add the part responsible for the crop.

![Screenshot 2024-01-26 at 10 14 45](https://github.com/roboflow/supervision/assets/26109316/806b9a2f-00c4-4b77-8219-13116417db49)

The API should also allow for the selection of the location of the enlarged crop using [`sv.Position`](https://supervision.roboflow.com/geometry/core/#position) (above, below, ...), as well as the choice of the `zoom_factor`.

### API

```python
class CropAnnotator(BaseAnnotator):

    def __init__(
        self,
        position: Position = Position.TOP_CENTER,
        zoom_factor: int = 2
    ):
        pass

    def annotate(
        self,
        scene: np.ndarray,
        detections: Detections,
    ) -> np.ndarray:
        pass
```

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will definitely speed up the review process. Each change must be tested by the reviewer. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by xaristeidou** [comment]
Hello there! I would love to be assigned and implement that!

**Comment by onuralpszr** [comment]
@xaristeidou good luck and have fun :)

**Comment by SkalskiP** [comment]
The master of annotators is back in business 🔥! As for `IconAnnotator`, I copied part of the description from another issue. Sorry for that.

**Comment by SkalskiP** [comment]
Hi @xaristeidou 👋🏻 Did you manage to get started with this task?

**Comment by xaristeidou** [comment]
@SkalskiP In fact yes! I dealt with some bugs in the meanwhile, and now are fixed. I have a question to get some different opinions on implementation. 

I have 2 different scenarios in mind. In cases where the cropped part of the image is going to exceed the scene dimensions based on the selected anchor `Position`:

1. The cropped part will be placed exactly to the anchor position and the rest of the exceeding cropped part will not be displayed.
2. The cropped part will be clipped to the edge of the scene, so the anchor position will be dynamically variable.

I would like to hear thoughts on that to continue further with a concept. Below I attach two examples for better representation. In both examples the anchor `Position `is assumed to be `TOP_RIGHT`


Scenario 1:

![Screenshot 2024-02-05 175000](https://github.com/roboflow/supervision/assets/65918758/5dd7ab90-5607-4018-aa51-ce08af6338ee)


Scenario 2:

![Screenshot 2024-02-05 175015](https://github.com/roboflow/supervision/assets/65918758/ac0ede1d-c876-44aa-b2e7-a9b25b359d10)

**Comment by SkalskiP** [comment]
Hi @xaristeidou 👋🏻 ! It's awesome to see the progress.

Let's go with scenario 1. It will be consistent with the behavior of other annotators.

**Comment by xaristeidou** [comment]
@SkalskiP Ok, when it is finished will get back with a PR.

**Comment by SkalskiP** [comment]
Hi @xaristeidou, 👋 `supervision-0.19.0` release is getting closer and closer. I would love to include this feature in an upcoming release. Have you been able to move the work on this feature forward? Alternatively, could you open the PR in your current state so we can finish it for you?

**Comment by xaristeidou** [comment]
@SkalskiP Hello!! Sorry for the delay to submit!! Submited #888 .

**Comment by SkalskiP** [comment]
Hi @xaristeidou 👋🏻 ! No worries!

**Comment by xaristeidou** [comment]
@SkalskiP Maybe we should close the issue due to PR #888 .

**Comment by onuralpszr** [comment]
Fixed via https://github.com/roboflow/supervision/pull/888
