### ISSUE TITLE
[ByteTrack] - change the names  and documenting input arguments

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#787]
### Description

Change the names of [input arguments](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/tracker/byte_tracker/core.py#L182) to be more intuitive and better document them so that users can easily use them while optimizing ByteTrack. Let's also consider exposing more parameters. Especially those that are available in the original implementation.

Document how changes in the values of individual arguments affect the behavior of ByteTrack.

### Reference

   - [ByteTrack paper](https://arxiv.org/pdf/2110.06864.pdf)
   - [ByteTrack code](https://github.com/ifzhang/ByteTrack)

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by Kadermiyanyedi** [comment]
Hi, I am interesting with this task. Can you assign me?

**Comment by onuralpszr** [comment]
@Kadermiyanyedi task is your, good luck and have fun 🚀

**Comment by SkalskiP** [comment]
Hi @Kadermiyanyedi 👋🏻 Did you manage to get started with this task?

**Comment by SkalskiP** [comment]
Hi @Kadermiyanyedi 👋🏻 Awesome. Thanks a lot for the update.
