### ISSUE TITLE
[ByteTrack] -  add a method to reset the state of the tracker

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#789]
### Description

Let's add a method to reset the state of the tracker - particularly useful when we want to process multiple videos one after another. Currently, part of the state is held in global variables, and even reinitializing the tracker doesn't help. It is necessary to kill the entire Python environment.

Pay attention to [`ByteTrack.tracked_tracks`](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/tracker/byte_tracker/core.py#L197), [`ByteTrack.lost_tracks`](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/tracker/byte_tracker/core.py#L198), [`ByteTrack.removed_tracks`](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/tracker/byte_tracker/core.py#L199), and [`BaseTrack._count`](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/tracker/byte_tracker/basetrack.py#L38). It may turn out that other places will also require changes.

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will definitely speed up the review process. Each change must be tested by the reviewer. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by SkalskiP** [comment]
Hi @JamesMcCullochDickens 👋🏻 This is already implemented and was released in [supervision-0.19.0](https://github.com/roboflow/supervision/releases/tag/0.19.0).

**Comment by JamesMcCullochDickens** [comment]
Alternatively I modified  ~/ByteTrack/yolox/tracker/basetrack.py to add:

@staticmethod
    def reset_ids():
        BaseTrack._count = 0
        return BaseTrack._count
        
      
Then modified the ByteTracker class as in:

    def __init__(self, args, frame_rate=30):
        BaseTrack.reset_ids() # this line is added
        self.tracked_stracks = []  # type: list[STrack]
        self.lost_stracks = []  # type: list[STrack]
        self.removed_stracks = []  # type: list[STrack]

        self.frame_id = 0
        self.args = args
        #self.det_thresh = args.track_thresh
        self.det_thresh = args.track_thresh + 0.1
        self.buffer_size = int(frame_rate / 30.0 * args.track_buffer)
        self.max_time_lost = self.buffer_size
        self.kalman_filter = KalmanFilter()
