### ISSUE TITLE
text color on Start and End Point Circles in LineZone annotator

### ISSUE THREAD

**Issue by maddust** [roboflow/supervision#79]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

just a minor thing but i noticed that circles at the end and start of the Line Counters are getting the Text Color instead of the Line color .  if im not mistaken the circles colors should match the Lines Right? 

Also i suggest if it's possible to add some "roundness" to the text boxes of the LineZone annotator and PolygonZone annotator IMO it looks more appealing than a plain rectangle 

 cv2.circle(
            frame,
            line_counter.vector.start.as_xy_int_tuple(),
            radius=5,
            color=self.text_color.as_bgr(),
            thickness=-1,
            lineType=cv2.LINE_AA,
        )
        cv2.circle(
            frame,
            line_counter.vector.end.as_xy_int_tuple(),
            radius=5,
            color=self.text_color.as_bgr(),
            thickness=-1,
            lineType=cv2.LINE_AA,
        )

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
That color scheme was actually done on purpose 🤣, but you are right; we should make that customizable. I'll think about the potential solution, and we will make that happen in the neer future. Maybe with the next release.
