### ISSUE TITLE
[LineZone] - allow per class counting  

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#790]
### Description

Currently, [sv.LineZone](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/detection/line_counter.py#L11) provides only aggregated counts - all classes are thrown into one bucket. In the past, many users have asked us to provide more granular - per class count. This can be achieved by adding `class_in_count` and `class_out_count` dictionaries that will store per-class counts.

### API

```python
class LineZone:

    def __init__(
        self,
        start: Point,
        end: Point,
        triggering_anchors: Iterable[Position] = (
            Position.TOP_LEFT,
            Position.TOP_RIGHT,
            Position.BOTTOM_LEFT,
            Position.BOTTOM_RIGHT,
        ),
    ):
        # Existing initialization code...

        self.class_in_count: Dict[int, int] = {}
        self.class_out_count: Dict[int, int] = {}

    def trigger(self, detections: Detections) -> Tuple[np.ndarray, np.ndarray]:
        crossed_in = np.full(len(detections), False)
        crossed_out = np.full(len(detections), False)

        # Required logic changes...
```

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will definitely speed up the review process. Each change must be tested by the reviewer. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by RaghavvGupta** [comment]
Hey @SkalskiP, I was wondering to work on this. I have this logic in mind, pls confirm if this approach is what you guys want?

Dictionaries to keep track of counts for each class

`self.class_in_count: Dict[str, int] = {}
self.class_out_count: Dict[str, int] = {}
`

Updating per class-in and class-out count

```
class_label = detections.class_labels[i]
                if class_label not in self.class_in_count:
                    self.class_in_count[class_label] = 0
                self.class_in_count[class_label] += 1
            else:
                self.out_count += 1
                crossed_out[i] = True

                # Updating per-class out count
                class_label = detections.class_labels[i]
                if class_label not in self.class_out_count:
                    self.class_out_count[class_label] = 0
                self.class_out_count[class_label] += 1
```

**Comment by RaghavvGupta** [comment]
Hey @SkalskiP, I was wondering to work on this. I have this logic in mind, pls confirm if this approach is what you guys want?

Dictionaries to keep track of counts for each class

`self.class_in_count: Dict[str, int] = {} self.class_out_count: Dict[str, int] = {} `

Updating per class-in and class-out count

```
class_label = detections.class_labels[i]
                if class_label not in self.class_in_count:
                    self.class_in_count[class_label] = 0
                self.class_in_count[class_label] += 1
            else:
                self.out_count += 1
                crossed_out[i] = True

                # Updating per-class out count
                class_label = detections.class_labels[i]
                if class_label not in self.class_out_count:
                    self.class_out_count[class_label] = 0
                self.class_out_count[class_label] += 1
```

**Comment by RaghavvGupta** [comment]
Hey @SkalskiP 😀👋
https://colab.research.google.com/drive/1HxRcfzqnS6axAlYPiPpe8WLblfdn6fC_?usp=sharing

This is what I was talking about. Please tell me whether this is what you want.

**Comment by SkalskiP** [comment]
Hi, @RaghavvGupta, Would that be the implementation of a current count or the total count?

**Comment by RaghavvGupta** [comment]
I have tried implementing per-class counting. It includes dictionaries `class_in_count` and `class_out_count` to store counts for each class separately. The counts within these dictionaries are updated during each call to the `trigger` method, representing the current count of objects for each class based on their movement across the line.

**Comment by SkalskiP** [comment]
@RaghavvGupta, submit PR so we can move forward with the review process.

**Comment by caiquejjx** [comment]
Hello, is this being worked on?

**Comment by LinasKo** [comment]
Hi @caiquejjx 👋 

Yes, it is. We have an outstanding PR that we need to review.

**Comment by 0xD4rky** [comment]
Hi, is the issue still open? If it is, I would like to take this up and submit a PR. 

Thanks.

**Comment by LinasKo** [comment]
Hi @0xD4rky :wave:

Thank you for asking first - that's honestly really helpful for us maintainers.

In fact - no, this is taken. I have a significant amount of code for this one that I'll be releasing in the next few days.
