### ISSUE TITLE
[LineZoneAnnotator] - make the display of in/out values optional

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#792]
### Description

Make the display of [`in_count`](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/detection/line_counter.py#L53) and [`out_count`](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/detection/line_counter.py#L54) values optional. This may require adding additional `display_in_count` and `display_out_count` arguments to [`LineZoneAnnotator`](https://github.com/roboflow/supervision/blob/3024ddca83ad837651e59d040e2a5ac5b2b4f00f/supervision/detection/line_counter.py#L165).

### API

```python
class LineZoneAnnotator:
    def __init__(
        self,
        thickness: float = 2,
        color: Color = Color.WHITE,
        text_thickness: float = 2,
        text_color: Color = Color.BLACK,
        text_scale: float = 0.5,
        text_offset: float = 1.5,
        text_padding: int = 10,
        custom_in_text: Optional[str] = None,
        custom_out_text: Optional[str] = None,
        display_in_count: bool = True,
        display_out_count: bool = True,
    ):
        # Existing initialization code...

        self.display_in_count: bool = display_in_count
        self.display_in_count: bool = display_in_count

    def annotate(self, frame: np.ndarray, line_counter: LineZone) -> np.ndarray:
        # Required logic changes...
```

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will definitely speed up the review process. Each change must be tested by the reviewer. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by Kadermiyanyedi** [comment]
Hi, I am interesting with this task. Can you assign me?

**Comment by onuralpszr** [comment]
@Kadermiyanyedi  hello and task is your good luck :)
