### ISSUE TITLE
Update Footer Logo to "X icon"

### ISSUE THREAD

**Issue by KSSaiTeja** [roboflow/supervision#812]
**Description:**

The current footer logo uses the old Twitter logo. Let's switch to the "X icon" for a cleaner look.

**Expected Behavior:**

Update the footer logo to the "X icon" for a consistent look.

**Comment by onuralpszr** [comment]
@SkalskiP  fixed in PR

**Comment by onuralpszr** [comment]
<img width="1555" alt="image" src="https://github.com/roboflow/supervision/assets/1688848/55fd68e9-00be-4a2b-9c20-32948d235c36">

**Comment by SkalskiP** [comment]
Thanks a lot for taking care of this, @onuralpszr ! 🔥

**Comment by onuralpszr** [comment]
> Thanks a lot for taking care of this, @onuralpszr ! 🔥

You are welcome !!  👍
