### ISSUE TITLE
Hide console output when objects are detected

### ISSUE THREAD

**Issue by jacobpchen** [roboflow/supervision#82]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Is there a way to hide the output to console when objects are detected?

**Comment by SkalskiP** [comment]
Hi @jacobpchen 👋🏻! Could you help me out what `console output` are we talking about?

**Comment by jacobpchen** [comment]
When the detection is running this is printed in console:

0: 384x640 (no detections), 1072.9ms
Speed: 1.7ms preprocess, 1072.9ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 (no detections), 1055.3ms
Speed: 1.0ms preprocess, 1055.3ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 (no detections), 1232.2ms
Speed: 1.7ms preprocess, 1232.2ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 3 cars, 1 truck, 955.4ms
Speed: 1.5ms preprocess, 955.4ms inference, 6.8ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 3 cars, 1 truck, 905.9ms
Speed: 1.5ms preprocess, 905.9ms inference, 3.1ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 2 cars, 1 truck, 722.2ms
Speed: 1.0ms preprocess, 722.2ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 3 cars, 739.7ms
Speed: 1.2ms preprocess, 739.7ms inference, 3.1ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 2 cars, 1073.4ms
Speed: 1.3ms preprocess, 1073.4ms inference, 3.4ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 2 cars, 1 truck, 1159.1ms
Speed: 0.9ms preprocess, 1159.1ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 2 cars, 877.3ms
Speed: 2.1ms preprocess, 877.3ms inference, 3.2ms postprocess per image at shape (1, 3, 640, 640)

0: 384x640 2 cars, 1 truck, 1359.9ms

I was wondering if there was a way to hide all of this output.

**Comment by SkalskiP** [comment]
Oh. That log is generated by YOLOv8 (`ultralytics` pip package). Feel free to create an issue here: https://github.com/ultralytics/ultralytics/issues

**Comment by araneto** [comment]
Hey @jacobpchen 

You can use the 'verbose=False' argument to disable the output generated by YOLOv8.

`model.predict(source=0, verbose=False)`

**Comment by jacobpchen** [comment]
Hi @araneto thank you! Your solution worked perfectly!

**Comment by fortmea** [comment]
Found out you can also set an environment variable:
In utils/__init__.py there's this line:
`VERBOSE = str(os.getenv("YOLO_VERBOSE", True)).lower() == "true"  # global verbose mode`
So to disable the logging, just use` os.environ["YOLO_VERBOSE"] = "False"` Somewhere in your code
