### ISSUE TITLE
[KeyPoints] - create `KeyPoints` class and implement `from_ultralytics` method

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#824]
### Description

- The `KeyPoints` class should be general. Flexible enough to support pose estimation, retina tracking, face landmarks, and other use cases. 
- The `KeyPoints` class should contain the following fields:
    - `xy` (`np.ndarray`): An array of shape `(N, K, 2)` containing the key points coordinates.
    - `confidence` (`Optional[np.ndarray`]): An array of shape `(N, K)` containing the confidence scores.
    - `data` (`Dict[str, Union[np.ndarray, List]]`): A dictionary containing additional data where each key is a string representing the data type, and the value is either a NumPy array or a list of corresponding data.
- The code should be placed in `supervision/keypoints/core.py`.
- Create a new KeyPoints section in the documentation.
- Ensure users know the code is still experimental and subject to change.

### API

```python
@dataclass
class KeyPoints:
    xy: np.ndarray
    confidence: Optional[np.ndarray] = None
    data: Dict[str, Union[np.ndarray, List]] = field(default_factory=dict)

    def __len__(self):
        return len(self.xy)

    def __eq__(self, other: KeyPoints):
        pass

    @classmethod
    def from_ultralytics(cls, ultralytics_results) -> KeyPoints:
        pass
```

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will definitely speed up the review process. Each change must be tested by the reviewer. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by onuralpszr** [comment]
I like to work in this one @SkalskiP

**Comment by SkalskiP** [comment]
@onuralpszr I like this idea a lot. Let's start with only the `KeyPoints` class. No annotators for now.

**Comment by onuralpszr** [comment]
> @onuralpszr I like this idea a lot. Let's start with only the `KeyPoints` class. No annotators for now.

Okay lets do it.

**Comment by adaiale** [comment]
I'm willing to help if you guys need an extra set of hands, I would love to have this implemented.

**Comment by onuralpszr** [comment]
> I'm willing to help if you guys need an extra set of hands, I would love to have this implemented.

Thank you, I am sending this week(tomorrow) and add others too. I wanted that to be  done as well

**Comment by SkalskiP** [comment]
@onuralpszr, please make sure to stick to the scope defined for this task. We want only to do things described in this issue and nothing more. I want to work on the next steps in the next issues.

**Comment by onuralpszr** [comment]
> Hi @onuralpszr 👋🏻 Have you managed to make progress on this topic? If not, it's okay, just please let me know. Working on the KeyPoints API is a significant part of our plan for Q2 2024, and this task needs to be done now. I'll just assign it to myself :)

I did progress and will push today ASAP

**Comment by SkalskiP** [comment]
Thanks a lot! 🙏🏻

**Comment by SkalskiP** [comment]
I'm closing this issue as `KeyPoints` support was added in https://github.com/roboflow/supervision/pull/1128
