### ISSUE TITLE
TypeError: BoxAnnotator.annotate() got an unexpected keyword argument 'custom_colors_lookup'

### ISSUE THREAD

**Issue by hoongyuan** [roboflow/supervision#834]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

First of all, I really like how supervision is providing so many features to integrate with yolov8 detection

I am trying to give assign different colors to some of the bounding boxes by using "custom_color_lookup", but it appears that this error showed up:

TypeError: BoxAnnotator.annotate() got an unexpected keyword argument 'custom_colors_lookup' 
 
Here is my code on calling the annotate() :

"colors" is initiated as an array

<img width="439" alt="image" src="https://github.com/roboflow/supervision/assets/62897998/b928a289-5541-4379-b99f-506c92b3d57a">

not sure if i am doing anything wrong here. Perhaps if there is other way of achieving this, please do let me know! thank you

**Comment by SkalskiP** [comment]
Hi @hoongyuan 👋🏻, I'm glad you like Supervision! The reason is you use `BoxAnnotator` - it is old and no longer supported. You should use `BoundingBoxAnnotator`.

I'm closing the issue. Feel free to reopen if you'll still experience any issues.

**Comment by hoongyuan** [comment]
Thats a very careless mistake of mine, thank you for your fast response!
