### ISSUE TITLE
[LineZone] - flip in/out line crossing directions

### ISSUE THREAD

**Issue by harshaneo17** [roboflow/supervision#838]
## Description

Between `supervision-0.17.0` and `supervision-0.18.0`, releases in/out of the direction of the crossing were accidentally changed. Given that `LineZone` is one of the oldest features we have we do not want to make life difficult for users and want to restore the previous behavior. The change made in this [PR](https://github.com/roboflow/supervision/pull/735), most likely in this [line](https://github.com/roboflow/supervision/blob/0ccb0b85adee4202f5fe96834a374a057bbbd9da/supervision/detection/line_counter.py#L140), is responsible for the change in behavior.

https://github.com/roboflow/supervision/blob/0ccb0b85adee4202f5fe96834a374a057bbbd9da/supervision/detection/line_counter.py#L140

### Minimal Reproducible Example

You can easily confirm the crossing direction change between `supervision-0.17.0` and `supervision-0.18.0` releases using this [notebook](https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8-and-supervison.ipynb). Here are example results.

__supervision-0.17.0__

https://github.com/roboflow/supervision/assets/26109316/32e0f95c-9204-4703-ab25-c2255a597720

__supervision-0.18.0__

https://github.com/roboflow/supervision/assets/26109316/af6db77e-24f8-4338-9925-3c80afe178f8

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by SkalskiP** [comment]
Hi @harshaneo17 👋🏻 Thanks for your interest in supervision. I just confirmed. You are right. Let me update the task title and description.

**Comment by Kadermiyanyedi** [comment]
Hi, I am interesting with this task. Can you assign me

**Comment by onuralpszr** [comment]
@Kadermiyanyedi you already have experience with linezones it should be easy for you handle it, good luck 👍 😉

**Comment by Kadermiyanyedi** [comment]
> Good luck, @Kadermiyanyedi 🤞🏻 Most likely, you need to change `>` into `<`. But that's just my guess.

Yes, you are right :) I changed the ">" character and opened PR :) Thank you very much for your guidance and detailed job description.

**Comment by onuralpszr** [comment]
Issue fix via #845, @Kadermiyanyedi
