### ISSUE TITLE
[PolygonZone] - allow `triggering_position` to be `Iterable[Position]`

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#844]
### Description

Update [`PolygonZone`](https://github.com/roboflow/supervision/blob/87a4927d03b6d8ec57208e8e3d01094135f9c829/supervision/detection/tools/polygon_zone.py#L15) logic, triggering the zone when not one anchor but multiple anchors are inside the zone. This type of logic is already implemented in [`LineZone`](https://github.com/roboflow/supervision/blob/87a4927d03b6d8ec57208e8e3d01094135f9c829/supervision/detection/line_counter.py#L12).

- Rename `triggering_position` to `triggering_anchors` to be consistent with the `LineZone` naming convention.
- `Update type of argument from `Position` to `Iterable[Position]
- Maintain the default behavior. The zone should, by default, be triggered by `Position.BOTTOM_CENTER`.

### API

```python
class PolygonZone:

    def __init__(
        self,
        polygon: np.ndarray,
        frame_resolution_wh: Tuple[int, int],
        triggering_anchors: Iterable[Position] = (Position.BOTTOM_CENTER, )
    ):
        pass

    def trigger(self, detections: Detections) -> np.ndarray:
        pass
```

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by LeviVasconcelos** [comment]
Hi, I would like to work on this.

**Comment by SkalskiP** [comment]
Hi @LeviVasconcelos 👋🏻 Go for it! Let us know if you need help.

**Comment by LeviVasconcelos** [comment]
Hi @SkalskiP,

PR is ready for review, let me know what you think when you find time :).

Best,

**Comment by onuralpszr** [comment]
This issue completed via PR #910 closing as complete

**Comment by LinasKo** [comment]
Hi @JShengP :wave:

By any chance, could you attach the image you used, before annotation? Are you using a custom model, or one of our or ultralytics' pretrained models?

**Comment by PetrosKataras** [comment]
Hey, also faced an issue with false positives in the case of `Position.CENTER`

I tracked it down in the clipping happening inside `PolygonZone` and specifically the `trigger` function - the way it is right now it actually modifies the bounding box coordinates before getting the anchor points which can lead to wrong calculations.

The following calculates anchor positions and then clips any points outside the polygon area which seems to fix the issue for me.

```

class PolygonZone:
    def __init__(
        self,
        polygon: npt.NDArray[np.int64],
        triggering_anchors: Iterable[Position] = (Position.BOTTOM_CENTER,),
    ):  
        self.polygon = polygon.astype(int)
        self.triggering_anchors = triggering_anchors
        if not list(self.triggering_anchors):
            raise ValueError("Triggering anchors cannot be empty.")

        self.current_count = 0 

        # Create mask with sufficient size to cover polygon
        x_max, y_max = np.max(polygon, axis=0)
        # Add padding to ensure we have room for the mask edges
        self.frame_resolution_wh = (x_max + 2, y_max + 2)
        self.mask = polygon_to_mask(
            polygon=polygon,
            resolution_wh=self.frame_resolution_wh
        )

    def trigger(self, detections: Detections) -> npt.NDArray[np.bool_]:
        # Get anchor coordinates for each detection without modifying original boxes
        all_anchors = []
        for anchor in self.triggering_anchors:
            anchor_coords = detections.get_anchors_coordinates(anchor)
                
            # Round coordinates for pixel access
            anchor_coords = np.round(anchor_coords)
                
            # Check which points are within frame bounds
            within_bounds = ( 
                (anchor_coords[:, 0] >= 0) & 
                (anchor_coords[:, 0] < self.frame_resolution_wh[0]) &
                (anchor_coords[:, 1] >= 0) & 
                (anchor_coords[:, 1] < self.frame_resolution_wh[1])
            )   
                
            # Create safe coordinates for mask indexing
            safe_coords = np.clip(
                anchor_coords,
                [0, 0], 
                [self.frame_resolution_wh[0] - 1, self.frame_resolution_wh[1] - 1]
            ).astype(int)
                    
            # Get mask values for the coordinates
            mask_values = self.mask[safe_coords[:, 1], safe_coords[:, 0]] 
                
            # Any point outside bounds is considered outside the polygon
            mask_values = mask_values & within_bounds
                    
            all_anchors.append(mask_values)

        all_anchors = np.array(all_anchors)
    
        # Detection is in zone only if all specified anchors are inside
        is_in_zone = np.all(all_anchors, axis=0)
                
        self.current_count = int(np.sum(is_in_zone))
        return is_in_zone
```
