### ISSUE TITLE
How can I plot multiple mask on the same image

### ISSUE THREAD

**Issue by assia855** [roboflow/supervision#85]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Thanks for this library. Following segment anything tutorial, I would like to plot on the same image all the masks and on the original image all the annotation boxes. Can you share a code on how can I do it please?

**Comment by SkalskiP** [comment]
Hi, @assia855! 👋🏻 

So you want o have two images side by side. Image + masks on the left and image + boxes on the right?

**Comment by assia855** [comment]
yes, I used 'cv2.bitwise_or' but the color of my masks and the color of the annotation boxes isn't good. Is there any other way to do it more efficient please

**Comment by SkalskiP** [comment]
@assia855 did you saw this notebook: https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-segment-anything-with-sam.ipynb

**Comment by assia855** [comment]
Hi @SkalskiP  thanks for your replay, I'm following this tutorial but in seat of one box as you did I would like to draw multiple masks

**Comment by SkalskiP** [comment]
Do you want to have this effect but with boxes on the left? 

![download (99)](https://user-images.githubusercontent.com/26109316/236457556-829d1ffa-d2a2-43cf-9023-058d19718389.png)

**Comment by assia855** [comment]
yes please I already used 'cv2.bitwise_or' but I had a weird color as output

**Comment by SkalskiP** [comment]
@assia855 sorry I was quit busu. Do you still need that viz?

**Comment by assia855** [comment]
@SkalskiP it's okay, I found a way to resolve it thanks a lot
