### ISSUE TITLE
[Annotators] - enable Annotators to accept image as `np.ndarray` or `PIL.Image`

### ISSUE THREAD

**Issue by SkalskiP** [roboflow/supervision#859]
### Description

Allow Supervision annotators to accept the `scene` argument as `np.ndarray` or `PIL.Image`.

Using Supervision annotators in combination with tools that process images as `PIL.Image` (Gradio, Transformers, MMDetection) is very cumbersome. It usually requires a series of conversions, as shown below. We would like to hide this complexity inside the annotators.

```python
import cv2
import supervision as sv
from PIL import Image

bounding_box_annotator = sv.BoundingBoxAnnotator()

image = np.array(image) # Convert PIL.Image to np.ndarray
image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # Convert RGB to BGR
image = bounding_box_annotator.annotate(image, detections)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # Convert BGR to RGB
image = Image.fromarray(image) # Convert np.ndarray to PIL.Image
```

- The annotator should return the image in the same format as it was passed in.
- DO NOT reimplement all annotators in Pillow. Internally, any annotator should continue to use OpenCV to draw everything that needs to be drawn. 

### API

Here is the updated `BoundingBoxAnnotator` API. As part of this task, the APIs of all annotators should be similarly modified.

```python
class BoundingBoxAnnotator(BaseAnnotator):

    def __init__(
        self,
        color: Union[Color, ColorPalette] = ColorPalette.DEFAULT,
        thickness: int = 2,
        color_lookup: ColorLookup = ColorLookup.CLASS,
    ):
        # constructor remains exactly the same

    def annotate(
        self,
        scene: Union[np.ndarray, Image.Image],
        detections: Detections,
        custom_color_lookup: Optional[np.ndarray] = None,
    ) -> Union[np.ndarray, Image.Image]:
        # updated implementation 
```

### Additional

- Note: Please share a Google Colab with minimal code to test the new feature. We know it's additional work, but it will speed up the review process. The reviewer must test each change. Setting up a local environment to do this is time-consuming. Please ensure that Google Colab can be accessed without any issues (make it public). Thank you! 🙏🏻

**Comment by LinasKo** [comment]
I'll grab this one.

Got the code ready and tested, except for `TraceAnnotator` and `PixelateAnnotator`. Just need to write it up, make the Colab.

**Comment by LinasKo** [comment]
Ready for review, when you find the time

**Comment by SkalskiP** [comment]
This was implemented via https://github.com/roboflow/supervision/pull/875.
