### ISSUE TITLE
Always tracker_id=None 

### ISSUE THREAD

**Issue by storm12t48** [roboflow/supervision#88]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hello everybody

I still have tracker_id in None , I have just tried everything on the net

```
ret, frame = cap.read()
       result= model.track(frame,tracker="botsort.yaml",device=0,agnostic_nms=True,show_labels=True,half=True,conf=confidence,vid_stride=True,iou=0.25)[0]

detections = sv.Detections.from_yolov8(result)
if result.boxes.id is not None:
     detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
```

**Comment by SkalskiP** [comment]
Hi @storm12t48 👋🏻! From what I see, you don't have probably the most important parameter of them all: `stream=True`. Could you add it and test it once again?

**Comment by zburq** [comment]
I had a similar issue when merging a sequence of detections, starting with an initial empty detection `det_init = Detections.empty()`. The empty detection doesn't have `tracker_id`: 

https://github.com/roboflow/supervision/blob/e16cca43497a6274ba3e15c3ad4913a88978f753/supervision/detection/core.py#L360

For dlll subsequent detections, when merged, the tracker_id is set to None here:

https://github.com/roboflow/supervision/blob/e16cca43497a6274ba3e15c3ad4913a88978f753/supervision/detection/core.py#L405

**Comment by SkalskiP** [comment]
@zburq those are two separate issues. Lrt me move your sorry into a separate issue.

**Comment by storm12t48** [comment]
> Hi @storm12t48 👋🏻! From what I see, you don't have probably the most important parameter of them all: `stream=True`. Could you add it and test it once again?

thank you I didn't know that I still had these parameters in the loop
