### ISSUE TITLE
Can we display the contours of detections in dotted lines

### ISSUE THREAD

**Issue by storm12t48** [roboflow/supervision#90]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Question

Hello everyone 

Can we display the contours of detections in dotted lines in BoxAnnotator?
best regards

**Comment by SkalskiP** [comment]
Hi @storm12t48 👋🏻! Not at this moment :/ But we might think about adding that in future.
