### ISSUE TITLE
Model Evaluation

### ISSUE THREAD

**Issue by hardikdava** [roboflow/supervision#92]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

It would be great if we can evaluate model performance with supervision detections. 

### Use case

- Easy performance comparision between multiple models
- Easy debug process of models

### Additional

Object detections models can be evaluated by [mean average precision](https://github.com/rafaelpadilla/Object-Detection-Metrics).
Instance segmentation models can be evaluated by mean average precision with mIOU.
Multi object trackers can be evaluated by [py-motmetrics](https://github.com/cheind/py-motmetrics)

If one can create/suggest architecture then I can help with implementation.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi, @hardikdava 👋🏻! We are actually working on integrating evaluation capabilities into supervision. 

@capjamesg take a look here :)

**Comment by hardikdava** [comment]
Thank you for your reply. It seems interesting and promising.

**Comment by SkalskiP** [comment]
I'm closing this issue as we already started to work on model evaluation in a separate issue https://github.com/roboflow/supervision/issues/140
