### ISSUE TITLE
[Smoother] - `tracker_id` is `None` when there is no detection for an extended period

### ISSUE THREAD

**Issue by vhuard** [roboflow/supervision#928]
### Bug

I have code that performs detections on video, which operates smoothly without the smoother function. However, upon integrating the smoother function, I encounter the following error:

```
Traceback (most recent call last):
  File "/content/script_detection.py", line 165, in <module>
    processor.process_video()
  File "/content/script_detection.py", line 67, in process_video
    annotated_frame = self.process_frame(frame)
  File "/content/script_detection.py", line 121, in process_frame
    return self.annotate_frame(frame, detections)
  File "/content/script_detection.py", line 86, in annotate_frame
    in zip(detections.tracker_id, detections.confidence, detections.class_id)
TypeError: 'NoneType' object is not iterable
```

### Environment

- Supervision: 0.18.0

### Minimal Reproducible Example

```python
def annotate_frame(
    self, frame: np.ndarray, detections: sv.Detections
) -> np.ndarray:
    annotated_frame = frame.copy()

    labels = [
            f"#{tracker_id} {class_id}"
            for tracker_id, confidence, class_id
            in zip(detections.tracker_id, detections.confidence, detections.class_id)
    ]

    annotated_frame = self.trace_annotator.annotate(
        scene=annotated_frame, detections=detections
    )
    annotated_frame = self.bounding_box_annotator.annotate(
        scene=annotated_frame, detections=detections
    )
    annotated_frame = self.label_annotator.annotate(
        scene=annotated_frame, detections=detections, labels=labels
     )
    annotated_frame = self.percentage_bar_annotator.annotate(
        scene=annotated_frame, detections=detections
    )


    return annotated_frame

def process_frame(self, frame: np.ndarray) -> np.ndarray:
    results = self.model(
        frame, verbose=False, conf=self.conf_threshold, iou=self.iou_threshold
    )[0]
    detections = sv.Detections.from_ultralytics(results)
    detections = detections[detections.confidence > args.confidence_threshold]
    detections = detections.with_nms(threshold=args.iou_threshold)
    detections = self.tracker.update_with_detections(detections=detections)
    detections = self.smoother.update_with_detections(detections=detections)
   

    return self.annotate_frame(frame, detections)
```

**Comment by LinasKo** [comment]
This will happen if there's no detections or all detections go out of view for long enough. `Detections.empty()` only initialized `xyxy`, `confidence` and `class_id` - not `tracker_id`.

**Comment by vhuard** [comment]
Hi @SkalskiP and @LinasKo I will provide a video.
It is a camera view from mountain peak with most of time no detections and suddenly wildfire start.
Since smoke is quite versatile, detection smoother will help me out to spot the wildfire start direction more accurately.
Should I do detections smoother before the tracking?

**Comment by LinasKo** [comment]
@vhuard, could you please also tell which of the variables in the `detections` is `None` in your example, right before `zip` gets called?

That's what ultimately causes the error, but it's unclear whether it's `detections.tracking_id`, `detections.confidence` or `detections.class_id`.

**Comment by vhuard** [comment]
there is no detections at all so everything is None in some frames
![1657755474_-01800](https://github.com/roboflow/supervision/assets/129664630/cef97213-6fb2-47dc-b673-a0a4dce0349a)
video is too big for github so pese one frame with no detections

**Comment by LinasKo** [comment]
@vhuard, I was wrong about the workaround. I suggest trying the following code. In my tests it successfully avoids the error:

```
labels = [f"#{tracker_id} {class_id}" for _, _, _, class_id, tracker_id, _ in detections]
```

Thanks a lot for reporting the issue. Do let me know if it's still failing!

(I suggest we keep this open until we fix the underlying problem)
