### ISSUE TITLE
Load OBB Detection, ideally from a Dictionary/Json

### ISSUE THREAD

**Issue by DaleBestOrbexLabs** [roboflow/supervision#958]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

To be able to create a Detection object to then run through Byte Track from the OBB information that is stored in a Dictionary/Json.

### Use case

Ideally this would allow to run the OBB prediction separately and save the information to a JSON file and then later parse the JSON file to get the prediction results and run it frame by frame through Byte Track.

This way would allow much faster revision and tuning on the tracker variables as it wouldn't require re-running the costly inference over and over again to find good fits.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @DaleBestOrbexLabs 👋🏻 Thanks for your interest in supervision. `supervision-0.19.0` will add support for saving detections to [CSV](https://supervision.roboflow.com/develop/detection/tools/save_detections/) and [JSON](https://github.com/roboflow/supervision/pull/819) file. 

If I understood you correctly, you would like us to also add a function for loading these detections?

**Comment by DaleBestOrbexLabs** [comment]
Hi @SkalskiP, yup pretty much a Detections.from_json()/Detections.from_dict() function.

**Comment by SkalskiP** [comment]
Hi @DaleBestOrbexLabs, I think it's a good idea, but we'll proceed with it only if it integrates seamlessly with the `CSVSink` and `JSONSink` API.

**Comment by Houangnt** [comment]
> Hi @DaleBestOrbexLabs, I think it's a good idea, but we'll proceed with it only if it integrates seamlessly with the `CSVSink` and `JSONSink` API.
How i can crop the region of an image after a model has detected objects ? tks:
![image](https://github.com/roboflow/supervision/assets/48252530/881973f1-000c-41ab-9961-20266c78e6a9)

**Comment by SkalskiP** [comment]
Hi, @DaleBestOrbexLabs. We plan to enable loading OBB in YOLO format via https://github.com/roboflow/supervision/issues/1096. 
I also think that for the time being, we will not be adding support for CSV and JSON. I hope the YOLO format will be sufficient for you.

**Comment by Bhavay-2001** [comment]
Hi @SkalskiP @LinasKo, I think this issue is somewhat similar to the one I have done rn. Can you describe the task in more detail so that maybe we can look for this issue? 
Thanks

**Comment by Bhavay-2001** [comment]
> Hi @SkalskiP, yup pretty much a Detections.from_json()/Detections.from_dict() function.

@SkalskiP @LinasKo, I am checking out the `core.py` file from the `Detections` module and I see that the detections are being loaded from all different kinds of repos like `tensorflow` and `ultralytics`. While loading from `json` or `dict`, which model do we need to get the results from? Like from where do we get the results to load the detections.

**Comment by LinasKo** [comment]
Hi @Bhavay-2001,

I wanted to respond to say that I see your questions; I apologize for the slow pace on my end.
I'm making time to respond as soon as I can; hopefully this week.

**Comment by Bhavay-2001** [comment]
Sure Linkas, Please take your time and reply accordingly. Thanks

**Comment by LinasKo** [comment]
Hi @Bhavay-2001,

This ticket suggested `load_csv` and `load_json`. Your work partially replaces the need by allowing loads from yolo format, and solves the linked issue #1096.

Let's wait and see whether we get any more requests for JSON and CSV loading before we jump into implementation 😉

**Comment by Bhavay-2001** [comment]
Alright @LinasKo, any other issues you may suggest that I can work on? Most of the issues are already assigned to someone so I don't know if they are working or not?

**Comment by LinasKo** [comment]
Hi @Bhavay-2001 ,

Indeed, there aren't many open ones at the moment. I'm happy to ping you when we have some.

Do note that I'd have even less time to help out and provide guidance :wink:

**Comment by Bhavay-2001** [comment]
Thanks for the reply @LinasKo. I'll check and if I see some idle issues, I'll start my work and let you know.

Meanwhile, if you would like to suggest some new feature(which is not mentioned in the issues) or would like me to try something new, Please let me know and maybe we can have a discussion about that. 
Thanks

**Comment by LinasKo** [comment]
The correct way is to ask on the issue first so I can assign the contributor.
