### ISSUE TITLE
sv.plot_images_grid shows nothing

### ISSUE THREAD

**Issue by gregi12** [roboflow/supervision#97]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar bug report.

### Bug

As in the title, function sv.plot_images_grid returns nothing even though right images (numpy.ndarray) are given as arguments. 
![346099528_1420932465351525_2381894506680403516_n](https://github.com/roboflow/supervision/assets/114067438/e301f056-57b4-4586-9029-efbe426dd39c)

I'm using SAM model, to detect holes in targets, and results [2][1] is just one of four parts of detected_target, because without partitioning, model wasn'tso accurate in his detections. For example, cv2_imshow(results[2][1]) properly shows detected image. 

![346100080_3441502842789925_6102147254246235557_n](https://github.com/roboflow/supervision/assets/114067438/b554e90b-748b-4236-8b66-b331dcda9fc8)

I need this to visualize which masks are holes, and due to that bug I can't run sv.plot_images_grid on masks 

![346099349_956906932019449_6642063735784182876_n](https://github.com/roboflow/supervision/assets/114067438/9cab8dd5-f55f-4e9d-b8ac-3ef84de3e265)

Am I doing something wrong or it's just a bug? Thanks for help in advance.

### Environment

I installed packages using this command from yours tutorial: !pip install -q jupyter_bbox_widget dataclasses-json supervision
so I assume it's the newest version of supervision. Python version on colab is 3.10 if I'm not mistaken.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment]
Hi @gregi12 👋🏻! Did you try to add `%matplotlib inline` before `sv.plot_images_grid` call?

**Comment by gregi12** [comment]
Yes, I've just checked it and it helped, thanks a lot!

**Comment by SkalskiP** [comment]
Awesome 🔥 Closing issue!
