### ISSUE TITLE
`Detections.export()` - a method to write detections to file

### ISSUE THREAD

**Issue by zburq** [roboflow/supervision#98]
### Search before asking

- [X] I have searched the Supervision [issues](https://github.com/roboflow/supervision/issues) and found no similar feature requests.

### Description

A new method for `Detections` class to write the contents to file in various formats. 

### Use case

- Bounding boxes and annotations saved to file in YOLO format (txt), without saving the video.
- These may be opened in CVAT for manual inspection or correction etc. 
- e.g., https://opencv.github.io/cvat/docs/manual/advanced/formats/format-yolo/

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by maddust** [comment]
According to the official [python usage source]from (https://docs.ultralytics.com/python/) this can be done by:

from ultralytics.yolo.engine.model import YOLO

model = YOLO("yolov8s.pt")
results = model.predict(source='ultralytics/assets', save=True, save_txt=True)

**Comment by SkalskiP** [comment]
@maddust remember that we try to support other models than YOLOv8 too 😉

**Comment by SkalskiP** [comment]
I just wanted to let you know that I'm closing the issue for now. @zburq feel free to open it if you think our current API is still not sufficient enough.
